/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.118
 * Generated at: 2026-06-12 01:31:54 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.board;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.hatshop.board.BoardDTO;
import com.hatshop.board.BoardDAO;
import com.hatshop.member.MemberDTO;

public final class boardWriteProc_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(4);
    _jspx_imports_classes.add("com.hatshop.board.BoardDTO");
    _jspx_imports_classes.add("com.hatshop.board.BoardDAO");
    _jspx_imports_classes.add("com.hatshop.member.MemberDTO");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');
      out.write('\n');

    /* POST 전용 처리 페이지 */
    if (!"POST".equalsIgnoreCase(request.getMethod())) {
        response.sendRedirect(request.getContextPath() + "/board/boardList.jsp");
        return;
    }

    /* 로그인 체크 */
    MemberDTO loginUser = (MemberDTO) session.getAttribute("loginUser");
    if (loginUser == null) {
        session.setAttribute("flashError", "로그인이 필요합니다.");
        response.sendRedirect(request.getContextPath() + "/member/login.jsp");
        return;
    }

    /* 파라미터 수집 */
    String title   = request.getParameter("boardTitle");
    String content = request.getParameter("boardContent");
    String typeParam = request.getParameter("boardType");

    /* 게시글 유형 — ADMIN 만 공지 설정 가능 */
    String boardType = "NORMAL";
    if (loginUser.isAdmin() && "NOTICE".equals(typeParam)) {
        boardType = "NOTICE";
    }

    /* 서버 유효성 검사 */
    if (title == null || title.trim().isEmpty()) {
        session.setAttribute("flashError", "제목을 입력해주세요.");
        response.sendRedirect(request.getContextPath() + "/board/boardWrite.jsp");
        return;
    }
    if (title.trim().length() > 200) {
        session.setAttribute("flashError", "제목은 200자 이하로 입력해주세요.");
        response.sendRedirect(request.getContextPath() + "/board/boardWrite.jsp");
        return;
    }
    if (content == null || content.trim().isEmpty()) {
        session.setAttribute("flashError", "내용을 입력해주세요.");
        response.sendRedirect(request.getContextPath() + "/board/boardWrite.jsp");
        return;
    }

    /* DB 저장 */
    try {
        BoardDTO dto = new BoardDTO();
        dto.setMemberId   (loginUser.getMemberId());
        dto.setBoardTitle (title.trim());
        dto.setBoardContent(content.trim());
        dto.setBoardType  (boardType);

        int boardNo = new BoardDAO().insert(dto);
        session.setAttribute("flashSuccess", "게시글이 등록되었습니다.");
        response.sendRedirect(request.getContextPath() + "/board/boardDetail.jsp?boardNo=" + boardNo);

    } catch (Exception e) {
        session.setAttribute("flashError", "게시글 등록 중 오류가 발생했습니다. 잠시 후 다시 시도해주세요.");
        response.sendRedirect(request.getContextPath() + "/board/boardWrite.jsp");
    }

      out.write('\n');
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
