/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.118
 * Generated at: 2026-06-19 01:23:15 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.member;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.hatshop.member.MemberDTO;
import com.hatshop.util.HtmlUtils;
import com.hatshop.util.Logger;
import com.hatshop.order.OrderDAO;
import com.hatshop.order.OrderDTO;
import com.hatshop.order.OrderDTO.OrderDetailDTO;
import com.hatshop.db.DBConn;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.List;
import java.util.Map;
import java.util.HashMap;
import java.net.URLEncoder;
import com.hatshop.cart.CartDAO;
import com.hatshop.member.MemberDTO;

public final class mypage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.LinkedHashMap<java.lang.String,java.lang.Long>(5);
    _jspx_dependants.put("/WEB-INF/inc/header.jsp", Long.valueOf(1781831986439L));
    _jspx_dependants.put("/WEB-INF/inc/nav.jsp", Long.valueOf(1781177216000L));
    _jspx_dependants.put("/WEB-INF/inc/footer.jsp", Long.valueOf(1781756931479L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1781088682000L));
    _jspx_dependants.put("jar:file:/C:/Users/gram14/OneDrive/바탕%20화면/Projact/jsp/hatshop-server/tomcat/webapps/hatshop/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(20);
    _jspx_imports_classes.add("com.hatshop.member.MemberDTO");
    _jspx_imports_classes.add("com.hatshop.util.HtmlUtils");
    _jspx_imports_classes.add("com.hatshop.util.Logger");
    _jspx_imports_classes.add("com.hatshop.order.OrderDAO");
    _jspx_imports_classes.add("com.hatshop.order.OrderDTO");
    _jspx_imports_classes.add("com.hatshop.order.OrderDTO.OrderDetailDTO");
    _jspx_imports_classes.add("com.hatshop.db.DBConn");
    _jspx_imports_classes.add("java.sql.Connection");
    _jspx_imports_classes.add("java.sql.PreparedStatement");
    _jspx_imports_classes.add("java.sql.ResultSet");
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("java.util.Map");
    _jspx_imports_classes.add("java.util.HashMap");
    _jspx_imports_classes.add("java.net.URLEncoder");
    _jspx_imports_classes.add("com.hatshop.cart.CartDAO");
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fchoose;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fotherwise;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fchoose = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fotherwise = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fchoose.release();
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fotherwise.release();
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');
      out.write('\n');

    MemberDTO loginUser = (MemberDTO) session.getAttribute("loginUser");
    if (loginUser == null) {
        response.sendRedirect(request.getContextPath() + "/member/login.jsp?redirectURL=/member/mypage.jsp");
        return;
    }

    String flashSuccess = (String) session.getAttribute("flashSuccess");
    String flashError   = (String) session.getAttribute("flashError");
    session.removeAttribute("flashSuccess");
    session.removeAttribute("flashError");

    String tab = request.getParameter("tab");
    if (tab == null) tab = "orders";

    /* 주문 목록 로드 (+ 각 주문의 품목 상세를 채워 썸네일 표시) */
    List<OrderDTO> orderList = null;
    try {
        OrderDAO orderDAO = new OrderDAO();
        orderList = orderDAO.getOrderList(loginUser.getMemberId());
        for (OrderDTO o : orderList) {
            try {
                OrderDTO full = orderDAO.getOrderDetail(o.getOrderNo(), loginUser.getMemberId());
                if (full != null) o.setDetails(full.getDetails());
            } catch (Exception inner) {
                Logger.error(this.getClass(), "mypage.jsp 주문 상세 보강 오류: orderNo=" + o.getOrderNo(), inner);
            }
        }
    } catch (Exception e) {
        Logger.error(this.getClass(), "mypage.jsp 주문목록 조회 오류: memberId=" + loginUser.getMemberId(), e);
        orderList = new java.util.ArrayList<>();
    }

    /* 주문별 환불 상태 (활성 신청만) 맵 로드 */
    Map<Integer, String> refundStatusMap = new HashMap<>();
    try {
        Connection conn = DBConn.getConnection();
        String sql = "SELECT order_no, refund_status FROM refund WHERE member_id = ? AND refund_status IN ('REQUESTED','APPROVED','COMPLETED')";
        try (PreparedStatement ps = conn.prepareStatement(sql)) {
            ps.setString(1, loginUser.getMemberId());
            try (ResultSet rs = ps.executeQuery()) {
                while (rs.next()) {
                    refundStatusMap.put(rs.getInt("order_no"), rs.getString("refund_status"));
                }
            }
        }
    } catch (Exception e) {
        Logger.error(this.getClass(), "mypage.jsp 환불상태 조회 오류: memberId=" + loginUser.getMemberId(), e);
    }

    /* 내 문의 내역 로드 */
    List<Object[]> myInquiries = new java.util.ArrayList<>();
    try {
        Connection conn = DBConn.getConnection();
        String sql = "SELECT inquiry_no, inquiry_title, inquiry_content, inquiry_answer, inquiry_status, reg_date, answer_date " +
                     "FROM inquiry WHERE member_id = ? ORDER BY inquiry_no DESC";
        try (PreparedStatement ps = conn.prepareStatement(sql)) {
            ps.setString(1, loginUser.getMemberId());
            try (ResultSet rs = ps.executeQuery()) {
                while (rs.next()) {
                    myInquiries.add(new Object[]{
                        rs.getInt("inquiry_no"), rs.getString("inquiry_title"), rs.getString("inquiry_content"),
                        rs.getString("inquiry_answer"), rs.getString("inquiry_status"),
                        rs.getTimestamp("reg_date"), rs.getTimestamp("answer_date")
                    });
                }
            }
        }
        /* 문의 탭을 열람하면 미확인 답변을 읽음 처리 */
        if ("inquiries".equals(tab)) {
            try (PreparedStatement ps = conn.prepareStatement(
                    "UPDATE inquiry SET is_read = 1 WHERE member_id = ? AND is_read = 0")) {
                ps.setString(1, loginUser.getMemberId());
                ps.executeUpdate();
            }
        }
    } catch (Exception e) {
        Logger.error(this.getClass(), "mypage.jsp 문의내역 조회 오류: memberId=" + loginUser.getMemberId(), e);
    }

    String CTX = request.getContextPath();

      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write('\n');

    String _ctx = request.getContextPath();
    String _uri = request.getRequestURI();
    String _cat = request.getParameter("category");
    if (_cat == null) _cat = "";
    boolean _onHome  = _uri.endsWith("/") || _uri.endsWith("index.jsp") || _uri.equals(_ctx + "/");
    boolean _onBoard = _uri.contains("/board/");
    boolean _onHat   = _uri.contains("/hat/");

    MemberDTO _hdrUser = (MemberDTO) session.getAttribute("loginUser");
    int _cartCount = 0;
    int _unreadInquiryCount = 0;
    if (_hdrUser != null) {
        try { _cartCount = new CartDAO().getCartCount(_hdrUser.getMemberId()); }
        catch (Exception _e) { /* 배지 카운트 실패 시 0으로 유지 */ }
        try {
            java.sql.Connection _conn = com.hatshop.db.DBConn.getConnection();
            try (java.sql.PreparedStatement _ps = _conn.prepareStatement(
                    "SELECT COUNT(*) FROM inquiry WHERE member_id = ? AND inquiry_status IN ('ANSWERED','CLOSED') AND is_read = 0")) {
                _ps.setString(1, _hdrUser.getMemberId());
                try (java.sql.ResultSet _rs = _ps.executeQuery()) {
                    if (_rs.next()) _unreadInquiryCount = _rs.getInt(1);
                }
            }
        } catch (Exception _e) { /* 알림 카운트 실패 시 0으로 유지 */ }
    }

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"ko\">\n");
      out.write("<head>\n");
      out.write("    <meta charset=\"UTF-8\">\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("    <title>HATSHOP — Wear Your Statement</title>\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.print( _ctx );
      out.write("/css/style.css?v=5\">\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.print( _ctx );
      out.write("/css/chatbot.css?v=5\">\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("<header class=\"site-header ");
      out.print( _onHome ? "" : "scrolled" );
      out.write("\" id=\"siteHeader\" data-home=\"");
      out.print( _onHome );
      out.write("\">\n");
      out.write("\n");
      out.write("    <a href=\"");
      out.print( _ctx );
      out.write("/\" class=\"brand\">HATSHOP</a>\n");
      out.write("\n");
      out.write("    <nav class=\"site-nav-primary\" id=\"primaryNav\">\n");
      out.write("        <a href=\"");
      out.print( _ctx );
      out.write("/\"\n");
      out.write("           class=\"");
      out.print( _onHome ? "active" : "" );
      out.write("\">Home</a>\n");
      out.write("        <a href=\"");
      out.print( _ctx );
      out.write("/hat/list?category=%EB%B3%BC%EC%BA%A1\"\n");
      out.write("           class=\"");
      out.print( "볼캡".equals(_cat) ? "active" : "" );
      out.write("\">볼캡</a>\n");
      out.write("        <a href=\"");
      out.print( _ctx );
      out.write("/hat/list?category=%EB%B2%84%ED%82%B7%ED%96%87\"\n");
      out.write("           class=\"");
      out.print( "버킷햇".equals(_cat) ? "active" : "" );
      out.write("\">버킷햇</a>\n");
      out.write("        <a href=\"");
      out.print( _ctx );
      out.write("/hat/list?category=%EB%B2%A0%EB%A0%88%EB%AA%A8\"\n");
      out.write("           class=\"");
      out.print( "베레모".equals(_cat) ? "active" : "" );
      out.write("\">베레모</a>\n");
      out.write("        <a href=\"");
      out.print( _ctx );
      out.write("/hat/list?category=%ED%8E%98%EB%8F%84%EB%9D%BC\"\n");
      out.write("           class=\"");
      out.print( "페도라".equals(_cat) ? "active" : "" );
      out.write("\">페도라</a>\n");
      out.write("        <a href=\"");
      out.print( _ctx );
      out.write("/hat/list?category=%EC%8A%A4%EB%83%85%EB%B0%B1\"\n");
      out.write("           class=\"");
      out.print( "스냅백".equals(_cat) ? "active" : "" );
      out.write("\">스냅백</a>\n");
      out.write("        <a href=\"");
      out.print( _ctx );
      out.write("/board/boardList.jsp\"\n");
      out.write("           class=\"");
      out.print( _onBoard ? "active" : "" );
      out.write("\">커뮤니티</a>\n");
      out.write("    </nav>\n");
      out.write("\n");
      out.write("    <div class=\"header-icons\">\n");
      out.write("        ");
      //  c:choose
      org.apache.taglibs.standard.tag.common.core.ChooseTag _jspx_th_c_005fchoose_005f0 = (org.apache.taglibs.standard.tag.common.core.ChooseTag) _005fjspx_005ftagPool_005fc_005fchoose.get(org.apache.taglibs.standard.tag.common.core.ChooseTag.class);
      try {
        _jspx_th_c_005fchoose_005f0.setPageContext(_jspx_page_context);
        _jspx_th_c_005fchoose_005f0.setParent(null);
        int _jspx_eval_c_005fchoose_005f0 = _jspx_th_c_005fchoose_005f0.doStartTag();
        if (_jspx_eval_c_005fchoose_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\n");
            out.write("            ");
            if (_jspx_meth_c_005fwhen_005f0(_jspx_th_c_005fchoose_005f0, _jspx_page_context))
              return;
            out.write("\n");
            out.write("            ");
            //  c:otherwise
            org.apache.taglibs.standard.tag.common.core.OtherwiseTag _jspx_th_c_005fotherwise_005f0 = (org.apache.taglibs.standard.tag.common.core.OtherwiseTag) _005fjspx_005ftagPool_005fc_005fotherwise.get(org.apache.taglibs.standard.tag.common.core.OtherwiseTag.class);
            try {
              _jspx_th_c_005fotherwise_005f0.setPageContext(_jspx_page_context);
              _jspx_th_c_005fotherwise_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
              int _jspx_eval_c_005fotherwise_005f0 = _jspx_th_c_005fotherwise_005f0.doStartTag();
              if (_jspx_eval_c_005fotherwise_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
                do {
                  out.write("\n");
                  out.write("                <a href=\"");
                  out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
                  out.write("/member/mypage.jsp?tab=inquiries\" style=\"position:relative\">마이페이지");

                    if (_unreadInquiryCount > 0) { 
                  out.write("<span class=\"cart-count\">");
                  out.print( _unreadInquiryCount );
                  out.write("</span>");
 } 
                  out.write("</a>\n");
                  out.write("                ");
                  if (_jspx_meth_c_005fif_005f0(_jspx_th_c_005fotherwise_005f0, _jspx_page_context))
                    return;
                  out.write("\n");
                  out.write("                <a href=\"");
                  out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
                  out.write("/member/logout.jsp\">로그아웃</a>\n");
                  out.write("            ");
                  int evalDoAfterBody = _jspx_th_c_005fotherwise_005f0.doAfterBody();
                  if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
                    break;
                } while (true);
              }
              if (_jspx_th_c_005fotherwise_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
                return;
              }
            } finally {
              _005fjspx_005ftagPool_005fc_005fotherwise.reuse(_jspx_th_c_005fotherwise_005f0);
            }
            out.write("\n");
            out.write("        ");
            int evalDoAfterBody = _jspx_th_c_005fchoose_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fchoose_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return;
        }
      } finally {
        _005fjspx_005ftagPool_005fc_005fchoose.reuse(_jspx_th_c_005fchoose_005f0);
      }
      out.write("\n");
      out.write("        <a href=\"");
      out.print( _ctx );
      out.write("/cart/list\" style=\"position:relative\">\n");
      out.write("            장바구니<span class=\"cart-count\" id=\"cartBadge\"");
      out.print( _cartCount > 0 ? "" : " style=\"display:none\"" );
      out.write('>');
      out.print( _cartCount > 0 ? _cartCount : 0 );
      out.write("</span>\n");
      out.write("        </a>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("</header>\n");
      out.write("\n");
      out.write("<script>\n");
      out.write("(function(){\n");
      out.write("    var h   = document.getElementById('siteHeader');\n");
      out.write("    var isHome = h && h.getAttribute('data-home') === 'true';\n");
      out.write("    function upd(){ h.classList.toggle('scrolled', !isHome || window.scrollY > 50); }\n");
      out.write("    window.addEventListener('scroll', upd, {passive:true});\n");
      out.write("    upd();\n");
      out.write("})();\n");
      out.write("function incrementCartBadge() {\n");
      out.write("    var b = document.getElementById('cartBadge');\n");
      out.write("    if (!b) return;\n");
      out.write("    var n = (parseInt(b.textContent) || 0) + 1;\n");
      out.write("    b.textContent = n;\n");
      out.write("    b.style.display = '';\n");
      out.write("}\n");
      out.write("</script>\n");
      out.write('\n');
      out.write('\n');
      out.write("\n");
      out.write("\n");
      out.write("<style>\n");
      out.write(".mypage-layout { display: grid; grid-template-columns: 240px 1fr; gap: 28px; align-items: start;\n");
      out.write("                 max-width: 1100px; margin: 0 auto; padding: calc(var(--header-h) + 40px) 24px 60px; }\n");
      out.write("\n");
      out.write("/* ── 프로필 카드 ── */\n");
      out.write(".profile-card { background: var(--bg); border: 1px solid var(--line);\n");
      out.write("                padding: 28px 20px; text-align: center; position: sticky; top: calc(var(--header-h) + 20px); }\n");
      out.write(".profile-avatar { width: 72px; height: 72px; border-radius: 50%; background: var(--ink);\n");
      out.write("                  display: flex; align-items: center; justify-content: center;\n");
      out.write("                  font-size: 1.8rem; color: #fff; margin: 0 auto 14px; font-weight: 700; }\n");
      out.write(".profile-name  { font-weight: 700; font-size: 1rem; margin-bottom: 4px; }\n");
      out.write(".profile-id    { font-size: .82rem; color: var(--ink-soft); margin-bottom: 8px; }\n");
      out.write(".profile-grade { display: inline-block; padding: 2px 10px;\n");
      out.write("                 font-size: .72rem; font-weight: 700; letter-spacing: .08em;\n");
      out.write("                 text-transform: uppercase; margin-bottom: 8px; border: 1px solid; }\n");
      out.write(".grade-normal  { background: var(--bg-sub); color: var(--ink-soft); border-color: var(--line); }\n");
      out.write(".grade-admin   { background: #fff5f5; color: var(--red); border-color: rgba(200,16,46,.3); }\n");
      out.write(".profile-date  { font-size: .78rem; color: var(--ink-soft); margin-bottom: 20px; }\n");
      out.write(".profile-sep   { border: none; border-top: 1px solid var(--line); margin: 16px 0; }\n");
      out.write(".profile-nav   { display: flex; flex-direction: column; gap: 4px; }\n");
      out.write(".profile-nav-btn {\n");
      out.write("    display: block; width: 100%; padding: 10px 14px; text-align: left;\n");
      out.write("    background: none; border: none; border-radius: 2px; cursor: pointer;\n");
      out.write("    font-size: .88rem; font-family: inherit; color: var(--ink-soft);\n");
      out.write("    transition: background .15s, color .15s; text-decoration: none;\n");
      out.write("}\n");
      out.write(".profile-nav-btn:hover { background: var(--bg-sub); color: var(--ink); }\n");
      out.write(".profile-nav-btn.active { background: var(--ink); color: #fff; font-weight: 600; }\n");
      out.write(".profile-nav-btn.logout-btn { color: var(--ink-soft); margin-top: 4px; }\n");
      out.write(".profile-nav-btn.logout-btn:hover { background: #fff5f5; color: var(--red); }\n");
      out.write("\n");
      out.write("/* ── 탭 패널 ── */\n");
      out.write(".tab-panel { display: none; }\n");
      out.write(".tab-panel.active { display: block; }\n");
      out.write("\n");
      out.write("/* ── 주문 내역 ── */\n");
      out.write(".section-heading { font-size: 1.1rem; font-weight: 800; letter-spacing: -.01em;\n");
      out.write("                   margin-bottom: 20px; display: flex; align-items: center; justify-content: space-between; }\n");
      out.write(".order-card { background: var(--bg); border: 1px solid var(--line); margin-bottom: 12px;\n");
      out.write("              transition: border-color .2s; }\n");
      out.write(".order-card:hover { border-color: var(--ink); }\n");
      out.write(".order-card-head { display: flex; align-items: center; justify-content: space-between;\n");
      out.write("                   padding: 12px 18px; border-bottom: 1px solid var(--line); background: var(--bg-sub); }\n");
      out.write(".order-no-txt { font-weight: 700; font-size: .92rem; }\n");
      out.write(".order-date-txt { font-size: .8rem; color: var(--ink-soft); margin-left: 10px; }\n");
      out.write(".order-card-body { display: flex; align-items: center; gap: 14px; padding: 14px 18px; }\n");
      out.write(".thumb-row { display: flex; }\n");
      out.write(".thumb-row img { width: 52px; height: 52px; object-fit: cover; border-radius: 2px;\n");
      out.write("                 border: 2px solid #fff; margin-left: -8px; background: var(--ph-a); }\n");
      out.write(".thumb-row img:first-child { margin-left: 0; }\n");
      out.write(".thumb-more-badge { width: 52px; height: 52px; background: var(--bg-sub);\n");
      out.write("                    border: 1px solid var(--line); display: inline-flex; align-items: center;\n");
      out.write("                    justify-content: center; font-size: .75rem; color: var(--ink-soft);\n");
      out.write("                    margin-left: -8px; flex-shrink: 0; }\n");
      out.write(".order-summary-block { flex: 1; }\n");
      out.write(".order-item-cnt { font-size: .85rem; color: var(--ink-soft); margin-bottom: 3px; }\n");
      out.write(".order-total-price { font-size: 1.05rem; font-weight: 800; }\n");
      out.write(".btn-order-detail { padding: 7px 18px; background: transparent; border: 1px solid var(--line);\n");
      out.write("                    color: var(--ink-soft); font-size: .82rem; text-decoration: none;\n");
      out.write("                    white-space: nowrap; transition: all .15s; }\n");
      out.write(".btn-order-detail:hover { border-color: var(--ink); color: var(--ink); }\n");
      out.write(".empty-orders { text-align: center; padding: 60px 20px; color: var(--ink-soft); border: 1px solid var(--line); }\n");
      out.write(".empty-orders .icon { font-size: 3rem; margin-bottom: 14px; opacity: .4; }\n");
      out.write(".empty-orders p { margin-bottom: 16px; font-size: .9rem; }\n");
      out.write("\n");
      out.write("/* 주문 상태 배지 */\n");
      out.write(".obadge { display: inline-block; padding: 2px 8px; font-size: .75rem; font-weight: 600; border: 1px solid; }\n");
      out.write(".status-pending  { background: #f5f5f5; color: #555; border-color: #ccc; }\n");
      out.write(".status-paid     { background: #eff8ff; color: #1a6fb3; border-color: #96cff5; }\n");
      out.write(".status-shipping { background: #fffbef; color: #8a6200; border-color: #e8c84a; }\n");
      out.write(".status-done     { background: #f0faf4; color: var(--green); border-color: #7dcf9e; }\n");
      out.write(".status-cancel   { background: #fff5f5; color: var(--red); border-color: #f5a0a0; }\n");
      out.write("\n");
      out.write("/* ── 계정 설정 ── */\n");
      out.write(".settings-section { border: 1px solid var(--line); margin-bottom: 20px; overflow: hidden; }\n");
      out.write(".settings-section-head { display: flex; align-items: center; gap: 12px; padding: 18px 24px;\n");
      out.write("                          border-bottom: 1px solid var(--line); background: var(--bg-sub); }\n");
      out.write(".settings-section-head .sec-icon { font-size: 1.1rem; }\n");
      out.write(".settings-section-head h3 { font-size: .95rem; font-weight: 700; }\n");
      out.write(".settings-section-head p  { font-size: .8rem; color: var(--ink-soft); margin-top: 2px; }\n");
      out.write(".settings-section-body { padding: 24px; }\n");
      out.write(".pw-strength { display: flex; gap: 4px; margin-top: 8px; }\n");
      out.write(".pw-strength span { height: 3px; flex: 1; background: var(--line); border-radius: 2px; transition: background .3s; }\n");
      out.write(".pw-strength.weak   span:nth-child(1) { background: var(--red); }\n");
      out.write(".pw-strength.fair   span:nth-child(1), .pw-strength.fair   span:nth-child(2) { background: #f5a623; }\n");
      out.write(".pw-strength.strong span:nth-child(1), .pw-strength.strong span:nth-child(2),\n");
      out.write(".pw-strength.strong span:nth-child(3) { background: var(--green); }\n");
      out.write(".pw-hint { font-size: .78rem; color: var(--ink-soft); margin-top: 6px; }\n");
      out.write(".danger-zone { border-color: rgba(200,16,46,.35) !important; }\n");
      out.write(".danger-zone .settings-section-head { background: #fff5f5; }\n");
      out.write(".danger-zone h3 { color: var(--red); }\n");
      out.write("\n");
      out.write("@media (max-width: 768px) {\n");
      out.write("    .mypage-layout { grid-template-columns: 1fr; padding-top: calc(var(--header-h) + 20px); }\n");
      out.write("    .profile-card { position: static; }\n");
      out.write("}\n");
      out.write("</style>\n");
      out.write("\n");
      out.write("<main>\n");
      out.write("<div class=\"mypage-layout\">\n");
      out.write("\n");
      out.write("  <!-- ── 프로필 사이드바 ── -->\n");
      out.write("  <aside class=\"profile-card\">\n");
      out.write("    <div class=\"profile-avatar\">\n");
      out.write("      ");
      out.print( HtmlUtils.escape(loginUser.getMemberName()).substring(0, 1) );
      out.write("\n");
      out.write("    </div>\n");
      out.write("    <p class=\"profile-name\">");
      out.print( HtmlUtils.escape(loginUser.getMemberName()) );
      out.write("</p>\n");
      out.write("    <p class=\"profile-id\">");
      out.print( HtmlUtils.escape(loginUser.getMemberId()) );
      out.write("</p>\n");
      out.write("    <span class=\"profile-grade ");
      out.print( loginUser.isAdmin() ? "grade-admin" : "grade-normal" );
      out.write("\">\n");
      out.write("      ");
      out.print( loginUser.isAdmin() ? "ADMIN" : "MEMBER" );
      out.write("\n");
      out.write("    </span>\n");
      out.write("    <p class=\"profile-date\">가입 ");
      out.print( HtmlUtils.escape(loginUser.getRegDate()) );
      out.write("</p>\n");
      out.write("    <hr class=\"profile-sep\">\n");
      out.write("    <nav class=\"profile-nav\">\n");
      out.write("      <button class=\"profile-nav-btn ");
      out.print( "orders".equals(tab) ? "active" : "" );
      out.write("\"\n");
      out.write("              onclick=\"switchTab('orders')\">주문 내역</button>\n");
      out.write("      <button class=\"profile-nav-btn ");
      out.print( "inquiries".equals(tab) ? "active" : "" );
      out.write("\"\n");
      out.write("              onclick=\"switchTab('inquiries')\">문의 내역</button>\n");
      out.write("      <button class=\"profile-nav-btn ");
      out.print( "account".equals(tab) ? "active" : "" );
      out.write("\"\n");
      out.write("              onclick=\"switchTab('account')\">계정 설정</button>\n");
      out.write("      <a href=\"");
      out.print( CTX );
      out.write("/member/logout.jsp\" class=\"profile-nav-btn logout-btn\">로그아웃</a>\n");
      out.write("    </nav>\n");
      out.write("  </aside>\n");
      out.write("\n");
      out.write("  <!-- ── 탭 패널 영역 ── -->\n");
      out.write("  <div>\n");
      out.write("\n");
      out.write("    ");
 if (flashSuccess != null) { 
      out.write("\n");
      out.write("    <div class=\"alert alert-success\" style=\"margin-bottom:20px\">");
      out.print( flashSuccess );
      out.write("</div>\n");
      out.write("    ");
 } 
      out.write("\n");
      out.write("    ");
 if (flashError != null) { 
      out.write("\n");
      out.write("    <div class=\"alert alert-error\" style=\"margin-bottom:20px\">");
      out.print( flashError );
      out.write("</div>\n");
      out.write("    ");
 } 
      out.write("\n");
      out.write("\n");
      out.write("    <!-- ═══ 주문 내역 탭 ═══ -->\n");
      out.write("    <div id=\"panel-orders\" class=\"tab-panel\">\n");
      out.write("      <div class=\"section-heading\">\n");
      out.write("        <span>주문 내역</span>\n");
      out.write("        ");
 if (orderList != null && !orderList.isEmpty()) { 
      out.write("\n");
      out.write("        <span style=\"font-size:.82rem;color:var(--ink-soft);font-weight:400\">총 ");
      out.print( orderList.size() );
      out.write("건</span>\n");
      out.write("        ");
 } 
      out.write("\n");
      out.write("      </div>\n");
      out.write("\n");
      out.write("      ");
 if (orderList == null || orderList.isEmpty()) { 
      out.write("\n");
      out.write("      <div class=\"empty-orders\">\n");
      out.write("        <div class=\"icon\"><svg class=\"icon-svg\" style=\"width:2.4em;height:2.4em\" viewBox=\"0 0 24 24\"><path d=\"M16.5 9.4 7.55 4.24\"/><path d=\"M21 16V8a2 2 0 0 0-1-1.73l-7-4a2 2 0 0 0-2 0l-7 4A2 2 0 0 0 3 8v8a2 2 0 0 0 1 1.73l7 4a2 2 0 0 0 2 0l7-4A2 2 0 0 0 21 16z\"/><polyline points=\"3.29 7 12 12 20.71 7\"/><line x1=\"12\" y1=\"22\" x2=\"12\" y2=\"12\"/></svg></div>\n");
      out.write("        <p>아직 주문 내역이 없습니다.</p>\n");
      out.write("        <a href=\"");
      out.print( CTX );
      out.write("/hat/list\" style=\"display:inline-block;padding:8px 24px;background:var(--ink);color:#fff;font-size:.85rem;font-weight:700;text-decoration:none;\">모자 쇼핑하러 가기</a>\n");
      out.write("      </div>\n");
      out.write("      ");
 } else {
           for (OrderDTO order : orderList) {
             List<OrderDetailDTO> details = order.getDetails();
             String refundStatus = refundStatusMap.get(order.getOrderNo());
             String refundBadgeText = null;
             if ("REQUESTED".equals(refundStatus)) refundBadgeText = "환불 신청 중";
             else if ("APPROVED".equals(refundStatus)) refundBadgeText = "환불 승인됨";
             else if ("COMPLETED".equals(refundStatus)) refundBadgeText = "환불 완료";
      
      out.write("\n");
      out.write("      <div class=\"order-card\">\n");
      out.write("        <div class=\"order-card-head\">\n");
      out.write("          <div>\n");
      out.write("            <span class=\"order-no-txt\">주문 #");
      out.print( order.getOrderNo() );
      out.write("</span>\n");
      out.write("            <span class=\"order-date-txt\">");
      out.print( order.getOrderDate() != null ? order.getOrderDate().substring(0, Math.min(16, order.getOrderDate().length())) : "" );
      out.write("</span>\n");
      out.write("          </div>\n");
      out.write("          <span style=\"display:flex;gap:6px;align-items:center\">\n");
      out.write("            ");
 if (refundBadgeText != null) { 
      out.write("\n");
      out.write("            <span class=\"obadge status-pending\">");
      out.print( refundBadgeText );
      out.write("</span>\n");
      out.write("            ");
 } 
      out.write("\n");
      out.write("            <span class=\"obadge ");
      out.print( order.getStatusClass() );
      out.write('"');
      out.write('>');
      out.print( order.getStatusLabel() );
      out.write("</span>\n");
      out.write("          </span>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"order-card-body\">\n");
      out.write("          <div class=\"thumb-row\">\n");
      out.write("            ");
 if (details != null && !details.isEmpty()) {
                 int showCnt = Math.min(details.size(), 3);
                 for (int i = 0; i < showCnt; i++) {
                   OrderDetailDTO d = details.get(i);
                   String rawImg = d.getHatImage();
                   String imgSrc = (rawImg != null && !rawImg.trim().isEmpty())
                       ? CTX + "/image?src=" + URLEncoder.encode(rawImg, "UTF-8")
                       : CTX + "/images/no-image.png";
            
      out.write("\n");
      out.write("            <img src=\"");
      out.print( imgSrc );
      out.write("\" alt=\"");
      out.print( HtmlUtils.escape(d.getHatName() != null ? d.getHatName() : "") );
      out.write("\"\n");
      out.write("                 onerror=\"this.onerror=null;this.src='");
      out.print( CTX );
      out.write("/images/no-image.png'\">\n");
      out.write("            ");
 }
               if (details.size() > 3) { 
      out.write("\n");
      out.write("            <span class=\"thumb-more-badge\">+");
      out.print( details.size()-3 );
      out.write("</span>\n");
      out.write("            ");
 }
              }
            
      out.write("\n");
      out.write("          </div>\n");
      out.write("          <div class=\"order-summary-block\">\n");
      out.write("            <div class=\"order-item-cnt\">상품 ");
      out.print( order.getItemCount() );
      out.write("건</div>\n");
      out.write("            <div class=\"order-total-price\">");
      out.print( order.getFormattedTotal() );
      out.write("원</div>\n");
      out.write("          </div>\n");
      out.write("          <div style=\"display:flex;gap:8px\">\n");
      out.write("            ");
 boolean refundEligible = refundBadgeText == null &&
                   ("PAID".equals(order.getOrderStatus()) || "SHIPPING".equals(order.getOrderStatus()) || "DONE".equals(order.getOrderStatus()));
               if (refundEligible) { 
      out.write("\n");
      out.write("            <a href=\"");
      out.print( CTX );
      out.write("/refund/request.jsp?orderNo=");
      out.print( order.getOrderNo() );
      out.write("\" class=\"btn-order-detail\">환불 신청</a>\n");
      out.write("            ");
 } 
      out.write("\n");
      out.write("            <a href=\"");
      out.print( CTX );
      out.write("/order/detail?orderNo=");
      out.print( order.getOrderNo() );
      out.write("\" class=\"btn-order-detail\">상세보기</a>\n");
      out.write("          </div>\n");
      out.write("        </div>\n");
      out.write("      </div>\n");
      out.write("      ");
 } } 
      out.write("\n");
      out.write("    </div><!-- /panel-orders -->\n");
      out.write("\n");
      out.write("    <!-- ═══ 문의 내역 탭 ═══ -->\n");
      out.write("    <div id=\"panel-inquiries\" class=\"tab-panel\">\n");
      out.write("      <div class=\"section-heading\">\n");
      out.write("        <span>문의 내역</span>\n");
      out.write("        ");
 if (!myInquiries.isEmpty()) { 
      out.write("\n");
      out.write("        <span style=\"font-size:.82rem;color:var(--ink-soft);font-weight:400\">총 ");
      out.print( myInquiries.size() );
      out.write("건</span>\n");
      out.write("        ");
 } 
      out.write("\n");
      out.write("      </div>\n");
      out.write("\n");
      out.write("      ");
 if (myInquiries.isEmpty()) { 
      out.write("\n");
      out.write("      <div class=\"empty-orders\">\n");
      out.write("        <div class=\"icon\"><svg class=\"icon-svg\" style=\"width:1em;height:1em\" viewBox=\"0 0 24 24\"><path d=\"M3 18v-6a9 9 0 0 1 18 0v6\"/><path d=\"M21 19a2 2 0 0 1-2 2h-1a2 2 0 0 1-2-2v-3a2 2 0 0 1 2-2h3zM3 19a2 2 0 0 0 2 2h1a2 2 0 0 0 2-2v-3a2 2 0 0 0-2-2H3z\"/></svg></div>\n");
      out.write("        <p>아직 문의한 내역이 없습니다.</p>\n");
      out.write("      </div>\n");
      out.write("      ");
 } else {
           for (Object[] iq : myInquiries) {
             int iqNo = (Integer) iq[0];
             String iqTitle = (String) iq[1];
             String iqContent = (String) iq[2];
             String iqAnswer = (String) iq[3];
             String iqStatus = (String) iq[4];
             java.sql.Timestamp iqReg = (java.sql.Timestamp) iq[5];
             java.sql.Timestamp iqAnsDate = (java.sql.Timestamp) iq[6];
             String iqBadgeClass, iqBadgeLabel;
             switch (iqStatus) {
                 case "ANSWERED": iqBadgeClass = "status-done";    iqBadgeLabel = "답변완료"; break;
                 case "CLOSED":   iqBadgeClass = "status-cancel";  iqBadgeLabel = "종료"; break;
                 default:         iqBadgeClass = "status-pending"; iqBadgeLabel = "답변대기"; break;
             }
      
      out.write("\n");
      out.write("      <div class=\"order-card\">\n");
      out.write("        <div class=\"order-card-head\">\n");
      out.write("          <div>\n");
      out.write("            <span class=\"order-no-txt\">");
      out.print( HtmlUtils.escape(iqTitle) );
      out.write("</span>\n");
      out.write("            <span class=\"order-date-txt\">");
      out.print( iqReg != null ? iqReg.toString().substring(0,16) : "" );
      out.write("</span>\n");
      out.write("          </div>\n");
      out.write("          <span class=\"obadge ");
      out.print( iqBadgeClass );
      out.write('"');
      out.write('>');
      out.print( iqBadgeLabel );
      out.write("</span>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"order-card-body\" style=\"flex-direction:column;align-items:stretch;gap:10px\">\n");
      out.write("          <div style=\"font-size:.88rem;color:var(--ink-soft);white-space:pre-wrap;word-break:break-word\">");
      out.print( HtmlUtils.escape(iqContent) );
      out.write("</div>\n");
      out.write("          ");
 if (iqAnswer != null) { 
      out.write("\n");
      out.write("          <div style=\"background:var(--bg-sub);border-radius:4px;padding:12px 14px;font-size:.86rem;white-space:pre-wrap;word-break:break-word\">\n");
      out.write("            <div style=\"font-weight:700;margin-bottom:4px;font-size:.78rem;color:var(--ink-soft)\">관리자 답변 ");
      out.print( iqAnsDate != null ? "· " + iqAnsDate.toString().substring(0,16) : "" );
      out.write("</div>\n");
      out.write("            ");
      out.print( HtmlUtils.escape(iqAnswer) );
      out.write("\n");
      out.write("          </div>\n");
      out.write("          ");
 } 
      out.write("\n");
      out.write("        </div>\n");
      out.write("      </div>\n");
      out.write("      ");
 } } 
      out.write("\n");
      out.write("    </div><!-- /panel-inquiries -->\n");
      out.write("\n");
      out.write("    <!-- ═══ 계정 설정 탭 ═══ -->\n");
      out.write("    <div id=\"panel-account\" class=\"tab-panel\">\n");
      out.write("      <div class=\"section-heading\">계정 설정</div>\n");
      out.write("\n");
      out.write("      <!-- 회원정보 수정 -->\n");
      out.write("      <div class=\"settings-section\">\n");
      out.write("        <div class=\"settings-section-head\">\n");
      out.write("          <span class=\"sec-icon\"><svg class=\"icon-svg\" viewBox=\"0 0 24 24\"><path d=\"M20 21v-2a4 4 0 0 0-4-4H8a4 4 0 0 0-4 4v2\"/><circle cx=\"12\" cy=\"7\" r=\"4\"/></svg></span>\n");
      out.write("          <div>\n");
      out.write("            <h3>기본 정보</h3>\n");
      out.write("            <p>이름, 이메일, 전화번호, 주소를 수정합니다</p>\n");
      out.write("          </div>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"settings-section-body\">\n");
      out.write("          <form action=\"");
      out.print( CTX );
      out.write("/member/updateProc.jsp\" method=\"post\">\n");
      out.write("            <input type=\"hidden\" name=\"type\" value=\"info\">\n");
      out.write("            <div class=\"form-group\">\n");
      out.write("              <label>아이디</label>\n");
      out.write("              <input type=\"text\" class=\"form-control\"\n");
      out.write("                     value=\"");
      out.print( HtmlUtils.escape(loginUser.getMemberId()) );
      out.write("\" disabled\n");
      out.write("                     style=\"opacity:.4;cursor:not-allowed\">\n");
      out.write("            </div>\n");
      out.write("            <div class=\"form-group\">\n");
      out.write("              <label for=\"memberName\">이름 <span style=\"color:var(--red)\">*</span></label>\n");
      out.write("              <input type=\"text\" id=\"memberName\" name=\"memberName\" class=\"form-control\"\n");
      out.write("                     value=\"");
      out.print( HtmlUtils.escape(loginUser.getMemberName()) );
      out.write("\" maxlength=\"30\">\n");
      out.write("            </div>\n");
      out.write("            <div class=\"form-group\">\n");
      out.write("              <label for=\"email\">이메일 <span style=\"color:var(--red)\">*</span></label>\n");
      out.write("              <input type=\"email\" id=\"email\" name=\"email\" class=\"form-control\"\n");
      out.write("                     value=\"");
      out.print( HtmlUtils.escape(loginUser.getEmail()) );
      out.write("\" maxlength=\"100\">\n");
      out.write("            </div>\n");
      out.write("            <div class=\"form-group\">\n");
      out.write("              <label for=\"phone\">전화번호</label>\n");
      out.write("              <input type=\"tel\" id=\"phone\" name=\"phone\" class=\"form-control\"\n");
      out.write("                     value=\"");
      out.print( HtmlUtils.escape(loginUser.getPhone() == null ? "" : loginUser.getPhone()) );
      out.write("\"\n");
      out.write("                     maxlength=\"20\">\n");
      out.write("            </div>\n");
      out.write("            <div class=\"form-group\">\n");
      out.write("              <label for=\"addr\">주소</label>\n");
      out.write("              <input type=\"text\" id=\"addr\" name=\"addr\" class=\"form-control\"\n");
      out.write("                     value=\"");
      out.print( HtmlUtils.escape(loginUser.getAddr() == null ? "" : loginUser.getAddr()) );
      out.write("\"\n");
      out.write("                     maxlength=\"200\">\n");
      out.write("            </div>\n");
      out.write("            <button type=\"submit\" class=\"btn btn-primary btn-sm\"\n");
      out.write("                    onclick=\"return validateInfoForm(this.form)\">저장</button>\n");
      out.write("          </form>\n");
      out.write("        </div>\n");
      out.write("      </div>\n");
      out.write("\n");
      out.write("      <!-- 비밀번호 변경 -->\n");
      out.write("      <div class=\"settings-section\">\n");
      out.write("        <div class=\"settings-section-head\">\n");
      out.write("          <span class=\"sec-icon\"><svg class=\"icon-svg\" viewBox=\"0 0 24 24\"><rect x=\"3\" y=\"11\" width=\"18\" height=\"11\" rx=\"2\" ry=\"2\"/><path d=\"M7 11V7a5 5 0 0 1 10 0v4\"/></svg></span>\n");
      out.write("          <div>\n");
      out.write("            <h3>비밀번호 변경</h3>\n");
      out.write("            <p>정기적인 비밀번호 변경으로 계정을 안전하게 보호하세요</p>\n");
      out.write("          </div>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"settings-section-body\">\n");
      out.write("          <form action=\"");
      out.print( CTX );
      out.write("/member/updateProc.jsp\" method=\"post\"\n");
      out.write("                onsubmit=\"return validatePwForm(this)\">\n");
      out.write("            <input type=\"hidden\" name=\"type\" value=\"pw\">\n");
      out.write("            <div class=\"form-group\">\n");
      out.write("              <label for=\"curPw\">현재 비밀번호 <span style=\"color:var(--red)\">*</span></label>\n");
      out.write("              <input type=\"password\" id=\"curPw\" name=\"curPw\" class=\"form-control\"\n");
      out.write("                     placeholder=\"현재 비밀번호 입력\" autocomplete=\"current-password\">\n");
      out.write("            </div>\n");
      out.write("            <div class=\"form-group\">\n");
      out.write("              <label for=\"newPw\">새 비밀번호 <span style=\"color:var(--red)\">*</span></label>\n");
      out.write("              <input type=\"password\" id=\"newPw\" name=\"newPw\" class=\"form-control\"\n");
      out.write("                     placeholder=\"영문·숫자 조합 8자 이상\" autocomplete=\"new-password\"\n");
      out.write("                     oninput=\"checkPwStrength(this.value)\">\n");
      out.write("              <div class=\"pw-strength\" id=\"pwStrength\">\n");
      out.write("                <span></span><span></span><span></span>\n");
      out.write("              </div>\n");
      out.write("              <div class=\"pw-hint\" id=\"pwHint\">8자 이상 입력해주세요</div>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"form-group\">\n");
      out.write("              <label for=\"newPw2\">새 비밀번호 확인 <span style=\"color:var(--red)\">*</span></label>\n");
      out.write("              <input type=\"password\" id=\"newPw2\" name=\"newPw2\" class=\"form-control\"\n");
      out.write("                     placeholder=\"새 비밀번호 재입력\" autocomplete=\"new-password\">\n");
      out.write("            </div>\n");
      out.write("            <button type=\"submit\" class=\"btn btn-primary btn-sm\">비밀번호 변경</button>\n");
      out.write("          </form>\n");
      out.write("        </div>\n");
      out.write("      </div>\n");
      out.write("\n");
      out.write("      <!-- 회원 탈퇴 -->\n");
      out.write("      <div class=\"settings-section danger-zone\">\n");
      out.write("        <div class=\"settings-section-head\">\n");
      out.write("          <span class=\"sec-icon\"><svg class=\"icon-svg\" viewBox=\"0 0 24 24\"><path d=\"M10.29 3.86L1.82 18a2 2 0 0 0 1.71 3h16.94a2 2 0 0 0 1.71-3L13.71 3.86a2 2 0 0 0-3.42 0z\"/><line x1=\"12\" y1=\"9\" x2=\"12\" y2=\"13\"/><line x1=\"12\" y1=\"17\" x2=\"12.01\" y2=\"17\"/></svg></span>\n");
      out.write("          <div>\n");
      out.write("            <h3>회원 탈퇴</h3>\n");
      out.write("            <p>탈퇴 후 모든 데이터는 삭제되며 복구할 수 없습니다</p>\n");
      out.write("          </div>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"settings-section-body\">\n");
      out.write("          <div class=\"alert alert-error\" style=\"margin-bottom:20px;font-size:.85rem\">\n");
      out.write("            탈퇴 시 장바구니, 주문 내역 등 모든 데이터가 즉시 삭제됩니다.\n");
      out.write("          </div>\n");
      out.write("          <form action=\"");
      out.print( CTX );
      out.write("/member/deleteProc.jsp\" method=\"post\"\n");
      out.write("                onsubmit=\"return confirmDelete()\">\n");
      out.write("            <div class=\"form-group\">\n");
      out.write("              <label for=\"delPw\">비밀번호 확인 <span style=\"color:var(--red)\">*</span></label>\n");
      out.write("              <input type=\"password\" id=\"delPw\" name=\"memberPw\" class=\"form-control\"\n");
      out.write("                     placeholder=\"비밀번호를 입력하여 탈퇴를 확인하세요\">\n");
      out.write("            </div>\n");
      out.write("            <button type=\"submit\" class=\"btn btn-danger btn-sm\">회원 탈퇴</button>\n");
      out.write("          </form>\n");
      out.write("        </div>\n");
      out.write("      </div>\n");
      out.write("\n");
      out.write("    </div><!-- /panel-account -->\n");
      out.write("\n");
      out.write("  </div><!-- /tab panels -->\n");
      out.write("</div><!-- /mypage-layout -->\n");
      out.write("</main>\n");
      out.write("\n");
      out.write("<script>\n");
      out.write("const INIT_TAB = '");
      out.print( tab );
      out.write("';\n");
      out.write("\n");
      out.write("function switchTab(name) {\n");
      out.write("    ['orders','inquiries','account'].forEach(t => {\n");
      out.write("        document.getElementById('panel-' + t).classList.toggle('active', t === name);\n");
      out.write("    });\n");
      out.write("    document.querySelectorAll('.profile-nav-btn[onclick]').forEach(btn => {\n");
      out.write("        btn.classList.toggle('active', btn.getAttribute('onclick') === \"switchTab('\" + name + \"')\");\n");
      out.write("    });\n");
      out.write("}\n");
      out.write("\n");
      out.write("function validateInfoForm(form) {\n");
      out.write("    if (!form.memberName.value.trim()) {\n");
      out.write("        alert('이름을 입력하세요.'); form.memberName.focus(); return false;\n");
      out.write("    }\n");
      out.write("    if (!/^[^\\s@]+@[^\\s@]+\\.[^\\s@]+$/.test(form.email.value.trim())) {\n");
      out.write("        alert('이메일 형식이 올바르지 않습니다.'); form.email.focus(); return false;\n");
      out.write("    }\n");
      out.write("    return true;\n");
      out.write("}\n");
      out.write("\n");
      out.write("function validatePwForm(form) {\n");
      out.write("    if (!form.curPw.value) {\n");
      out.write("        alert('현재 비밀번호를 입력하세요.'); form.curPw.focus(); return false;\n");
      out.write("    }\n");
      out.write("    if (form.newPw.value.length < 8) {\n");
      out.write("        alert('새 비밀번호는 8자 이상 입력하세요.'); form.newPw.focus(); return false;\n");
      out.write("    }\n");
      out.write("    if (form.newPw.value !== form.newPw2.value) {\n");
      out.write("        alert('새 비밀번호가 일치하지 않습니다.'); form.newPw2.focus(); return false;\n");
      out.write("    }\n");
      out.write("    return true;\n");
      out.write("}\n");
      out.write("\n");
      out.write("function checkPwStrength(val) {\n");
      out.write("    var el = document.getElementById('pwStrength');\n");
      out.write("    var hint = document.getElementById('pwHint');\n");
      out.write("    if (!el) return;\n");
      out.write("    el.className = 'pw-strength';\n");
      out.write("    if (val.length === 0) { hint.textContent = '8자 이상 입력해주세요'; return; }\n");
      out.write("    var score = 0;\n");
      out.write("    if (val.length >= 8) score++;\n");
      out.write("    if (/[A-Za-z]/.test(val) && /[0-9]/.test(val)) score++;\n");
      out.write("    if (/[^A-Za-z0-9]/.test(val)) score++;\n");
      out.write("    var levels = ['', 'weak', 'fair', 'strong'];\n");
      out.write("    var msgs = ['', '보안 수준: 낮음', '보안 수준: 보통', '보안 수준: 높음'];\n");
      out.write("    el.className = 'pw-strength ' + (levels[score] || '');\n");
      out.write("    hint.textContent = msgs[score] || '';\n");
      out.write("}\n");
      out.write("\n");
      out.write("function confirmDelete() {\n");
      out.write("    var pw = document.getElementById('delPw').value;\n");
      out.write("    if (!pw) { alert('비밀번호를 입력하세요.'); return false; }\n");
      out.write("    return confirm('정말 탈퇴하시겠습니까?\\n이 작업은 되돌릴 수 없습니다.');\n");
      out.write("}\n");
      out.write("\n");
      out.write("switchTab(INIT_TAB);\n");
      out.write("</script>\n");
      out.write("\n");
      out.write("\n");
      out.write("<footer class=\"site-footer\">\n");
      out.write("\n");
      out.write("    <div class=\"footer__top\">\n");
      out.write("        <div class=\"footer__brand\">\n");
      out.write("            <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/\" class=\"logo\">HATSHOP</a>\n");
      out.write("            <p>모자 그 이상의 태도. 절제된 디자인으로<br>매일의 룩을 완성하는 헤드웨어.</p>\n");
      out.write("            <form class=\"footer__news\" onsubmit=\"return false;\">\n");
      out.write("                <input type=\"email\" placeholder=\"이메일로 신상품 소식 받기\" aria-label=\"이메일\">\n");
      out.write("                <button type=\"submit\">→</button>\n");
      out.write("            </form>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        <div class=\"footer__col\">\n");
      out.write("            <h4>쇼핑</h4>\n");
      out.write("            <ul>\n");
      out.write("                <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/hat/list?category=%EB%B3%BC%EC%BA%A1\">볼캡</a></li>\n");
      out.write("                <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/hat/list?category=%EB%B2%84%ED%82%B7%ED%96%87\">버킷햇</a></li>\n");
      out.write("                <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/hat/list?category=%EB%B2%A0%EB%A0%88%EB%AA%A8\">베레모</a></li>\n");
      out.write("                <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/hat/list?category=%ED%8E%98%EB%8F%84%EB%9D%BC\">페도라</a></li>\n");
      out.write("                <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/hat/list?category=%EC%8A%A4%EB%83%85%EB%B0%B1\">스냅백</a></li>\n");
      out.write("                <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/hat/list\">전체 목록</a></li>\n");
      out.write("            </ul>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        <div class=\"footer__col\">\n");
      out.write("            <h4>회원</h4>\n");
      out.write("            <ul>\n");
      out.write("                <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/member/login.jsp\">로그인</a></li>\n");
      out.write("                <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/member/join.jsp\">회원가입</a></li>\n");
      out.write("                <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/member/mypage.jsp\">마이페이지</a></li>\n");
      out.write("                <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/cart/cartList.jsp\">장바구니</a></li>\n");
      out.write("                <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/order/orderList.jsp\">주문내역</a></li>\n");
      out.write("            </ul>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        <div class=\"footer__col\">\n");
      out.write("            <h4>고객센터</h4>\n");
      out.write("            <ul>\n");
      out.write("                <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/info/delivery.jsp\">배송 안내</a></li>\n");
      out.write("                <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/info/returns.jsp\">교환 / 반품</a></li>\n");
      out.write("                <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/info/size-guide.jsp\">사이즈 가이드</a></li>\n");
      out.write("                <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/board/boardList.jsp\">커뮤니티</a></li>\n");
      out.write("            </ul>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <div class=\"footer__bottom\">\n");
      out.write("        <small>© 2026 HATSHOP. All rights reserved.</small>\n");
      out.write("        <div class=\"legal\">\n");
      out.write("            <a href=\"#\">이용약관</a>\n");
      out.write("            <a href=\"#\">개인정보처리방침</a>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("</footer>\n");
      out.write("\n");
      out.write("<!-- ── AI 고객 상담 챗봇 위젯 ── -->\n");
      out.write("<div id=\"hsChatbot\" class=\"hs-chatbot\">\n");
      out.write("  <button id=\"hsChatToggle\" type=\"button\" class=\"hs-chat-toggle\" aria-label=\"고객 상담 챗봇 열기\">💬</button>\n");
      out.write("  <div id=\"hsChatPanel\" class=\"hs-chat-panel\" hidden>\n");
      out.write("    <div class=\"hs-chat-header\">\n");
      out.write("      <span>HATSHOP 고객 상담</span>\n");
      out.write("      <button id=\"hsChatClose\" type=\"button\" class=\"hs-chat-close\" aria-label=\"닫기\">✕</button>\n");
      out.write("    </div>\n");
      out.write("    <div id=\"hsChatBody\" class=\"hs-chat-body\"></div>\n");
      out.write("    <div id=\"hsChatQuick\" class=\"hs-chat-quick\"></div>\n");
      out.write("    <div class=\"ac-wrap\" style=\"margin:0 12px\">\n");
      out.write("      <div id=\"hsAcDropdown\" class=\"ac-dropdown\"></div>\n");
      out.write("    </div>\n");
      out.write("    <form id=\"hsChatForm\" class=\"hs-chat-form\">\n");
      out.write("      <input type=\"text\" id=\"hsChatInput\" placeholder=\"질문을 입력하세요...\" autocomplete=\"off\">\n");
      out.write("      <button type=\"submit\">전송</button>\n");
      out.write("    </form>\n");
      out.write("  </div>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/js/validation.js\"></script>\n");
      out.write("<script>window.HS_CTX = '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("';</script>\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/js/chatbot.js\"></script>\n");
      out.write("</body>\n");
      out.write("</html>\n");
      out.write('\n');
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fwhen_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:when
    org.apache.taglibs.standard.tag.rt.core.WhenTag _jspx_th_c_005fwhen_005f0 = (org.apache.taglibs.standard.tag.rt.core.WhenTag) _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.WhenTag.class);
    try {
      _jspx_th_c_005fwhen_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fwhen_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
      // /WEB-INF/inc/header.jsp(65,12) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fwhen_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${empty sessionScope.loginUser}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fwhen_005f0 = _jspx_th_c_005fwhen_005f0.doStartTag();
      if (_jspx_eval_c_005fwhen_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("                <a href=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/member/login.jsp\">로그인</a>\n");
          out.write("                <a href=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/member/join.jsp\">회원가입</a>\n");
          out.write("            ");
          int evalDoAfterBody = _jspx_th_c_005fwhen_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fwhen_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } finally {
      _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f0);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fotherwise_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fotherwise_005f0);
      // /WEB-INF/inc/header.jsp(72,16) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.loginUser.grade eq 'ADMIN'}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("                    <a href=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/admin/\">관리자</a>\n");
          out.write("                ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } finally {
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
    }
    return false;
  }
}
