/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.118
 * Generated at: 2026-06-19 01:20:46 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.hatshop.member.MemberDTO;
import com.hatshop.cart.CartDTO;
import com.hatshop.util.HtmlUtils;
import java.util.List;
import com.hatshop.cart.CartDAO;
import com.hatshop.member.MemberDTO;

public final class cartList_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {


private String formatPrice(int price) {
    return java.text.NumberFormat.getNumberInstance(java.util.Locale.KOREA).format(price);
}

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.LinkedHashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("/WEB-INF/inc/header.jsp", Long.valueOf(1781831986439L));
    _jspx_dependants.put("/WEB-INF/inc/footer.jsp", Long.valueOf(1781756931479L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1781088682000L));
    _jspx_dependants.put("jar:file:/C:/Users/gram14/OneDrive/바탕%20화면/Projact/jsp/hatshop-server/tomcat/webapps/hatshop/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(7);
    _jspx_imports_classes.add("com.hatshop.member.MemberDTO");
    _jspx_imports_classes.add("com.hatshop.cart.CartDTO");
    _jspx_imports_classes.add("com.hatshop.util.HtmlUtils");
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("com.hatshop.cart.CartDAO");
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fchoose;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fotherwise;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fchoose = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fotherwise = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fchoose.release();
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fotherwise.release();
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');
      out.write('\n');

    MemberDTO loginUser = (MemberDTO) session.getAttribute("loginUser");
    if (loginUser == null) {
        response.sendRedirect(request.getContextPath() + "/member/login.jsp"); return;
    }

    String ctx  = request.getContextPath();
    List<CartDTO> cartList   = (List<CartDTO>) request.getAttribute("cartList");
    int           totalPrice = (Integer)       request.getAttribute("totalPrice");
    boolean       isEmpty    = cartList == null || cartList.isEmpty();

    String flashSuccess = (String) session.getAttribute("flashSuccess");
    session.removeAttribute("flashSuccess");

      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write('\n');

    String _ctx = request.getContextPath();
    String _uri = request.getRequestURI();
    String _cat = request.getParameter("category");
    if (_cat == null) _cat = "";
    boolean _onHome  = _uri.endsWith("/") || _uri.endsWith("index.jsp") || _uri.equals(_ctx + "/");
    boolean _onBoard = _uri.contains("/board/");
    boolean _onHat   = _uri.contains("/hat/");

    MemberDTO _hdrUser = (MemberDTO) session.getAttribute("loginUser");
    int _cartCount = 0;
    int _unreadInquiryCount = 0;
    if (_hdrUser != null) {
        try { _cartCount = new CartDAO().getCartCount(_hdrUser.getMemberId()); }
        catch (Exception _e) { /* 배지 카운트 실패 시 0으로 유지 */ }
        try {
            java.sql.Connection _conn = com.hatshop.db.DBConn.getConnection();
            try (java.sql.PreparedStatement _ps = _conn.prepareStatement(
                    "SELECT COUNT(*) FROM inquiry WHERE member_id = ? AND inquiry_status IN ('ANSWERED','CLOSED') AND is_read = 0")) {
                _ps.setString(1, _hdrUser.getMemberId());
                try (java.sql.ResultSet _rs = _ps.executeQuery()) {
                    if (_rs.next()) _unreadInquiryCount = _rs.getInt(1);
                }
            }
        } catch (Exception _e) { /* 알림 카운트 실패 시 0으로 유지 */ }
    }

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"ko\">\n");
      out.write("<head>\n");
      out.write("    <meta charset=\"UTF-8\">\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("    <title>HATSHOP — Wear Your Statement</title>\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.print( _ctx );
      out.write("/css/style.css?v=5\">\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.print( _ctx );
      out.write("/css/chatbot.css?v=5\">\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("<header class=\"site-header ");
      out.print( _onHome ? "" : "scrolled" );
      out.write("\" id=\"siteHeader\" data-home=\"");
      out.print( _onHome );
      out.write("\">\n");
      out.write("\n");
      out.write("    <a href=\"");
      out.print( _ctx );
      out.write("/\" class=\"brand\">HATSHOP</a>\n");
      out.write("\n");
      out.write("    <nav class=\"site-nav-primary\" id=\"primaryNav\">\n");
      out.write("        <a href=\"");
      out.print( _ctx );
      out.write("/\"\n");
      out.write("           class=\"");
      out.print( _onHome ? "active" : "" );
      out.write("\">Home</a>\n");
      out.write("        <a href=\"");
      out.print( _ctx );
      out.write("/hat/list?category=%EB%B3%BC%EC%BA%A1\"\n");
      out.write("           class=\"");
      out.print( "볼캡".equals(_cat) ? "active" : "" );
      out.write("\">볼캡</a>\n");
      out.write("        <a href=\"");
      out.print( _ctx );
      out.write("/hat/list?category=%EB%B2%84%ED%82%B7%ED%96%87\"\n");
      out.write("           class=\"");
      out.print( "버킷햇".equals(_cat) ? "active" : "" );
      out.write("\">버킷햇</a>\n");
      out.write("        <a href=\"");
      out.print( _ctx );
      out.write("/hat/list?category=%EB%B2%A0%EB%A0%88%EB%AA%A8\"\n");
      out.write("           class=\"");
      out.print( "베레모".equals(_cat) ? "active" : "" );
      out.write("\">베레모</a>\n");
      out.write("        <a href=\"");
      out.print( _ctx );
      out.write("/hat/list?category=%ED%8E%98%EB%8F%84%EB%9D%BC\"\n");
      out.write("           class=\"");
      out.print( "페도라".equals(_cat) ? "active" : "" );
      out.write("\">페도라</a>\n");
      out.write("        <a href=\"");
      out.print( _ctx );
      out.write("/hat/list?category=%EC%8A%A4%EB%83%85%EB%B0%B1\"\n");
      out.write("           class=\"");
      out.print( "스냅백".equals(_cat) ? "active" : "" );
      out.write("\">스냅백</a>\n");
      out.write("        <a href=\"");
      out.print( _ctx );
      out.write("/board/boardList.jsp\"\n");
      out.write("           class=\"");
      out.print( _onBoard ? "active" : "" );
      out.write("\">커뮤니티</a>\n");
      out.write("    </nav>\n");
      out.write("\n");
      out.write("    <div class=\"header-icons\">\n");
      out.write("        ");
      //  c:choose
      org.apache.taglibs.standard.tag.common.core.ChooseTag _jspx_th_c_005fchoose_005f0 = (org.apache.taglibs.standard.tag.common.core.ChooseTag) _005fjspx_005ftagPool_005fc_005fchoose.get(org.apache.taglibs.standard.tag.common.core.ChooseTag.class);
      try {
        _jspx_th_c_005fchoose_005f0.setPageContext(_jspx_page_context);
        _jspx_th_c_005fchoose_005f0.setParent(null);
        int _jspx_eval_c_005fchoose_005f0 = _jspx_th_c_005fchoose_005f0.doStartTag();
        if (_jspx_eval_c_005fchoose_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\n");
            out.write("            ");
            if (_jspx_meth_c_005fwhen_005f0(_jspx_th_c_005fchoose_005f0, _jspx_page_context))
              return;
            out.write("\n");
            out.write("            ");
            //  c:otherwise
            org.apache.taglibs.standard.tag.common.core.OtherwiseTag _jspx_th_c_005fotherwise_005f0 = (org.apache.taglibs.standard.tag.common.core.OtherwiseTag) _005fjspx_005ftagPool_005fc_005fotherwise.get(org.apache.taglibs.standard.tag.common.core.OtherwiseTag.class);
            try {
              _jspx_th_c_005fotherwise_005f0.setPageContext(_jspx_page_context);
              _jspx_th_c_005fotherwise_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
              int _jspx_eval_c_005fotherwise_005f0 = _jspx_th_c_005fotherwise_005f0.doStartTag();
              if (_jspx_eval_c_005fotherwise_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
                do {
                  out.write("\n");
                  out.write("                <a href=\"");
                  out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
                  out.write("/member/mypage.jsp?tab=inquiries\" style=\"position:relative\">마이페이지");

                    if (_unreadInquiryCount > 0) { 
                  out.write("<span class=\"cart-count\">");
                  out.print( _unreadInquiryCount );
                  out.write("</span>");
 } 
                  out.write("</a>\n");
                  out.write("                ");
                  if (_jspx_meth_c_005fif_005f0(_jspx_th_c_005fotherwise_005f0, _jspx_page_context))
                    return;
                  out.write("\n");
                  out.write("                <a href=\"");
                  out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
                  out.write("/member/logout.jsp\">로그아웃</a>\n");
                  out.write("            ");
                  int evalDoAfterBody = _jspx_th_c_005fotherwise_005f0.doAfterBody();
                  if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
                    break;
                } while (true);
              }
              if (_jspx_th_c_005fotherwise_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
                return;
              }
            } finally {
              _005fjspx_005ftagPool_005fc_005fotherwise.reuse(_jspx_th_c_005fotherwise_005f0);
            }
            out.write("\n");
            out.write("        ");
            int evalDoAfterBody = _jspx_th_c_005fchoose_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fchoose_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return;
        }
      } finally {
        _005fjspx_005ftagPool_005fc_005fchoose.reuse(_jspx_th_c_005fchoose_005f0);
      }
      out.write("\n");
      out.write("        <a href=\"");
      out.print( _ctx );
      out.write("/cart/list\" style=\"position:relative\">\n");
      out.write("            장바구니<span class=\"cart-count\" id=\"cartBadge\"");
      out.print( _cartCount > 0 ? "" : " style=\"display:none\"" );
      out.write('>');
      out.print( _cartCount > 0 ? _cartCount : 0 );
      out.write("</span>\n");
      out.write("        </a>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("</header>\n");
      out.write("\n");
      out.write("<script>\n");
      out.write("(function(){\n");
      out.write("    var h   = document.getElementById('siteHeader');\n");
      out.write("    var isHome = h && h.getAttribute('data-home') === 'true';\n");
      out.write("    function upd(){ h.classList.toggle('scrolled', !isHome || window.scrollY > 50); }\n");
      out.write("    window.addEventListener('scroll', upd, {passive:true});\n");
      out.write("    upd();\n");
      out.write("})();\n");
      out.write("function incrementCartBadge() {\n");
      out.write("    var b = document.getElementById('cartBadge');\n");
      out.write("    if (!b) return;\n");
      out.write("    var n = (parseInt(b.textContent) || 0) + 1;\n");
      out.write("    b.textContent = n;\n");
      out.write("    b.style.display = '';\n");
      out.write("}\n");
      out.write("</script>\n");
      out.write("\n");
      out.write("\n");
      out.write("<style>\n");
      out.write("/* ── 레이아웃 ─────────────────────────────────── */\n");
      out.write(".cart-wrap      { max-width: 1000px; margin: 0 auto; }\n");
      out.write(".cart-page-head { display: flex; align-items: center; justify-content: space-between;\n");
      out.write("                  margin-bottom: 20px; flex-wrap: wrap; gap: 10px; }\n");
      out.write(".cart-page-head h1 { font-size: 1.25rem; font-weight: 700; }\n");
      out.write("\n");
      out.write("/* ── 테이블 ────────────────────────────────────── */\n");
      out.write(".cart-card      { background: var(--bg-secondary); border: 1px solid var(--border);\n");
      out.write("                  border-radius: 12px; overflow: hidden; }\n");
      out.write(".cart-table     { width: 100%; border-collapse: collapse; font-size: .9rem; }\n");
      out.write(".cart-table th  { padding: 13px 14px; background: var(--bg-card);\n");
      out.write("                  color: var(--text-muted); font-weight: 600; text-align: center;\n");
      out.write("                  border-bottom: 1px solid var(--border); }\n");
      out.write(".cart-table td  { padding: 14px; border-bottom: 1px solid rgba(255,255,255,.04);\n");
      out.write("                  vertical-align: middle; text-align: center; }\n");
      out.write(".cart-table tr:last-child td { border-bottom: none; }\n");
      out.write(".cart-table tbody tr:hover td { background: rgba(255,255,255,.03); }\n");
      out.write("\n");
      out.write("/* ── 상품 셀 ─────────────────────────────────── */\n");
      out.write(".cart-prod      { display: flex; align-items: center; gap: 12px; text-align: left; }\n");
      out.write(".cart-thumb     { width: 60px; height: 60px; border-radius: 8px; object-fit: cover;\n");
      out.write("                  border: 1px solid var(--border); background: var(--bg-card); flex-shrink: 0; }\n");
      out.write(".cart-thumb-empty { display: flex; align-items: center; justify-content: center;\n");
      out.write("                    font-size: 1.5rem; background: var(--bg-card);\n");
      out.write("                    border: 1px solid var(--border); }\n");
      out.write(".cart-name      { font-weight: 600; color: var(--text-primary); }\n");
      out.write(".cart-category  { font-size: .78rem; color: var(--text-muted); margin-top: 2px; }\n");
      out.write("\n");
      out.write("/* ── 수량 컨트롤 ───────────────────────────────── */\n");
      out.write(".qty-ctrl       { display: inline-flex; align-items: center;\n");
      out.write("                  border: 1px solid var(--border); border-radius: 8px; overflow: hidden; }\n");
      out.write(".qty-btn        { width: 32px; height: 32px; background: var(--bg-card); border: none;\n");
      out.write("                  color: var(--text-primary); font-size: 1rem; cursor: pointer;\n");
      out.write("                  display: flex; align-items: center; justify-content: center;\n");
      out.write("                  transition: background .15s; }\n");
      out.write(".qty-btn:hover  { background: var(--accent); color: #111; }\n");
      out.write(".qty-btn:disabled { opacity: .35; cursor: default; }\n");
      out.write(".qty-num        { min-width: 36px; text-align: center; font-weight: 600; padding: 0 4px; }\n");
      out.write("\n");
      out.write("/* ── 소계 ────────────────────────────────────── */\n");
      out.write(".subtotal       { font-weight: 700; color: var(--accent); white-space: nowrap; }\n");
      out.write("\n");
      out.write("/* ── 삭제 버튼 ───────────────────────────────── */\n");
      out.write(".btn-del        { width: 28px; height: 28px; border-radius: 50%; background: transparent;\n");
      out.write("                  border: 1px solid var(--border); color: var(--text-muted);\n");
      out.write("                  cursor: pointer; font-size: .85rem; display: inline-flex;\n");
      out.write("                  align-items: center; justify-content: center; transition: .15s; }\n");
      out.write(".btn-del:hover  { border-color: var(--danger); color: var(--danger); background: rgba(224,82,82,.1); }\n");
      out.write("\n");
      out.write("/* ── 체크박스 ────────────────────────────────── */\n");
      out.write(".cart-check     { width: 17px; height: 17px; accent-color: var(--accent); cursor: pointer; }\n");
      out.write("\n");
      out.write("/* ── 하단 요약 ───────────────────────────────── */\n");
      out.write(".cart-footer    { padding: 20px 24px; background: var(--bg-card);\n");
      out.write("                  border-top: 1px solid var(--border);\n");
      out.write("                  display: flex; align-items: center; justify-content: space-between;\n");
      out.write("                  flex-wrap: wrap; gap: 14px; }\n");
      out.write(".total-info     { display: flex; align-items: center; gap: 24px; flex-wrap: wrap; }\n");
      out.write(".total-item     { font-size: .85rem; color: var(--text-muted); }\n");
      out.write(".total-item strong { color: var(--text-primary); font-weight: 700; }\n");
      out.write(".total-main     { font-size: 1.05rem; font-weight: 700; }\n");
      out.write(".total-main strong { color: var(--accent); font-size: 1.2rem; }\n");
      out.write(".cart-actions   { display: flex; gap: 10px; flex-wrap: wrap; }\n");
      out.write("\n");
      out.write("/* ── 툴바 ────────────────────────────────────── */\n");
      out.write(".cart-toolbar   { display: flex; align-items: center; gap: 10px; margin-bottom: 12px;\n");
      out.write("                  flex-wrap: wrap; }\n");
      out.write("\n");
      out.write("/* ── 빈 장바구니 ────────────────────────────── */\n");
      out.write(".cart-empty     { text-align: center; padding: 80px 20px;\n");
      out.write("                  color: var(--text-muted); }\n");
      out.write(".cart-empty .icon   { font-size: 4rem; margin-bottom: 16px; opacity: .5; }\n");
      out.write(".cart-empty p       { font-size: 1rem; margin-bottom: 20px; }\n");
      out.write("\n");
      out.write("/* ── 품절 표시 ───────────────────────────────── */\n");
      out.write(".out-of-stock   { color: var(--danger); font-size: .76rem; margin-top: 3px; }\n");
      out.write("\n");
      out.write("/* ── 반응형 ────────────────────────────────── */\n");
      out.write("@media (max-width: 700px) {\n");
      out.write("    .cart-table th:nth-child(4),\n");
      out.write("    .cart-table td:nth-child(4),\n");
      out.write("    .cart-table th:nth-child(2),\n");
      out.write("    .cart-table td:nth-child(2) { display: none; }\n");
      out.write("    .cart-footer { flex-direction: column; align-items: flex-start; }\n");
      out.write("}\n");
      out.write("\n");
      out.write("/* ── 토스트 ────────────────────────────────── */\n");
      out.write("#cart-toast { position: fixed; bottom: 28px; left: 50%; transform: translateX(-50%) translateY(60px);\n");
      out.write("              background: var(--bg-card); border: 1px solid var(--border); border-radius: 8px;\n");
      out.write("              padding: 12px 22px; font-size: .88rem; color: var(--text-primary);\n");
      out.write("              box-shadow: 0 4px 20px rgba(0,0,0,.4); transition: transform .3s ease, opacity .3s ease;\n");
      out.write("              opacity: 0; z-index: 9999; white-space: nowrap; }\n");
      out.write("#cart-toast.show { transform: translateX(-50%) translateY(0); opacity: 1; }\n");
      out.write("</style>\n");
      out.write("\n");
      out.write("<main class=\"main-content\">\n");
      out.write("<div class=\"container\">\n");
      out.write("<div class=\"cart-wrap\">\n");
      out.write("\n");
      out.write("  <div class=\"cart-page-head\">\n");
      out.write("    <h1><svg class=\"icon-svg\" viewBox=\"0 0 24 24\"><circle cx=\"9\" cy=\"21\" r=\"1\"/><circle cx=\"20\" cy=\"21\" r=\"1\"/><path d=\"M1 1h4l2.68 13.39a2 2 0 0 0 2 1.61h9.72a2 2 0 0 0 2-1.61L23 6H6\"/></svg> 장바구니\n");
      out.write("      ");
 if (!isEmpty) { 
      out.write("\n");
      out.write("      <span style=\"font-size:.85rem;color:var(--text-muted);font-weight:400\">\n");
      out.write("        (<span id=\"item-count\">");
      out.print( cartList.size() );
      out.write("</span>개)\n");
      out.write("      </span>\n");
      out.write("      ");
 } 
      out.write("\n");
      out.write("    </h1>\n");
      out.write("    <a href=\"");
      out.print( ctx );
      out.write("/hat/list\" class=\"btn btn-secondary\" style=\"font-size:.85rem\">쇼핑 계속하기</a>\n");
      out.write("  </div>\n");
      out.write("\n");
      out.write("  ");
 if (flashSuccess != null) { 
      out.write("\n");
      out.write("  <div class=\"alert alert-success\">");
      out.print( HtmlUtils.escape(flashSuccess) );
      out.write("</div>\n");
      out.write("  ");
 } 
      out.write("\n");
      out.write("\n");
      out.write("  ");
 if (isEmpty) { 
      out.write("\n");
      out.write("  <!-- ── 빈 장바구니 ── -->\n");
      out.write("  <div class=\"cart-card\">\n");
      out.write("    <div class=\"cart-empty\">\n");
      out.write("      <div class=\"icon\"><svg class=\"icon-svg\" style=\"width:1em;height:1em\" viewBox=\"0 0 24 24\"><circle cx=\"9\" cy=\"21\" r=\"1\"/><circle cx=\"20\" cy=\"21\" r=\"1\"/><path d=\"M1 1h4l2.68 13.39a2 2 0 0 0 2 1.61h9.72a2 2 0 0 0 2-1.61L23 6H6\"/></svg></div>\n");
      out.write("      <p>장바구니가 비어 있습니다.</p>\n");
      out.write("      <a href=\"");
      out.print( ctx );
      out.write("/hat/list\" class=\"btn btn-primary\">모자 쇼핑하러 가기</a>\n");
      out.write("    </div>\n");
      out.write("  </div>\n");
      out.write("\n");
      out.write("  ");
 } else { 
      out.write("\n");
      out.write("  <!-- ── 툴바: 선택 삭제 / 전체 선택 ── -->\n");
      out.write("  <div class=\"cart-toolbar\">\n");
      out.write("    <label style=\"display:flex;align-items:center;gap:7px;cursor:pointer;font-size:.88rem\">\n");
      out.write("      <input type=\"checkbox\" id=\"checkAll\" class=\"cart-check\" onchange=\"toggleAll(this)\">\n");
      out.write("      전체 선택\n");
      out.write("    </label>\n");
      out.write("    <button class=\"btn btn-secondary\" style=\"font-size:.82rem;padding:6px 12px\"\n");
      out.write("            onclick=\"deleteSelected()\">선택 삭제</button>\n");
      out.write("  </div>\n");
      out.write("\n");
      out.write("  <!-- ── 장바구니 테이블 ── -->\n");
      out.write("  <div class=\"cart-card\">\n");
      out.write("    <table class=\"cart-table\">\n");
      out.write("      <thead>\n");
      out.write("        <tr>\n");
      out.write("          <th style=\"width:40px\"></th>\n");
      out.write("          <th style=\"width:70px\">이미지</th>\n");
      out.write("          <th style=\"text-align:left\">상품명</th>\n");
      out.write("          <th style=\"width:100px\">단가</th>\n");
      out.write("          <th style=\"width:130px\">수량</th>\n");
      out.write("          <th style=\"width:110px\">소계</th>\n");
      out.write("          <th style=\"width:44px\"></th>\n");
      out.write("        </tr>\n");
      out.write("      </thead>\n");
      out.write("      <tbody id=\"cartBody\">\n");
      out.write("      ");

        String noImage = ctx + "/images/no-image.png";
        for (CartDTO item : cartList) {
            String imgSrc = item.getHatImage();
            String proxySrc = (imgSrc != null && !imgSrc.trim().isEmpty())
              ? ctx + "/image?src=" + java.net.URLEncoder.encode(imgSrc, "UTF-8")
              : noImage;
            if (imgSrc == null || imgSrc.trim().isEmpty()) {
              imgSrc = noImage;
          }
      
      out.write("\n");
      out.write("        <tr id=\"row-");
      out.print( item.getCartNo() );
      out.write("\" class=\"cart-row\">\n");
      out.write("\n");
      out.write("          <!-- 체크박스 -->\n");
      out.write("          <td>\n");
      out.write("            <input type=\"checkbox\"\n");
      out.write("                   class=\"cart-check item-check\"\n");
      out.write("                   value=\"");
      out.print( item.getCartNo() );
      out.write("\"\n");
      out.write("                   data-price=\"");
      out.print( item.getHatPrice() );
      out.write("\"\n");
      out.write("                   onchange=\"updateSelectedTotal()\">\n");
      out.write("          </td>\n");
      out.write("\n");
      out.write("          <!-- 이미지 -->\n");
      out.write("          <td>\n");
      out.write("                ");
 if (imgSrc != null) { 
      out.write("\n");
      out.write("            <img class=\"cart-thumb\"\n");
      out.write("                  src=\"");
      out.print( proxySrc );
      out.write("\"\n");
      out.write("                alt=\"");
      out.print( HtmlUtils.escape(item.getHatName()) );
      out.write("\"\n");
      out.write("                onerror=\"this.onerror=null;this.src='");
      out.print( noImage );
      out.write("'\">\n");
      out.write("            ");
 } else { 
      out.write("\n");
      out.write("              <img class=\"cart-thumb cart-thumb-empty\"\n");
      out.write("                src=\"");
      out.print( noImage );
      out.write("\"\n");
      out.write("                alt=\"");
      out.print( HtmlUtils.escape(item.getHatName()) );
      out.write("\">\n");
      out.write("            ");
 } 
      out.write("\n");
      out.write("          </td>\n");
      out.write("\n");
      out.write("          <!-- 상품명 -->\n");
      out.write("          <td>\n");
      out.write("            <div class=\"cart-prod\">\n");
      out.write("              <div>\n");
      out.write("                <div class=\"cart-name\">\n");
      out.write("                  <a href=\"");
      out.print( ctx );
      out.write("/hat/detail?hatNo=");
      out.print( item.getHatNo() );
      out.write("\"\n");
      out.write("                     style=\"color:inherit;text-decoration:none\">\n");
      out.write("                    ");
      out.print( HtmlUtils.escape(item.getHatName()) );
      out.write("\n");
      out.write("                  </a>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"cart-category\">");
      out.print( HtmlUtils.escape(item.getHatCategory()) );
      out.write("</div>\n");
      out.write("                ");
 if (item.isOverStock()) { 
      out.write("\n");
      out.write("                <div class=\"out-of-stock\"><svg class=\"icon-svg\" style=\"width:.85em;height:.85em\" viewBox=\"0 0 24 24\"><path d=\"M10.29 3.86L1.82 18a2 2 0 0 0 1.71 3h16.94a2 2 0 0 0 1.71-3L13.71 3.86a2 2 0 0 0-3.42 0z\"/><line x1=\"12\" y1=\"9\" x2=\"12\" y2=\"13\"/><line x1=\"12\" y1=\"17\" x2=\"12.01\" y2=\"17\"/></svg> 재고 부족 (현재 재고 ");
      out.print( item.getHatStock() );
      out.write("개)</div>\n");
      out.write("                ");
 } else if (item.isSoldOut()) { 
      out.write("\n");
      out.write("                <div class=\"out-of-stock\">품절</div>\n");
      out.write("                ");
 } 
      out.write("\n");
      out.write("              </div>\n");
      out.write("            </div>\n");
      out.write("          </td>\n");
      out.write("\n");
      out.write("          <!-- 단가 -->\n");
      out.write("          <td>");
      out.print( item.getFormattedPrice() );
      out.write("원</td>\n");
      out.write("\n");
      out.write("          <!-- 수량 컨트롤 -->\n");
      out.write("          <td>\n");
      out.write("            <div class=\"qty-ctrl\">\n");
      out.write("              <button class=\"qty-btn\"\n");
      out.write("                      onclick=\"updateQty(");
      out.print( item.getCartNo() );
      out.write(", -1)\"\n");
      out.write("                      id=\"btn-minus-");
      out.print( item.getCartNo() );
      out.write("\"\n");
      out.write("                      ");
      out.print( item.getCartQty() <= 1 ? "disabled" : "" );
      out.write("\n");
      out.write("                      title=\"수량 감소\">−</button>\n");
      out.write("              <span class=\"qty-num\" id=\"qty-");
      out.print( item.getCartNo() );
      out.write('"');
      out.write('>');
      out.print( item.getCartQty() );
      out.write("</span>\n");
      out.write("              <button class=\"qty-btn\"\n");
      out.write("                      onclick=\"updateQty(");
      out.print( item.getCartNo() );
      out.write(", 1)\"\n");
      out.write("                      id=\"btn-plus-");
      out.print( item.getCartNo() );
      out.write("\"\n");
      out.write("                      ");
      out.print( item.getCartQty() >= item.getHatStock() ? "disabled" : "" );
      out.write("\n");
      out.write("                      title=\"수량 증가\">+</button>\n");
      out.write("            </div>\n");
      out.write("          </td>\n");
      out.write("\n");
      out.write("          <!-- 소계 -->\n");
      out.write("          <td>\n");
      out.write("            <span class=\"subtotal\" id=\"sub-");
      out.print( item.getCartNo() );
      out.write("\">\n");
      out.write("              ");
      out.print( item.getFormattedSubTotal() );
      out.write("원\n");
      out.write("            </span>\n");
      out.write("          </td>\n");
      out.write("\n");
      out.write("          <!-- 삭제 -->\n");
      out.write("          <td>\n");
      out.write("            <button class=\"btn-del\" onclick=\"deleteItem(");
      out.print( item.getCartNo() );
      out.write(")\" title=\"삭제\">✕</button>\n");
      out.write("          </td>\n");
      out.write("        </tr>\n");
      out.write("      ");
 } 
      out.write("\n");
      out.write("      </tbody>\n");
      out.write("    </table>\n");
      out.write("\n");
      out.write("    <!-- ── 하단 요약 + 버튼 ── -->\n");
      out.write("    <div class=\"cart-footer\">\n");
      out.write("      <div class=\"total-info\">\n");
      out.write("        <div class=\"total-item\">\n");
      out.write("          선택 합계:\n");
      out.write("          <strong id=\"selected-total\">0원</strong>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"total-main\">\n");
      out.write("          전체 합계:\n");
      out.write("          <strong id=\"total-price\">");
      out.print( formatPrice(totalPrice) );
      out.write("원</strong>\n");
      out.write("        </div>\n");
      out.write("      </div>\n");
      out.write("      <div class=\"cart-actions\">\n");
      out.write("        <button class=\"btn btn-secondary\" onclick=\"deleteSelected()\">선택 삭제</button>\n");
      out.write("        <button class=\"btn btn-primary\"   onclick=\"orderSelected()\"  id=\"btn-order\">\n");
      out.write("          선택 상품 주문\n");
      out.write("        </button>\n");
      out.write("      </div>\n");
      out.write("    </div>\n");
      out.write("  </div><!-- /cart-card -->\n");
      out.write("  ");
 } 
      out.write("\n");
      out.write("\n");
      out.write("</div>\n");
      out.write("</div>\n");
      out.write("</main>\n");
      out.write("\n");
      out.write("<div id=\"cart-toast\"></div>\n");
      out.write("\n");
      out.write("<script>\n");
      out.write("const CTX = '");
      out.print( ctx );
      out.write("';\n");
      out.write("\n");
      out.write("/* ── 가격 포맷 ─────────────────────────────── */\n");
      out.write("function formatPrice(n) {\n");
      out.write("    return Number(n).toLocaleString('ko-KR');\n");
      out.write("}\n");
      out.write("\n");
      out.write("/* ── 선택 합계 갱신 ─────────────────────────── */\n");
      out.write("function updateSelectedTotal() {\n");
      out.write("    let total = 0;\n");
      out.write("    document.querySelectorAll('.item-check:checked').forEach(cb => {\n");
      out.write("        const row  = document.getElementById('row-' + cb.value);\n");
      out.write("        const qtyEl = document.getElementById('qty-' + cb.value);\n");
      out.write("        const price = parseInt(cb.dataset.price) || 0;\n");
      out.write("        const qty   = parseInt(qtyEl ? qtyEl.textContent : 1);\n");
      out.write("        total += price * qty;\n");
      out.write("    });\n");
      out.write("    document.getElementById('selected-total').textContent = formatPrice(total) + '원';\n");
      out.write("\n");
      out.write("    // 전체 선택 체크박스 동기화\n");
      out.write("    const all      = document.querySelectorAll('.item-check');\n");
      out.write("    const checked  = document.querySelectorAll('.item-check:checked');\n");
      out.write("    const checkAllEl = document.getElementById('checkAll');\n");
      out.write("    if (checkAllEl) {\n");
      out.write("        checkAllEl.checked       = checked.length === all.length && all.length > 0;\n");
      out.write("        checkAllEl.indeterminate = checked.length > 0 && checked.length < all.length;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    // 주문 버튼 텍스트 갱신\n");
      out.write("    const btnOrder = document.getElementById('btn-order');\n");
      out.write("    if (btnOrder) {\n");
      out.write("        btnOrder.textContent = checked.length > 0\n");
      out.write("            ? checked.length + '개 상품 구매하기'\n");
      out.write("            : '선택 상품 주문';\n");
      out.write("    }\n");
      out.write("}\n");
      out.write("\n");
      out.write("/* ── 전체 선택 / 해제 ───────────────────────── */\n");
      out.write("function toggleAll(cb) {\n");
      out.write("    document.querySelectorAll('.item-check').forEach(el => el.checked = cb.checked);\n");
      out.write("    updateSelectedTotal();\n");
      out.write("}\n");
      out.write("\n");
      out.write("/* ── 수량 변경 AJAX ─────────────────────────── */\n");
      out.write("async function updateQty(cartNo, delta) {\n");
      out.write("    const qtyEl    = document.getElementById('qty-'       + cartNo);\n");
      out.write("    const minusBtn = document.getElementById('btn-minus-' + cartNo);\n");
      out.write("    const plusBtn  = document.getElementById('btn-plus-'  + cartNo);\n");
      out.write("    if (!qtyEl) return;\n");
      out.write("\n");
      out.write("    const newQty = parseInt(qtyEl.textContent) + delta;\n");
      out.write("    if (newQty < 1) return;\n");
      out.write("\n");
      out.write("    // 버튼 잠금\n");
      out.write("    if (minusBtn) minusBtn.disabled = true;\n");
      out.write("    if (plusBtn)  plusBtn.disabled  = true;\n");
      out.write("\n");
      out.write("    try {\n");
      out.write("        const res  = await fetch(CTX + '/cart/update', {\n");
      out.write("            method: 'POST',\n");
      out.write("            headers: { 'Content-Type': 'application/x-www-form-urlencoded' },\n");
      out.write("            body: 'cartNo=' + cartNo + '&qty=' + newQty\n");
      out.write("        });\n");
      out.write("        const data = await res.json();\n");
      out.write("\n");
      out.write("        if (data.result === 'ok') {\n");
      out.write("            const actualQty = data.qty || newQty;\n");
      out.write("            qtyEl.textContent = actualQty;\n");
      out.write("\n");
      out.write("            // 소계 갱신\n");
      out.write("            const subEl = document.getElementById('sub-' + cartNo);\n");
      out.write("            if (subEl) subEl.textContent = formatPrice(data.subTotal) + '원';\n");
      out.write("\n");
      out.write("            // 전체 합계 갱신\n");
      out.write("            const totalEl = document.getElementById('total-price');\n");
      out.write("            if (totalEl) totalEl.textContent = formatPrice(data.totalPrice) + '원';\n");
      out.write("\n");
      out.write("            // 선택 합계 갱신\n");
      out.write("            updateSelectedTotal();\n");
      out.write("\n");
      out.write("            // 버튼 상태 복원\n");
      out.write("            if (minusBtn) minusBtn.disabled = (actualQty <= 1);\n");
      out.write("            // stock 정보가 없으면 plus는 항상 활성화 (서버에서 재고 체크)\n");
      out.write("            if (plusBtn)  plusBtn.disabled  = false;\n");
      out.write("\n");
      out.write("        } else {\n");
      out.write("            showToast(data.msg || '수정에 실패했습니다.', 'error');\n");
      out.write("            // 버튼 복원\n");
      out.write("            if (minusBtn) minusBtn.disabled = (parseInt(qtyEl.textContent) <= 1);\n");
      out.write("            if (plusBtn)  plusBtn.disabled  = false;\n");
      out.write("        }\n");
      out.write("    } catch (e) {\n");
      out.write("        showToast('서버 오류가 발생했습니다.', 'error');\n");
      out.write("        if (minusBtn) minusBtn.disabled = false;\n");
      out.write("        if (plusBtn)  plusBtn.disabled  = false;\n");
      out.write("    }\n");
      out.write("}\n");
      out.write("\n");
      out.write("/* ── 단건 삭제 AJAX ─────────────────────────── */\n");
      out.write("async function deleteItem(cartNo) {\n");
      out.write("    if (!confirm('이 상품을 장바구니에서 삭제하시겠습니까?')) return;\n");
      out.write("\n");
      out.write("    try {\n");
      out.write("        const res  = await fetch(CTX + '/cart/delete', {\n");
      out.write("            method: 'POST',\n");
      out.write("            headers: { 'Content-Type': 'application/x-www-form-urlencoded' },\n");
      out.write("            body: 'cartNo=' + cartNo\n");
      out.write("        });\n");
      out.write("        const data = await res.json();\n");
      out.write("\n");
      out.write("        if (data.result === 'ok') {\n");
      out.write("            const row = document.getElementById('row-' + cartNo);\n");
      out.write("            if (row) row.remove();\n");
      out.write("\n");
      out.write("            // 합계 갱신\n");
      out.write("            const totalEl = document.getElementById('total-price');\n");
      out.write("            if (totalEl) totalEl.textContent = formatPrice(data.totalPrice) + '원';\n");
      out.write("\n");
      out.write("            // 아이템 수 갱신\n");
      out.write("            const countEl = document.getElementById('item-count');\n");
      out.write("            const rows    = document.querySelectorAll('.cart-row');\n");
      out.write("            if (countEl) countEl.textContent = rows.length;\n");
      out.write("\n");
      out.write("            updateSelectedTotal();\n");
      out.write("            showToast('상품이 삭제되었습니다.');\n");
      out.write("\n");
      out.write("            // 빈 장바구니 → 페이지 리로드\n");
      out.write("            if (rows.length === 0) setTimeout(() => location.reload(), 600);\n");
      out.write("\n");
      out.write("        } else {\n");
      out.write("            showToast(data.msg || '삭제에 실패했습니다.', 'error');\n");
      out.write("        }\n");
      out.write("    } catch (e) {\n");
      out.write("        showToast('서버 오류가 발생했습니다.', 'error');\n");
      out.write("    }\n");
      out.write("}\n");
      out.write("\n");
      out.write("/* ── 선택 삭제 AJAX ─────────────────────────── */\n");
      out.write("async function deleteSelected() {\n");
      out.write("    const checked = document.querySelectorAll('.item-check:checked');\n");
      out.write("    if (checked.length === 0) { showToast('삭제할 상품을 선택하세요.'); return; }\n");
      out.write("    if (!confirm(checked.length + '개 상품을 장바구니에서 삭제하시겠습니까?')) return;\n");
      out.write("\n");
      out.write("    const cartNos = Array.from(checked).map(cb => cb.value).join(',');\n");
      out.write("\n");
      out.write("    try {\n");
      out.write("        const res  = await fetch(CTX + '/cart/delete', {\n");
      out.write("            method: 'POST',\n");
      out.write("            headers: { 'Content-Type': 'application/x-www-form-urlencoded' },\n");
      out.write("            body: 'cartNos=' + encodeURIComponent(cartNos)\n");
      out.write("        });\n");
      out.write("        const data = await res.json();\n");
      out.write("\n");
      out.write("        if (data.result === 'ok') {\n");
      out.write("            checked.forEach(cb => {\n");
      out.write("                const row = document.getElementById('row-' + cb.value);\n");
      out.write("                if (row) row.remove();\n");
      out.write("            });\n");
      out.write("\n");
      out.write("            const totalEl = document.getElementById('total-price');\n");
      out.write("            if (totalEl) totalEl.textContent = formatPrice(data.totalPrice) + '원';\n");
      out.write("\n");
      out.write("            const rows    = document.querySelectorAll('.cart-row');\n");
      out.write("            const countEl = document.getElementById('item-count');\n");
      out.write("            if (countEl) countEl.textContent = rows.length;\n");
      out.write("\n");
      out.write("            // 전체 선택 해제\n");
      out.write("            const checkAllEl = document.getElementById('checkAll');\n");
      out.write("            if (checkAllEl) { checkAllEl.checked = false; checkAllEl.indeterminate = false; }\n");
      out.write("\n");
      out.write("            updateSelectedTotal();\n");
      out.write("            showToast(checked.length + '개 상품이 삭제되었습니다.');\n");
      out.write("\n");
      out.write("            if (rows.length === 0) setTimeout(() => location.reload(), 600);\n");
      out.write("\n");
      out.write("        } else {\n");
      out.write("            showToast(data.msg || '삭제에 실패했습니다.', 'error');\n");
      out.write("        }\n");
      out.write("    } catch (e) {\n");
      out.write("        showToast('서버 오류가 발생했습니다.', 'error');\n");
      out.write("    }\n");
      out.write("}\n");
      out.write("\n");
      out.write("/* ── 선택 상품 주문 ─────────────────────────── */\n");
      out.write("function orderSelected() {\n");
      out.write("    const checked = document.querySelectorAll('.item-check:checked');\n");
      out.write("    if (checked.length === 0) { showToast('주문할 상품을 선택하세요.'); return; }\n");
      out.write("\n");
      out.write("    const cartNos = Array.from(checked).map(cb => cb.value).join(',');\n");
      out.write("    location.href = CTX + '/order/checkout?cartNos=' + encodeURIComponent(cartNos);\n");
      out.write("}\n");
      out.write("\n");
      out.write("/* ── 토스트 알림 ─────────────────────────────── */\n");
      out.write("function showToast(msg, type) {\n");
      out.write("    const el = document.getElementById('cart-toast');\n");
      out.write("    el.textContent = msg;\n");
      out.write("    el.style.borderColor = type === 'error' ? 'var(--danger)' : 'var(--border)';\n");
      out.write("    el.classList.add('show');\n");
      out.write("    clearTimeout(el._timer);\n");
      out.write("    el._timer = setTimeout(() => el.classList.remove('show'), 2400);\n");
      out.write("}\n");
      out.write("\n");
      out.write("/* ── 초기화 ──────────────────────────────────── */\n");
      out.write("document.addEventListener('DOMContentLoaded', function () {\n");
      out.write("    updateSelectedTotal();\n");
      out.write("});\n");
      out.write("</script>\n");
      out.write("\n");
      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write("\n");
      out.write("<footer class=\"site-footer\">\n");
      out.write("\n");
      out.write("    <div class=\"footer__top\">\n");
      out.write("        <div class=\"footer__brand\">\n");
      out.write("            <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/\" class=\"logo\">HATSHOP</a>\n");
      out.write("            <p>모자 그 이상의 태도. 절제된 디자인으로<br>매일의 룩을 완성하는 헤드웨어.</p>\n");
      out.write("            <form class=\"footer__news\" onsubmit=\"return false;\">\n");
      out.write("                <input type=\"email\" placeholder=\"이메일로 신상품 소식 받기\" aria-label=\"이메일\">\n");
      out.write("                <button type=\"submit\">→</button>\n");
      out.write("            </form>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        <div class=\"footer__col\">\n");
      out.write("            <h4>쇼핑</h4>\n");
      out.write("            <ul>\n");
      out.write("                <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/hat/list?category=%EB%B3%BC%EC%BA%A1\">볼캡</a></li>\n");
      out.write("                <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/hat/list?category=%EB%B2%84%ED%82%B7%ED%96%87\">버킷햇</a></li>\n");
      out.write("                <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/hat/list?category=%EB%B2%A0%EB%A0%88%EB%AA%A8\">베레모</a></li>\n");
      out.write("                <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/hat/list?category=%ED%8E%98%EB%8F%84%EB%9D%BC\">페도라</a></li>\n");
      out.write("                <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/hat/list?category=%EC%8A%A4%EB%83%85%EB%B0%B1\">스냅백</a></li>\n");
      out.write("                <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/hat/list\">전체 목록</a></li>\n");
      out.write("            </ul>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        <div class=\"footer__col\">\n");
      out.write("            <h4>회원</h4>\n");
      out.write("            <ul>\n");
      out.write("                <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/member/login.jsp\">로그인</a></li>\n");
      out.write("                <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/member/join.jsp\">회원가입</a></li>\n");
      out.write("                <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/member/mypage.jsp\">마이페이지</a></li>\n");
      out.write("                <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/cart/cartList.jsp\">장바구니</a></li>\n");
      out.write("                <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/order/orderList.jsp\">주문내역</a></li>\n");
      out.write("            </ul>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        <div class=\"footer__col\">\n");
      out.write("            <h4>고객센터</h4>\n");
      out.write("            <ul>\n");
      out.write("                <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/info/delivery.jsp\">배송 안내</a></li>\n");
      out.write("                <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/info/returns.jsp\">교환 / 반품</a></li>\n");
      out.write("                <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/info/size-guide.jsp\">사이즈 가이드</a></li>\n");
      out.write("                <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/board/boardList.jsp\">커뮤니티</a></li>\n");
      out.write("            </ul>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <div class=\"footer__bottom\">\n");
      out.write("        <small>© 2026 HATSHOP. All rights reserved.</small>\n");
      out.write("        <div class=\"legal\">\n");
      out.write("            <a href=\"#\">이용약관</a>\n");
      out.write("            <a href=\"#\">개인정보처리방침</a>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("</footer>\n");
      out.write("\n");
      out.write("<!-- ── AI 고객 상담 챗봇 위젯 ── -->\n");
      out.write("<div id=\"hsChatbot\" class=\"hs-chatbot\">\n");
      out.write("  <button id=\"hsChatToggle\" type=\"button\" class=\"hs-chat-toggle\" aria-label=\"고객 상담 챗봇 열기\">💬</button>\n");
      out.write("  <div id=\"hsChatPanel\" class=\"hs-chat-panel\" hidden>\n");
      out.write("    <div class=\"hs-chat-header\">\n");
      out.write("      <span>HATSHOP 고객 상담</span>\n");
      out.write("      <button id=\"hsChatClose\" type=\"button\" class=\"hs-chat-close\" aria-label=\"닫기\">✕</button>\n");
      out.write("    </div>\n");
      out.write("    <div id=\"hsChatBody\" class=\"hs-chat-body\"></div>\n");
      out.write("    <div id=\"hsChatQuick\" class=\"hs-chat-quick\"></div>\n");
      out.write("    <div class=\"ac-wrap\" style=\"margin:0 12px\">\n");
      out.write("      <div id=\"hsAcDropdown\" class=\"ac-dropdown\"></div>\n");
      out.write("    </div>\n");
      out.write("    <form id=\"hsChatForm\" class=\"hs-chat-form\">\n");
      out.write("      <input type=\"text\" id=\"hsChatInput\" placeholder=\"질문을 입력하세요...\" autocomplete=\"off\">\n");
      out.write("      <button type=\"submit\">전송</button>\n");
      out.write("    </form>\n");
      out.write("  </div>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/js/validation.js\"></script>\n");
      out.write("<script>window.HS_CTX = '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("';</script>\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/js/chatbot.js\"></script>\n");
      out.write("</body>\n");
      out.write("</html>\n");
      out.write('\n');
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fwhen_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:when
    org.apache.taglibs.standard.tag.rt.core.WhenTag _jspx_th_c_005fwhen_005f0 = (org.apache.taglibs.standard.tag.rt.core.WhenTag) _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.WhenTag.class);
    try {
      _jspx_th_c_005fwhen_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fwhen_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
      // /WEB-INF/inc/header.jsp(65,12) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fwhen_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${empty sessionScope.loginUser}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fwhen_005f0 = _jspx_th_c_005fwhen_005f0.doStartTag();
      if (_jspx_eval_c_005fwhen_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("                <a href=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/member/login.jsp\">로그인</a>\n");
          out.write("                <a href=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/member/join.jsp\">회원가입</a>\n");
          out.write("            ");
          int evalDoAfterBody = _jspx_th_c_005fwhen_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fwhen_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } finally {
      _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f0);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fotherwise_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fotherwise_005f0);
      // /WEB-INF/inc/header.jsp(72,16) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.loginUser.grade eq 'ADMIN'}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("                    <a href=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/admin/\">관리자</a>\n");
          out.write("                ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } finally {
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
    }
    return false;
  }
}
