/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.118
 * Generated at: 2026-06-19 01:20:31 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.hat;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.hatshop.hat.HatDTO;
import com.hatshop.member.MemberDTO;
import com.hatshop.util.HtmlUtils;
import java.util.List;
import java.net.URLEncoder;
import com.hatshop.cart.CartDAO;
import com.hatshop.member.MemberDTO;

public final class hatDetail_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.LinkedHashMap<java.lang.String,java.lang.Long>(5);
    _jspx_dependants.put("/WEB-INF/inc/header.jsp", Long.valueOf(1781831986439L));
    _jspx_dependants.put("/WEB-INF/inc/nav.jsp", Long.valueOf(1781177216000L));
    _jspx_dependants.put("/WEB-INF/inc/footer.jsp", Long.valueOf(1781756931479L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1781088682000L));
    _jspx_dependants.put("jar:file:/C:/Users/gram14/OneDrive/바탕%20화면/Projact/jsp/hatshop-server/tomcat/webapps/hatshop/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(8);
    _jspx_imports_classes.add("com.hatshop.hat.HatDTO");
    _jspx_imports_classes.add("com.hatshop.member.MemberDTO");
    _jspx_imports_classes.add("com.hatshop.util.HtmlUtils");
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("java.net.URLEncoder");
    _jspx_imports_classes.add("com.hatshop.cart.CartDAO");
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fchoose;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fotherwise;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fchoose = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fotherwise = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fchoose.release();
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fotherwise.release();
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');
      out.write('\n');

    HatDTO hat = (HatDTO) request.getAttribute("hat");

    @SuppressWarnings("unchecked")
    List<HatDTO> related = (List<HatDTO>) request.getAttribute("related");

    MemberDTO loginUser = (MemberDTO) session.getAttribute("loginUser");

    String  ctx      = request.getContextPath();
    boolean soldOut  = hat.isSoldOut();
    int     stock    = hat.getHatStock();

    /* 플래시 메시지 (장바구니 담기 결과) */
    String flashSuccess = (String) session.getAttribute("flashSuccess");
    String flashError   = (String) session.getAttribute("flashError");
    session.removeAttribute("flashSuccess");
    session.removeAttribute("flashError");

    /* 로그인 후 복귀 URL */
    String backPath   = "/hat/detail?hatNo=" + hat.getHatNo();
    String redirectUrl = URLEncoder.encode(backPath, "UTF-8");

      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write('\n');

    String _ctx = request.getContextPath();
    String _uri = request.getRequestURI();
    String _cat = request.getParameter("category");
    if (_cat == null) _cat = "";
    boolean _onHome  = _uri.endsWith("/") || _uri.endsWith("index.jsp") || _uri.equals(_ctx + "/");
    boolean _onBoard = _uri.contains("/board/");
    boolean _onHat   = _uri.contains("/hat/");

    MemberDTO _hdrUser = (MemberDTO) session.getAttribute("loginUser");
    int _cartCount = 0;
    int _unreadInquiryCount = 0;
    if (_hdrUser != null) {
        try { _cartCount = new CartDAO().getCartCount(_hdrUser.getMemberId()); }
        catch (Exception _e) { /* 배지 카운트 실패 시 0으로 유지 */ }
        try {
            java.sql.Connection _conn = com.hatshop.db.DBConn.getConnection();
            try (java.sql.PreparedStatement _ps = _conn.prepareStatement(
                    "SELECT COUNT(*) FROM inquiry WHERE member_id = ? AND inquiry_status IN ('ANSWERED','CLOSED') AND is_read = 0")) {
                _ps.setString(1, _hdrUser.getMemberId());
                try (java.sql.ResultSet _rs = _ps.executeQuery()) {
                    if (_rs.next()) _unreadInquiryCount = _rs.getInt(1);
                }
            }
        } catch (Exception _e) { /* 알림 카운트 실패 시 0으로 유지 */ }
    }

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"ko\">\n");
      out.write("<head>\n");
      out.write("    <meta charset=\"UTF-8\">\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("    <title>HATSHOP — Wear Your Statement</title>\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.print( _ctx );
      out.write("/css/style.css?v=5\">\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.print( _ctx );
      out.write("/css/chatbot.css?v=5\">\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("<header class=\"site-header ");
      out.print( _onHome ? "" : "scrolled" );
      out.write("\" id=\"siteHeader\" data-home=\"");
      out.print( _onHome );
      out.write("\">\n");
      out.write("\n");
      out.write("    <a href=\"");
      out.print( _ctx );
      out.write("/\" class=\"brand\">HATSHOP</a>\n");
      out.write("\n");
      out.write("    <nav class=\"site-nav-primary\" id=\"primaryNav\">\n");
      out.write("        <a href=\"");
      out.print( _ctx );
      out.write("/\"\n");
      out.write("           class=\"");
      out.print( _onHome ? "active" : "" );
      out.write("\">Home</a>\n");
      out.write("        <a href=\"");
      out.print( _ctx );
      out.write("/hat/list?category=%EB%B3%BC%EC%BA%A1\"\n");
      out.write("           class=\"");
      out.print( "볼캡".equals(_cat) ? "active" : "" );
      out.write("\">볼캡</a>\n");
      out.write("        <a href=\"");
      out.print( _ctx );
      out.write("/hat/list?category=%EB%B2%84%ED%82%B7%ED%96%87\"\n");
      out.write("           class=\"");
      out.print( "버킷햇".equals(_cat) ? "active" : "" );
      out.write("\">버킷햇</a>\n");
      out.write("        <a href=\"");
      out.print( _ctx );
      out.write("/hat/list?category=%EB%B2%A0%EB%A0%88%EB%AA%A8\"\n");
      out.write("           class=\"");
      out.print( "베레모".equals(_cat) ? "active" : "" );
      out.write("\">베레모</a>\n");
      out.write("        <a href=\"");
      out.print( _ctx );
      out.write("/hat/list?category=%ED%8E%98%EB%8F%84%EB%9D%BC\"\n");
      out.write("           class=\"");
      out.print( "페도라".equals(_cat) ? "active" : "" );
      out.write("\">페도라</a>\n");
      out.write("        <a href=\"");
      out.print( _ctx );
      out.write("/hat/list?category=%EC%8A%A4%EB%83%85%EB%B0%B1\"\n");
      out.write("           class=\"");
      out.print( "스냅백".equals(_cat) ? "active" : "" );
      out.write("\">스냅백</a>\n");
      out.write("        <a href=\"");
      out.print( _ctx );
      out.write("/board/boardList.jsp\"\n");
      out.write("           class=\"");
      out.print( _onBoard ? "active" : "" );
      out.write("\">커뮤니티</a>\n");
      out.write("    </nav>\n");
      out.write("\n");
      out.write("    <div class=\"header-icons\">\n");
      out.write("        ");
      //  c:choose
      org.apache.taglibs.standard.tag.common.core.ChooseTag _jspx_th_c_005fchoose_005f0 = (org.apache.taglibs.standard.tag.common.core.ChooseTag) _005fjspx_005ftagPool_005fc_005fchoose.get(org.apache.taglibs.standard.tag.common.core.ChooseTag.class);
      try {
        _jspx_th_c_005fchoose_005f0.setPageContext(_jspx_page_context);
        _jspx_th_c_005fchoose_005f0.setParent(null);
        int _jspx_eval_c_005fchoose_005f0 = _jspx_th_c_005fchoose_005f0.doStartTag();
        if (_jspx_eval_c_005fchoose_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\n");
            out.write("            ");
            if (_jspx_meth_c_005fwhen_005f0(_jspx_th_c_005fchoose_005f0, _jspx_page_context))
              return;
            out.write("\n");
            out.write("            ");
            //  c:otherwise
            org.apache.taglibs.standard.tag.common.core.OtherwiseTag _jspx_th_c_005fotherwise_005f0 = (org.apache.taglibs.standard.tag.common.core.OtherwiseTag) _005fjspx_005ftagPool_005fc_005fotherwise.get(org.apache.taglibs.standard.tag.common.core.OtherwiseTag.class);
            try {
              _jspx_th_c_005fotherwise_005f0.setPageContext(_jspx_page_context);
              _jspx_th_c_005fotherwise_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
              int _jspx_eval_c_005fotherwise_005f0 = _jspx_th_c_005fotherwise_005f0.doStartTag();
              if (_jspx_eval_c_005fotherwise_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
                do {
                  out.write("\n");
                  out.write("                <a href=\"");
                  out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
                  out.write("/member/mypage.jsp?tab=inquiries\" style=\"position:relative\">마이페이지");

                    if (_unreadInquiryCount > 0) { 
                  out.write("<span class=\"cart-count\">");
                  out.print( _unreadInquiryCount );
                  out.write("</span>");
 } 
                  out.write("</a>\n");
                  out.write("                ");
                  if (_jspx_meth_c_005fif_005f0(_jspx_th_c_005fotherwise_005f0, _jspx_page_context))
                    return;
                  out.write("\n");
                  out.write("                <a href=\"");
                  out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
                  out.write("/member/logout.jsp\">로그아웃</a>\n");
                  out.write("            ");
                  int evalDoAfterBody = _jspx_th_c_005fotherwise_005f0.doAfterBody();
                  if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
                    break;
                } while (true);
              }
              if (_jspx_th_c_005fotherwise_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
                return;
              }
            } finally {
              _005fjspx_005ftagPool_005fc_005fotherwise.reuse(_jspx_th_c_005fotherwise_005f0);
            }
            out.write("\n");
            out.write("        ");
            int evalDoAfterBody = _jspx_th_c_005fchoose_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fchoose_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return;
        }
      } finally {
        _005fjspx_005ftagPool_005fc_005fchoose.reuse(_jspx_th_c_005fchoose_005f0);
      }
      out.write("\n");
      out.write("        <a href=\"");
      out.print( _ctx );
      out.write("/cart/list\" style=\"position:relative\">\n");
      out.write("            장바구니<span class=\"cart-count\" id=\"cartBadge\"");
      out.print( _cartCount > 0 ? "" : " style=\"display:none\"" );
      out.write('>');
      out.print( _cartCount > 0 ? _cartCount : 0 );
      out.write("</span>\n");
      out.write("        </a>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("</header>\n");
      out.write("\n");
      out.write("<script>\n");
      out.write("(function(){\n");
      out.write("    var h   = document.getElementById('siteHeader');\n");
      out.write("    var isHome = h && h.getAttribute('data-home') === 'true';\n");
      out.write("    function upd(){ h.classList.toggle('scrolled', !isHome || window.scrollY > 50); }\n");
      out.write("    window.addEventListener('scroll', upd, {passive:true});\n");
      out.write("    upd();\n");
      out.write("})();\n");
      out.write("function incrementCartBadge() {\n");
      out.write("    var b = document.getElementById('cartBadge');\n");
      out.write("    if (!b) return;\n");
      out.write("    var n = (parseInt(b.textContent) || 0) + 1;\n");
      out.write("    b.textContent = n;\n");
      out.write("    b.style.display = '';\n");
      out.write("}\n");
      out.write("</script>\n");
      out.write('\n');
      out.write('\n');
      out.write("\n");
      out.write("\n");
      out.write("<style>\n");
      out.write("/* ── 브레드크럼 ── */\n");
      out.write(".breadcrumb {\n");
      out.write("  display: flex; align-items: center; gap: 6px; flex-wrap: wrap;\n");
      out.write("  font-family: var(--mono); font-size: 10px; letter-spacing: .14em;\n");
      out.write("  text-transform: uppercase; color: var(--ink-soft); margin-bottom: 36px;\n");
      out.write("}\n");
      out.write(".breadcrumb a:hover { color: var(--ink); }\n");
      out.write(".breadcrumb .sep { color: var(--line); }\n");
      out.write("\n");
      out.write("/* ── 상세 2컬럼 ── */\n");
      out.write(".detail-wrap {\n");
      out.write("  display: grid; grid-template-columns: 1fr 1fr;\n");
      out.write("  gap: 60px; align-items: start; margin-bottom: 80px;\n");
      out.write("}\n");
      out.write("\n");
      out.write("/* ── 이미지 영역 ── */\n");
      out.write(".detail-img-box {\n");
      out.write("  background: var(--ph-a); aspect-ratio: 4/5; overflow: hidden;\n");
      out.write("  position: sticky; top: calc(var(--header-h) + 16px);\n");
      out.write("}\n");
      out.write(".detail-img-box img { width: 100%; height: 100%; object-fit: cover; mix-blend-mode: multiply; transition: transform .6s; }\n");
      out.write(".detail-img-box:hover img { transform: scale(1.04); }\n");
      out.write(".detail-img-placeholder { display: none; }\n");
      out.write("\n");
      out.write("/* ── 정보 영역 ── */\n");
      out.write(".detail-info { display: flex; flex-direction: column; gap: 0; padding-top: 8px; }\n");
      out.write("\n");
      out.write(".detail-cat-badge {\n");
      out.write("  font-family: var(--mono); font-size: 10px; font-weight: 700; letter-spacing: .2em;\n");
      out.write("  text-transform: uppercase; color: var(--ink-soft); margin-bottom: 14px; display: block;\n");
      out.write("}\n");
      out.write(".detail-name {\n");
      out.write("  font-size: clamp(26px, 4vw, 44px); font-weight: 900; line-height: .95;\n");
      out.write("  letter-spacing: -.03em; text-transform: uppercase; margin-bottom: 22px;\n");
      out.write("}\n");
      out.write(".detail-price {\n");
      out.write("  font-size: clamp(22px, 3vw, 32px); font-weight: 800;\n");
      out.write("  letter-spacing: -.01em; margin-bottom: 26px;\n");
      out.write("}\n");
      out.write(".detail-divider { border: none; border-top: 1px solid var(--line); margin: 24px 0; }\n");
      out.write("\n");
      out.write("/* 재고 상태 */\n");
      out.write(".stock-badge {\n");
      out.write("  display: inline-flex; align-items: center; gap: 6px;\n");
      out.write("  font-size: 11px; font-weight: 700; letter-spacing: .08em; padding: 6px 12px;\n");
      out.write("}\n");
      out.write(".stock-ok   { background: rgba(42,125,79,.08); color: var(--green); }\n");
      out.write(".stock-low  { background: rgba(200,0,0,.06);   color: #a83200; }\n");
      out.write(".stock-none { background: rgba(0,0,0,.05);     color: var(--ink-soft); }\n");
      out.write("\n");
      out.write("/* 수량 선택기 */\n");
      out.write(".qty-row   { display: flex; align-items: center; gap: 16px; margin: 20px 0; }\n");
      out.write(".qty-label {\n");
      out.write("  font-size: 11px; font-weight: 700; letter-spacing: .12em;\n");
      out.write("  text-transform: uppercase; color: var(--ink-soft); flex-shrink: 0;\n");
      out.write("}\n");
      out.write(".qty-ctrl  { display: flex; align-items: center; border: 1.4px solid var(--line); }\n");
      out.write(".qty-btn   {\n");
      out.write("  width: 42px; height: 42px; background: transparent; border: none; color: var(--ink);\n");
      out.write("  font-size: 18px; line-height: 1; cursor: pointer; transition: background .15s; font-family: inherit;\n");
      out.write("}\n");
      out.write(".qty-btn:hover:not(:disabled) { background: var(--ph-a); }\n");
      out.write(".qty-btn:disabled { opacity: .3; cursor: not-allowed; }\n");
      out.write(".qty-input {\n");
      out.write("  width: 60px; height: 42px; text-align: center; background: transparent;\n");
      out.write("  border: none; border-left: 1px solid var(--line); border-right: 1px solid var(--line);\n");
      out.write("  color: var(--ink); font-size: 14px; font-weight: 800; font-family: inherit;\n");
      out.write("  -moz-appearance: textfield;\n");
      out.write("}\n");
      out.write(".qty-input::-webkit-outer-spin-button,\n");
      out.write(".qty-input::-webkit-inner-spin-button { -webkit-appearance: none; }\n");
      out.write(".qty-max { font-size: 11px; color: var(--ink-soft); font-family: var(--mono); }\n");
      out.write("\n");
      out.write("/* 총 금액 미리보기 */\n");
      out.write(".total-preview {\n");
      out.write("  background: var(--ph-a); padding: 14px 18px; margin-top: 8px;\n");
      out.write("  display: flex; justify-content: space-between; align-items: center;\n");
      out.write("}\n");
      out.write(".total-preview span:first-child {\n");
      out.write("  font-size: 11px; font-weight: 700; letter-spacing: .12em;\n");
      out.write("  text-transform: uppercase; color: var(--ink-soft);\n");
      out.write("}\n");
      out.write(".total-preview .total-amount { font-size: 16px; font-weight: 900; }\n");
      out.write("\n");
      out.write("/* 액션 버튼 */\n");
      out.write(".action-btns { display: flex; gap: 10px; margin-top: 8px; }\n");
      out.write(".action-btns .btn { flex: 1; justify-content: center; }\n");
      out.write(".btn-cart-add {\n");
      out.write("  background: transparent; color: var(--ink); border-color: var(--ink);\n");
      out.write("}\n");
      out.write(".btn-cart-add:hover { background: var(--ink); color: #fff; }\n");
      out.write(".btn-buy-now  { background: var(--ink); color: #fff; }\n");
      out.write(".btn-buy-now:hover { background: var(--btn-hover); }\n");
      out.write("\n");
      out.write("/* 품절 버튼 */\n");
      out.write(".btn-soldout {\n");
      out.write("  flex: 1; padding: 16px; font-size: 12px; font-weight: 800;\n");
      out.write("  letter-spacing: .12em; text-transform: uppercase;\n");
      out.write("  background: var(--ph-a); color: var(--ink-soft); border: 1.4px solid var(--line);\n");
      out.write("  cursor: not-allowed; font-family: inherit;\n");
      out.write("}\n");
      out.write("\n");
      out.write("/* ── 상품 설명 ── */\n");
      out.write(".desc-section {\n");
      out.write("  border-top: 1px solid var(--line); padding: 48px 0; margin-bottom: 64px;\n");
      out.write("}\n");
      out.write(".desc-section h2 {\n");
      out.write("  font-size: 12px; font-weight: 800; letter-spacing: .2em;\n");
      out.write("  text-transform: uppercase; color: var(--ink-soft); margin-bottom: 20px;\n");
      out.write("}\n");
      out.write(".desc-body { line-height: 1.9; color: #555; white-space: pre-line; font-size: 15px; }\n");
      out.write(".desc-empty { color: var(--ink-soft); font-style: italic; font-size: 14px; }\n");
      out.write("\n");
      out.write("/* ── 연관 상품 ── */\n");
      out.write(".related-section { padding-bottom: 80px; }\n");
      out.write(".related-section h2 {\n");
      out.write("  font-size: clamp(22px, 3.5vw, 38px); font-weight: 900;\n");
      out.write("  letter-spacing: -.025em; text-transform: uppercase;\n");
      out.write("  line-height: .95; margin-bottom: 28px;\n");
      out.write("}\n");
      out.write(".related-grid { display: grid; grid-template-columns: repeat(4, 1fr); gap: 14px; }\n");
      out.write(".related-card { position: relative; }\n");
      out.write(".related-card a { display: block; color: inherit; }\n");
      out.write(".related-img {\n");
      out.write("  aspect-ratio: 4/5; overflow: hidden; background: var(--ph-a); margin-bottom: 12px;\n");
      out.write("}\n");
      out.write(".related-img img {\n");
      out.write("  width: 100%; height: 100%; object-fit: cover;\n");
      out.write("  transition: transform .7s cubic-bezier(.2,.7,.2,1);\n");
      out.write("}\n");
      out.write(".related-card:hover .related-img img { transform: scale(1.06); }\n");
      out.write(".r-fallback { display: none; }\n");
      out.write(".related-body { padding: 0 2px; }\n");
      out.write(".related-name  { font-size: 13px; font-weight: 600; margin-bottom: 5px; line-height: 1.3; }\n");
      out.write(".related-price { font-size: 13px; font-weight: 800; }\n");
      out.write(".related-sold  { font-size: 11px; color: var(--ink-soft); margin-top: 2px; }\n");
      out.write("\n");
      out.write("/* ── 반응형 ── */\n");
      out.write("@media (max-width: 900px) {\n");
      out.write("  .detail-wrap { grid-template-columns: 1fr; gap: 28px; }\n");
      out.write("  .detail-img-box { position: static; aspect-ratio: 1/1; }\n");
      out.write("  .detail-name { font-size: 1.6rem; }\n");
      out.write("  .detail-price { font-size: 1.4rem; }\n");
      out.write("  .related-grid { grid-template-columns: repeat(2, 1fr); }\n");
      out.write("}\n");
      out.write("@media (max-width: 480px) {\n");
      out.write("  .action-btns { flex-direction: column; }\n");
      out.write("  .related-grid { gap: 10px; }\n");
      out.write("}\n");
      out.write("</style>\n");
      out.write("\n");
      out.write("<main class=\"main-content\">\n");
      out.write("<div class=\"container\">\n");
      out.write("\n");
      out.write("  <!-- 플래시 메시지 -->\n");
      out.write("  ");
 if (flashSuccess != null) { 
      out.write("\n");
      out.write("  <div class=\"alert alert-success\" style=\"margin-bottom:20px\">");
      out.print( flashSuccess );
      out.write("</div>\n");
      out.write("  ");
 } 
      out.write('\n');
      out.write(' ');
      out.write(' ');
 if (flashError != null) { 
      out.write("\n");
      out.write("  <div class=\"alert alert-error\" style=\"margin-bottom:20px\">");
      out.print( flashError );
      out.write("</div>\n");
      out.write("  ");
 } 
      out.write("\n");
      out.write("\n");
      out.write("  <!-- ── 브레드크럼 ── -->\n");
      out.write("  <nav class=\"breadcrumb\">\n");
      out.write("    <a href=\"");
      out.print( ctx );
      out.write("/\">홈</a>\n");
      out.write("    <span class=\"sep\">›</span>\n");
      out.write("    <a href=\"");
      out.print( ctx );
      out.write("/hat/list\">전체</a>\n");
      out.write("    <span class=\"sep\">›</span>\n");
      out.write("    <a href=\"");
      out.print( ctx );
      out.write("/hat/list?category=");
      out.print( URLEncoder.encode(hat.getHatCategory(),"UTF-8") );
      out.write("\">\n");
      out.write("      ");
      out.print( HtmlUtils.escape(hat.getHatCategory()) );
      out.write("\n");
      out.write("    </a>\n");
      out.write("    <span class=\"sep\">›</span>\n");
      out.write("    <span>");
      out.print( HtmlUtils.escape(hat.getHatName()) );
      out.write("</span>\n");
      out.write("  </nav>\n");
      out.write("\n");
      out.write("  <!-- ── 메인 상세 ── -->\n");
      out.write("  <div class=\"detail-wrap\">\n");
      out.write("\n");
      out.write("    <!-- 이미지 -->\n");
      out.write("    <div class=\"detail-img-box\">\n");
      out.write("       ");
 String imgSrc = hat.getHatImage();
          String noImage = ctx + "/images/no-image.png";
       
      out.write("\n");
      out.write("      ");
 if (imgSrc != null && !imgSrc.trim().isEmpty()) { 
      out.write("\n");
      out.write("      <img src=\"");
      out.print( ctx );
      out.write("/image?src=");
      out.print( URLEncoder.encode(imgSrc, "UTF-8") );
      out.write("\"\n");
      out.write("         alt=\"");
      out.print( HtmlUtils.escape(hat.getHatName()) );
      out.write("\"\n");
      out.write("         onerror=\"this.onerror=null;this.src='");
      out.print( noImage );
      out.write("'\">\n");
      out.write("      <span class=\"detail-img-placeholder\" style=\"display:none\"><svg class=\"icon-svg\" style=\"width:2.2em;height:2.2em\" viewBox=\"0 0 24 24\"><path d=\"M4 16c0-4.4 3.6-8 8-8s8 3.6 8 8\"/><ellipse cx=\"12\" cy=\"16\" rx=\"10\" ry=\"2.2\"/></svg></span>\n");
      out.write("      ");
 } else { 
      out.write("\n");
      out.write("       <img src=\"");
      out.print( noImage );
      out.write("\" alt=\"");
      out.print( HtmlUtils.escape(hat.getHatName()) );
      out.write("\">\n");
      out.write("      ");
 } 
      out.write("\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <!-- 정보 -->\n");
      out.write("    <div class=\"detail-info\">\n");
      out.write("\n");
      out.write("      <span class=\"detail-cat-badge\">");
      out.print( HtmlUtils.escape(hat.getHatCategory()) );
      out.write("</span>\n");
      out.write("      <h1 class=\"detail-name\">");
      out.print( HtmlUtils.escape(hat.getHatName()) );
      out.write("</h1>\n");
      out.write("      <p class=\"detail-price\">");
      out.print( hat.getFormattedPrice() );
      out.write("원</p>\n");
      out.write("\n");
      out.write("      <hr class=\"detail-divider\">\n");
      out.write("\n");
      out.write("      <!-- 재고 상태 -->\n");
      out.write("      <div>\n");
      out.write("        ");
 if (soldOut) { 
      out.write("\n");
      out.write("        <span class=\"stock-badge stock-none\"><svg class=\"icon-svg\" style=\"width:.9em;height:.9em\" viewBox=\"0 0 24 24\"><circle cx=\"12\" cy=\"12\" r=\"10\"/><line x1=\"4.93\" y1=\"4.93\" x2=\"19.07\" y2=\"19.07\"/></svg> 품절</span>\n");
      out.write("        ");
 } else if (stock <= 5) { 
      out.write("\n");
      out.write("        <span class=\"stock-badge stock-low\"><svg class=\"icon-svg\" style=\"width:.9em;height:.9em\" viewBox=\"0 0 24 24\"><path d=\"M10.29 3.86L1.82 18a2 2 0 0 0 1.71 3h16.94a2 2 0 0 0 1.71-3L13.71 3.86a2 2 0 0 0-3.42 0z\"/><line x1=\"12\" y1=\"9\" x2=\"12\" y2=\"13\"/><line x1=\"12\" y1=\"17\" x2=\"12.01\" y2=\"17\"/></svg> 잔여 ");
      out.print( stock );
      out.write("개 (품절 임박)</span>\n");
      out.write("        ");
 } else { 
      out.write("\n");
      out.write("        <span class=\"stock-badge stock-ok\"><svg class=\"icon-svg\" style=\"width:.9em;height:.9em\" viewBox=\"0 0 24 24\"><polyline points=\"20 6 9 17 4 12\"/></svg> 재고 있음 (");
      out.print( stock );
      out.write("개)</span>\n");
      out.write("        ");
 } 
      out.write("\n");
      out.write("      </div>\n");
      out.write("\n");
      out.write("      <hr class=\"detail-divider\">\n");
      out.write("\n");
      out.write("      <!-- 수량 선택 -->\n");
      out.write("      <div class=\"qty-row\">\n");
      out.write("        <span class=\"qty-label\">수량</span>\n");
      out.write("        <div class=\"qty-ctrl\">\n");
      out.write("          <button type=\"button\" class=\"qty-btn\" id=\"btnMinus\"\n");
      out.write("                  onclick=\"changeQty(-1)\" ");
      out.print( soldOut ? "disabled" : "" );
      out.write(">−</button>\n");
      out.write("          <input type=\"number\" class=\"qty-input\" id=\"qtyDisplay\"\n");
      out.write("                 value=\"1\" min=\"1\" max=\"");
      out.print( Math.max(stock, 1) );
      out.write("\"\n");
      out.write("                 oninput=\"syncQty(this)\" ");
      out.print( soldOut ? "disabled" : "" );
      out.write(">\n");
      out.write("          <button type=\"button\" class=\"qty-btn\" id=\"btnPlus\"\n");
      out.write("                  onclick=\"changeQty(1)\" ");
      out.print( soldOut ? "disabled" : "" );
      out.write(">+</button>\n");
      out.write("        </div>\n");
      out.write("        ");
 if (!soldOut) { 
      out.write("\n");
      out.write("        <span class=\"qty-max\">최대 ");
      out.print( stock );
      out.write("개</span>\n");
      out.write("        ");
 } 
      out.write("\n");
      out.write("      </div>\n");
      out.write("\n");
      out.write("      <!-- 총 금액 미리보기 -->\n");
      out.write("      ");
 if (!soldOut) { 
      out.write("\n");
      out.write("      <div class=\"total-preview\">\n");
      out.write("        <span>총 주문금액</span>\n");
      out.write("        <span class=\"total-amount\" id=\"totalPreview\">");
      out.print( hat.getFormattedPrice() );
      out.write("원</span>\n");
      out.write("      </div>\n");
      out.write("      ");
 } 
      out.write("\n");
      out.write("\n");
      out.write("      <!-- 액션 버튼 -->\n");
      out.write("      <div class=\"action-btns\" style=\"margin-top:16px\">\n");
      out.write("        ");
 if (soldOut) { 
      out.write("\n");
      out.write("        <button class=\"btn-soldout\" disabled><svg class=\"icon-svg\" style=\"width:.9em;height:.9em\" viewBox=\"0 0 24 24\"><circle cx=\"12\" cy=\"12\" r=\"10\"/><line x1=\"4.93\" y1=\"4.93\" x2=\"19.07\" y2=\"19.07\"/></svg> 품절된 상품입니다</button>\n");
      out.write("        ");
 } else { 
      out.write("\n");
      out.write("        <button type=\"button\" class=\"btn btn-cart-add\" onclick=\"submitCart(false)\">장바구니 담기</button>\n");
      out.write("        <button type=\"button\" class=\"btn btn-buy-now\" onclick=\"submitCart(true)\">바로 구매</button>\n");
      out.write("        ");
 } 
      out.write("\n");
      out.write("      </div>\n");
      out.write("\n");
      out.write("      <!-- hatNo 참조용 (submitCart에서 사용) -->\n");
      out.write("      <span id=\"cartHatNo\" data-no=\"");
      out.print( hat.getHatNo() );
      out.write("\" style=\"display:none\"></span>\n");
      out.write("\n");
      out.write("    </div><!-- /detail-info -->\n");
      out.write("  </div><!-- /detail-wrap -->\n");
      out.write("\n");
      out.write("  <!-- ── 상품 설명 ── -->\n");
      out.write("  <section class=\"desc-section\">\n");
      out.write("    <h2>상품 설명</h2>\n");
      out.write("    <div class=\"desc-body\">\n");
      out.write("      ");
 String desc = hat.getHatDesc(); 
      out.write("\n");
      out.write("      ");
 if (desc != null && !desc.trim().isEmpty()) { 
      out.write("\n");
      out.write("      ");
      out.print( HtmlUtils.nl2br(desc) );
      out.write("\n");
      out.write("      ");
 } else { 
      out.write("\n");
      out.write("      <span class=\"desc-empty\">등록된 상품 설명이 없습니다.</span>\n");
      out.write("      ");
 } 
      out.write("\n");
      out.write("    </div>\n");
      out.write("  </section>\n");
      out.write("\n");
      out.write("  <!-- ── 연관 상품 ── -->\n");
      out.write("  ");
 if (related != null && !related.isEmpty()) { 
      out.write("\n");
      out.write("  <section class=\"related-section\">\n");
      out.write("    <h2>같은 카테고리 상품</h2>\n");
      out.write("    <div class=\"related-grid\">\n");
      out.write("      ");
 for (HatDTO r : related) { 
      out.write("\n");
      out.write("      <div class=\"related-card\">\n");
      out.write("        <a href=\"");
      out.print( ctx );
      out.write("/hat/detail?hatNo=");
      out.print( r.getHatNo() );
      out.write("\">\n");
      out.write("          <div class=\"related-img\">\n");
      out.write("              ");
 String riSrc = r.getHatImage(); 
      out.write("\n");
      out.write("                ");
 if (riSrc != null && !riSrc.trim().isEmpty()) { 
      out.write("\n");
      out.write("                  <img src=\"");
      out.print( ctx );
      out.write("/image?src=");
      out.print( URLEncoder.encode(riSrc, "UTF-8") );
      out.write("\"\n");
      out.write("                alt=\"");
      out.print( HtmlUtils.escape(r.getHatName()) );
      out.write("\"\n");
      out.write("                onerror=\"this.onerror=null;this.src='");
      out.print( ctx );
      out.write("/images/no-image.png'\">\n");
      out.write("            <span class=\"r-fallback\" style=\"display:none\"><svg class=\"icon-svg\" viewBox=\"0 0 24 24\"><path d=\"M4 16c0-4.4 3.6-8 8-8s8 3.6 8 8\"/><ellipse cx=\"12\" cy=\"16\" rx=\"10\" ry=\"2.2\"/></svg></span>\n");
      out.write("            ");
 } else { 
      out.write("\n");
      out.write("              <img src=\"");
      out.print( ctx );
      out.write("/images/no-image.png\" alt=\"");
      out.print( HtmlUtils.escape(r.getHatName()) );
      out.write("\">\n");
      out.write("            ");
 } 
      out.write("\n");
      out.write("          </div>\n");
      out.write("          <div class=\"related-body\">\n");
      out.write("            <p class=\"related-name\">");
      out.print( HtmlUtils.escape(r.getHatName()) );
      out.write("</p>\n");
      out.write("            <p class=\"related-price\">");
      out.print( r.getFormattedPrice() );
      out.write("원</p>\n");
      out.write("            ");
 if (r.isSoldOut()) { 
      out.write("<p class=\"related-sold\">품절</p>");
 } 
      out.write("\n");
      out.write("          </div>\n");
      out.write("        </a>\n");
      out.write("      </div>\n");
      out.write("      ");
 } 
      out.write("\n");
      out.write("    </div>\n");
      out.write("  </section>\n");
      out.write("  ");
 } 
      out.write("\n");
      out.write("\n");
      out.write("</div><!-- /container -->\n");
      out.write("</main>\n");
      out.write("\n");
      out.write("<script>\n");
      out.write("const IS_LOGGED_IN  = ");
      out.print( loginUser != null ? "true" : "false" );
      out.write(";\n");
      out.write("const LOGIN_URL     = '");
      out.print( ctx );
      out.write("/member/login.jsp?redirectURL=");
      out.print( redirectUrl );
      out.write("';\n");
      out.write("const UNIT_PRICE    = ");
      out.print( hat.getHatPrice() );
      out.write(";\n");
      out.write("const MAX_STOCK     = ");
      out.print( Math.max(stock, 1) );
      out.write(";\n");
      out.write("\n");
      out.write("/* ── 수량 변경 ── */\n");
      out.write("function changeQty(delta) {\n");
      out.write("    const input = document.getElementById('qtyDisplay');\n");
      out.write("    let val = parseInt(input.value || 1) + delta;\n");
      out.write("    val = Math.max(1, Math.min(val, MAX_STOCK));\n");
      out.write("    input.value = val;\n");
      out.write("    onQtyChange(val);\n");
      out.write("}\n");
      out.write("\n");
      out.write("function syncQty(input) {\n");
      out.write("    let val = parseInt(input.value);\n");
      out.write("    if (isNaN(val) || val < 1) val = 1;\n");
      out.write("    if (val > MAX_STOCK) val = MAX_STOCK;\n");
      out.write("    input.value = val;\n");
      out.write("    onQtyChange(val);\n");
      out.write("}\n");
      out.write("\n");
      out.write("function onQtyChange(val) {\n");
      out.write("    /* 총 금액 미리보기 갱신 */\n");
      out.write("    const preview = document.getElementById('totalPreview');\n");
      out.write("    if (preview) {\n");
      out.write("        preview.textContent = (UNIT_PRICE * val).toLocaleString('ko-KR') + '원';\n");
      out.write("    }\n");
      out.write("    /* +/- 버튼 상태 */\n");
      out.write("    document.getElementById('btnMinus').disabled = (val <= 1);\n");
      out.write("    document.getElementById('btnPlus').disabled  = (val >= MAX_STOCK);\n");
      out.write("}\n");
      out.write("\n");
      out.write("/* ── 장바구니 제출 ── */\n");
      out.write("function submitCart(buyNow) {\n");
      out.write("    if (!IS_LOGGED_IN) {\n");
      out.write("        location.href = LOGIN_URL;\n");
      out.write("        return;\n");
      out.write("    }\n");
      out.write("    var qty   = parseInt(document.getElementById('qtyDisplay').value) || 1;\n");
      out.write("    var hatNo = document.getElementById('cartHatNo').dataset.no;\n");
      out.write("    var params = 'hatNo=' + hatNo + '&qty=' + qty + '&buyNow=' + (buyNow ? 'Y' : 'N');\n");
      out.write("\n");
      out.write("    fetch('");
      out.print( ctx );
      out.write("/cart/add', {\n");
      out.write("        method: 'POST',\n");
      out.write("        headers: {'Content-Type': 'application/x-www-form-urlencoded'},\n");
      out.write("        body: params\n");
      out.write("    })\n");
      out.write("    .then(function(r) { return r.json(); })\n");
      out.write("    .then(function(data) {\n");
      out.write("        if (data.result === 'ok') {\n");
      out.write("            if (data.redirect) {\n");
      out.write("                location.href = data.redirect;\n");
      out.write("            } else {\n");
      out.write("                if (typeof incrementCartBadge === 'function') incrementCartBadge();\n");
      out.write("                alert(data.msg || '장바구니에 담겼습니다.');\n");
      out.write("            }\n");
      out.write("        } else {\n");
      out.write("            alert(data.msg || '오류가 발생했습니다.');\n");
      out.write("        }\n");
      out.write("    })\n");
      out.write("    .catch(function() { alert('오류가 발생했습니다.'); });\n");
      out.write("}\n");
      out.write("\n");
      out.write("/* ── 초기화 ── */\n");
      out.write("onQtyChange(1);\n");
      out.write("</script>\n");
      out.write("\n");
      out.write("\n");
      out.write("<footer class=\"site-footer\">\n");
      out.write("\n");
      out.write("    <div class=\"footer__top\">\n");
      out.write("        <div class=\"footer__brand\">\n");
      out.write("            <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/\" class=\"logo\">HATSHOP</a>\n");
      out.write("            <p>모자 그 이상의 태도. 절제된 디자인으로<br>매일의 룩을 완성하는 헤드웨어.</p>\n");
      out.write("            <form class=\"footer__news\" onsubmit=\"return false;\">\n");
      out.write("                <input type=\"email\" placeholder=\"이메일로 신상품 소식 받기\" aria-label=\"이메일\">\n");
      out.write("                <button type=\"submit\">→</button>\n");
      out.write("            </form>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        <div class=\"footer__col\">\n");
      out.write("            <h4>쇼핑</h4>\n");
      out.write("            <ul>\n");
      out.write("                <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/hat/list?category=%EB%B3%BC%EC%BA%A1\">볼캡</a></li>\n");
      out.write("                <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/hat/list?category=%EB%B2%84%ED%82%B7%ED%96%87\">버킷햇</a></li>\n");
      out.write("                <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/hat/list?category=%EB%B2%A0%EB%A0%88%EB%AA%A8\">베레모</a></li>\n");
      out.write("                <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/hat/list?category=%ED%8E%98%EB%8F%84%EB%9D%BC\">페도라</a></li>\n");
      out.write("                <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/hat/list?category=%EC%8A%A4%EB%83%85%EB%B0%B1\">스냅백</a></li>\n");
      out.write("                <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/hat/list\">전체 목록</a></li>\n");
      out.write("            </ul>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        <div class=\"footer__col\">\n");
      out.write("            <h4>회원</h4>\n");
      out.write("            <ul>\n");
      out.write("                <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/member/login.jsp\">로그인</a></li>\n");
      out.write("                <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/member/join.jsp\">회원가입</a></li>\n");
      out.write("                <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/member/mypage.jsp\">마이페이지</a></li>\n");
      out.write("                <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/cart/cartList.jsp\">장바구니</a></li>\n");
      out.write("                <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/order/orderList.jsp\">주문내역</a></li>\n");
      out.write("            </ul>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        <div class=\"footer__col\">\n");
      out.write("            <h4>고객센터</h4>\n");
      out.write("            <ul>\n");
      out.write("                <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/info/delivery.jsp\">배송 안내</a></li>\n");
      out.write("                <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/info/returns.jsp\">교환 / 반품</a></li>\n");
      out.write("                <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/info/size-guide.jsp\">사이즈 가이드</a></li>\n");
      out.write("                <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/board/boardList.jsp\">커뮤니티</a></li>\n");
      out.write("            </ul>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <div class=\"footer__bottom\">\n");
      out.write("        <small>© 2026 HATSHOP. All rights reserved.</small>\n");
      out.write("        <div class=\"legal\">\n");
      out.write("            <a href=\"#\">이용약관</a>\n");
      out.write("            <a href=\"#\">개인정보처리방침</a>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("</footer>\n");
      out.write("\n");
      out.write("<!-- ── AI 고객 상담 챗봇 위젯 ── -->\n");
      out.write("<div id=\"hsChatbot\" class=\"hs-chatbot\">\n");
      out.write("  <button id=\"hsChatToggle\" type=\"button\" class=\"hs-chat-toggle\" aria-label=\"고객 상담 챗봇 열기\">💬</button>\n");
      out.write("  <div id=\"hsChatPanel\" class=\"hs-chat-panel\" hidden>\n");
      out.write("    <div class=\"hs-chat-header\">\n");
      out.write("      <span>HATSHOP 고객 상담</span>\n");
      out.write("      <button id=\"hsChatClose\" type=\"button\" class=\"hs-chat-close\" aria-label=\"닫기\">✕</button>\n");
      out.write("    </div>\n");
      out.write("    <div id=\"hsChatBody\" class=\"hs-chat-body\"></div>\n");
      out.write("    <div id=\"hsChatQuick\" class=\"hs-chat-quick\"></div>\n");
      out.write("    <div class=\"ac-wrap\" style=\"margin:0 12px\">\n");
      out.write("      <div id=\"hsAcDropdown\" class=\"ac-dropdown\"></div>\n");
      out.write("    </div>\n");
      out.write("    <form id=\"hsChatForm\" class=\"hs-chat-form\">\n");
      out.write("      <input type=\"text\" id=\"hsChatInput\" placeholder=\"질문을 입력하세요...\" autocomplete=\"off\">\n");
      out.write("      <button type=\"submit\">전송</button>\n");
      out.write("    </form>\n");
      out.write("  </div>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/js/validation.js\"></script>\n");
      out.write("<script>window.HS_CTX = '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("';</script>\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/js/chatbot.js\"></script>\n");
      out.write("</body>\n");
      out.write("</html>\n");
      out.write('\n');
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fwhen_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:when
    org.apache.taglibs.standard.tag.rt.core.WhenTag _jspx_th_c_005fwhen_005f0 = (org.apache.taglibs.standard.tag.rt.core.WhenTag) _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.WhenTag.class);
    try {
      _jspx_th_c_005fwhen_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fwhen_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
      // /WEB-INF/inc/header.jsp(65,12) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fwhen_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${empty sessionScope.loginUser}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fwhen_005f0 = _jspx_th_c_005fwhen_005f0.doStartTag();
      if (_jspx_eval_c_005fwhen_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("                <a href=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/member/login.jsp\">로그인</a>\n");
          out.write("                <a href=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/member/join.jsp\">회원가입</a>\n");
          out.write("            ");
          int evalDoAfterBody = _jspx_th_c_005fwhen_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fwhen_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } finally {
      _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f0);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fotherwise_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fotherwise_005f0);
      // /WEB-INF/inc/header.jsp(72,16) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.loginUser.grade eq 'ADMIN'}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("                    <a href=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/admin/\">관리자</a>\n");
          out.write("                ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } finally {
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
    }
    return false;
  }
}
