/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.118
 * Generated at: 2026-06-18 04:30:54 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.hat;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.hatshop.util.Logger;
import com.hatshop.db.DBConn;
import org.json.JSONObject;
import org.json.JSONArray;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.List;
import java.util.ArrayList;
import java.util.LinkedHashSet;
import java.util.Set;

public final class suggest_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {


    /* 레벤슈타인 거리(편집거리) — 오타 보정용 */
    private int levenshtein(String a, String b) {
        a = a.toLowerCase(); b = b.toLowerCase();
        int[] dp = new int[b.length() + 1];
        for (int j = 0; j <= b.length(); j++) dp[j] = j;
        for (int i = 1; i <= a.length(); i++) {
            int prev = dp[0];
            dp[0] = i;
            for (int j = 1; j <= b.length(); j++) {
                int temp = dp[j];
                if (a.charAt(i - 1) == b.charAt(j - 1)) {
                    dp[j] = prev;
                } else {
                    dp[j] = 1 + Math.min(prev, Math.min(dp[j], dp[j - 1]));
                }
                prev = temp;
            }
        }
        return dp[b.length()];
    }

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(15);
    _jspx_imports_classes.add("com.hatshop.util.Logger");
    _jspx_imports_classes.add("com.hatshop.db.DBConn");
    _jspx_imports_classes.add("org.json.JSONObject");
    _jspx_imports_classes.add("org.json.JSONArray");
    _jspx_imports_classes.add("java.sql.Connection");
    _jspx_imports_classes.add("java.sql.PreparedStatement");
    _jspx_imports_classes.add("java.sql.ResultSet");
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("java.util.ArrayList");
    _jspx_imports_classes.add("java.util.LinkedHashSet");
    _jspx_imports_classes.add("java.util.Set");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("application/json; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');
      out.write('\n');
      out.write('\n');

    response.setHeader("Cache-Control", "no-store");
    JSONObject resultJson = new JSONObject();
    JSONArray suggestions = new JSONArray();

    String q = request.getParameter("q");
    if (q == null) q = "";
    q = q.trim();

    if (q.isEmpty()) {
        resultJson.put("suggestions", suggestions);
        resultJson.write(response.getWriter());
        return;
    }
    if (q.length() > 50) q = q.substring(0, 50);

    String[] categories = {"볼캡", "버킷햇", "베레모", "페도라", "스냅백"};

    try {
        Connection conn = DBConn.getConnection();
        List<String> hatNames = new ArrayList<>();
        try (PreparedStatement ps = conn.prepareStatement("SELECT DISTINCT hat_name FROM hat");
             ResultSet rs = ps.executeQuery()) {
            while (rs.next()) hatNames.add(rs.getString("hat_name"));
        }

        String qLower = q.toLowerCase();
        Set<String> added = new LinkedHashSet<>();

        /* 1) 카테고리 직접 일치 */
        for (String cat : categories) {
            if (added.size() >= 8) break;
            if (cat.toLowerCase().contains(qLower) && added.add(cat)) {
                JSONObject item = new JSONObject();
                item.put("text", cat);
                item.put("type", "category");
                suggestions.put(item);
            }
        }

        /* 2) 상품명 직접 일치 */
        for (String name : hatNames) {
            if (added.size() >= 8) break;
            if (name.toLowerCase().contains(qLower) && added.add(name)) {
                JSONObject item = new JSONObject();
                item.put("text", name);
                item.put("type", "product");
                suggestions.put(item);
            }
        }

        /* 3) 직접 일치가 부족하면 오타 보정 (레벤슈타인 거리 기반) */
        if (added.size() < 5) {
            int threshold = q.length() <= 2 ? 1 : 2;

            /* 후보 토큰 모음: 카테고리 + 상품명을 공백으로 분리한 단어들 */
            Set<String> tokenVocab = new LinkedHashSet<>();
            for (String cat : categories) tokenVocab.add(cat);
            for (String name : hatNames) {
                for (String tok : name.split("\\s+")) {
                    if (!tok.isEmpty()) tokenVocab.add(tok);
                }
            }

            final String qForSort = q;
            List<String> corrected = new ArrayList<>();
            for (String token : tokenVocab) {
                if (levenshtein(q, token) <= threshold) corrected.add(token);
            }
            /* 거리 짧은 순으로 정렬 */
            corrected.sort((a, b) -> levenshtein(qForSort, a) - levenshtein(qForSort, b));

            for (String token : corrected) {
                if (added.size() >= 8) break;
                boolean isCategory = false;
                for (String cat : categories) if (cat.equals(token)) { isCategory = true; break; }

                if (isCategory) {
                    if (added.add(token)) {
                        JSONObject item = new JSONObject();
                        item.put("text", token);
                        item.put("type", "category");
                        item.put("corrected", true);
                        suggestions.put(item);
                    }
                } else {
                    /* 해당 토큰을 포함하는 상품명 1~2개 제시 */
                    int cnt = 0;
                    for (String name : hatNames) {
                        if (added.size() >= 8 || cnt >= 2) break;
                        if (name.contains(token) && added.add(name)) {
                            JSONObject item = new JSONObject();
                            item.put("text", name);
                            item.put("type", "product");
                            item.put("corrected", true);
                            suggestions.put(item);
                            cnt++;
                        }
                    }
                }
            }
        }

        resultJson.put("suggestions", suggestions);
        resultJson.write(response.getWriter());

    } catch (Exception e) {
        Logger.error(this.getClass(), "상품 자동완성 오류: q=" + q, e);
        response.setStatus(500);
        resultJson.put("suggestions", new JSONArray());
        resultJson.put("error", "자동완성 처리 중 오류가 발생했습니다.");
        resultJson.write(response.getWriter());
    }

      out.write('\n');
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
