/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.118
 * Generated at: 2026-06-19 01:22:43 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.admin;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.hatshop.member.MemberDTO;
import com.hatshop.util.HtmlUtils;
import com.hatshop.util.Logger;
import com.hatshop.db.DBConn;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import com.hatshop.cart.CartDAO;
import com.hatshop.member.MemberDTO;

public final class inquiryDetail_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.LinkedHashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("/WEB-INF/inc/header.jsp", Long.valueOf(1781831986439L));
    _jspx_dependants.put("/WEB-INF/inc/footer.jsp", Long.valueOf(1781756931479L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1781088682000L));
    _jspx_dependants.put("jar:file:/C:/Users/gram14/OneDrive/바탕%20화면/Projact/jsp/hatshop-server/tomcat/webapps/hatshop/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(11);
    _jspx_imports_classes.add("com.hatshop.member.MemberDTO");
    _jspx_imports_classes.add("com.hatshop.util.HtmlUtils");
    _jspx_imports_classes.add("com.hatshop.util.Logger");
    _jspx_imports_classes.add("com.hatshop.db.DBConn");
    _jspx_imports_classes.add("java.sql.Connection");
    _jspx_imports_classes.add("java.sql.PreparedStatement");
    _jspx_imports_classes.add("java.sql.ResultSet");
    _jspx_imports_classes.add("com.hatshop.cart.CartDAO");
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fchoose;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fotherwise;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fchoose = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fotherwise = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fchoose.release();
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fotherwise.release();
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');
      out.write('\n');

    MemberDTO loginUser = (MemberDTO) session.getAttribute("loginUser");
    if (loginUser == null || !loginUser.isAdmin()) {
        response.sendRedirect(request.getContextPath() + "/error/403.jsp"); return;
    }
    String ctx = request.getContextPath();

    int inquiryNo = 0;
    try { inquiryNo = Integer.parseInt(request.getParameter("inquiryNo")); } catch (Exception ignored) {}
    if (inquiryNo <= 0) {
        response.sendRedirect(ctx + "/admin/inquiryList.jsp"); return;
    }

    String flashError = (String) session.getAttribute("flashError");
    session.removeAttribute("flashError");

    String memberId = null, name = null, email = null, title = null, content = null, answer = null, status = null;
    java.sql.Timestamp regDate = null, answerDate = null;
    boolean found = false;

    try {
        Connection conn = DBConn.getConnection();
        String sql = "SELECT member_id, inquiry_name, inquiry_email, inquiry_title, inquiry_content, inquiry_answer, " +
                     "inquiry_status, reg_date, answer_date FROM inquiry WHERE inquiry_no = ?";
        try (PreparedStatement ps = conn.prepareStatement(sql)) {
            ps.setInt(1, inquiryNo);
            try (ResultSet rs = ps.executeQuery()) {
                if (rs.next()) {
                    found = true;
                    memberId = rs.getString("member_id");
                    name = rs.getString("inquiry_name");
                    email = rs.getString("inquiry_email");
                    title = rs.getString("inquiry_title");
                    content = rs.getString("inquiry_content");
                    answer = rs.getString("inquiry_answer");
                    status = rs.getString("inquiry_status");
                    regDate = rs.getTimestamp("reg_date");
                    answerDate = rs.getTimestamp("answer_date");
                }
            }
        }
    } catch (Exception e) {
        Logger.error(this.getClass(), "admin/inquiryDetail.jsp 조회 오류: inquiryNo=" + inquiryNo, e);
    }

    if (!found) {
        session.setAttribute("flashError", "존재하지 않는 문의입니다.");
        response.sendRedirect(ctx + "/admin/inquiryList.jsp");
        return;
    }

      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write('\n');

    String _ctx = request.getContextPath();
    String _uri = request.getRequestURI();
    String _cat = request.getParameter("category");
    if (_cat == null) _cat = "";
    boolean _onHome  = _uri.endsWith("/") || _uri.endsWith("index.jsp") || _uri.equals(_ctx + "/");
    boolean _onBoard = _uri.contains("/board/");
    boolean _onHat   = _uri.contains("/hat/");

    MemberDTO _hdrUser = (MemberDTO) session.getAttribute("loginUser");
    int _cartCount = 0;
    int _unreadInquiryCount = 0;
    if (_hdrUser != null) {
        try { _cartCount = new CartDAO().getCartCount(_hdrUser.getMemberId()); }
        catch (Exception _e) { /* 배지 카운트 실패 시 0으로 유지 */ }
        try {
            java.sql.Connection _conn = com.hatshop.db.DBConn.getConnection();
            try (java.sql.PreparedStatement _ps = _conn.prepareStatement(
                    "SELECT COUNT(*) FROM inquiry WHERE member_id = ? AND inquiry_status IN ('ANSWERED','CLOSED') AND is_read = 0")) {
                _ps.setString(1, _hdrUser.getMemberId());
                try (java.sql.ResultSet _rs = _ps.executeQuery()) {
                    if (_rs.next()) _unreadInquiryCount = _rs.getInt(1);
                }
            }
        } catch (Exception _e) { /* 알림 카운트 실패 시 0으로 유지 */ }
    }

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"ko\">\n");
      out.write("<head>\n");
      out.write("    <meta charset=\"UTF-8\">\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("    <title>HATSHOP — Wear Your Statement</title>\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.print( _ctx );
      out.write("/css/style.css?v=5\">\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.print( _ctx );
      out.write("/css/chatbot.css?v=5\">\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("<header class=\"site-header ");
      out.print( _onHome ? "" : "scrolled" );
      out.write("\" id=\"siteHeader\" data-home=\"");
      out.print( _onHome );
      out.write("\">\n");
      out.write("\n");
      out.write("    <a href=\"");
      out.print( _ctx );
      out.write("/\" class=\"brand\">HATSHOP</a>\n");
      out.write("\n");
      out.write("    <nav class=\"site-nav-primary\" id=\"primaryNav\">\n");
      out.write("        <a href=\"");
      out.print( _ctx );
      out.write("/\"\n");
      out.write("           class=\"");
      out.print( _onHome ? "active" : "" );
      out.write("\">Home</a>\n");
      out.write("        <a href=\"");
      out.print( _ctx );
      out.write("/hat/list?category=%EB%B3%BC%EC%BA%A1\"\n");
      out.write("           class=\"");
      out.print( "볼캡".equals(_cat) ? "active" : "" );
      out.write("\">볼캡</a>\n");
      out.write("        <a href=\"");
      out.print( _ctx );
      out.write("/hat/list?category=%EB%B2%84%ED%82%B7%ED%96%87\"\n");
      out.write("           class=\"");
      out.print( "버킷햇".equals(_cat) ? "active" : "" );
      out.write("\">버킷햇</a>\n");
      out.write("        <a href=\"");
      out.print( _ctx );
      out.write("/hat/list?category=%EB%B2%A0%EB%A0%88%EB%AA%A8\"\n");
      out.write("           class=\"");
      out.print( "베레모".equals(_cat) ? "active" : "" );
      out.write("\">베레모</a>\n");
      out.write("        <a href=\"");
      out.print( _ctx );
      out.write("/hat/list?category=%ED%8E%98%EB%8F%84%EB%9D%BC\"\n");
      out.write("           class=\"");
      out.print( "페도라".equals(_cat) ? "active" : "" );
      out.write("\">페도라</a>\n");
      out.write("        <a href=\"");
      out.print( _ctx );
      out.write("/hat/list?category=%EC%8A%A4%EB%83%85%EB%B0%B1\"\n");
      out.write("           class=\"");
      out.print( "스냅백".equals(_cat) ? "active" : "" );
      out.write("\">스냅백</a>\n");
      out.write("        <a href=\"");
      out.print( _ctx );
      out.write("/board/boardList.jsp\"\n");
      out.write("           class=\"");
      out.print( _onBoard ? "active" : "" );
      out.write("\">커뮤니티</a>\n");
      out.write("    </nav>\n");
      out.write("\n");
      out.write("    <div class=\"header-icons\">\n");
      out.write("        ");
      //  c:choose
      org.apache.taglibs.standard.tag.common.core.ChooseTag _jspx_th_c_005fchoose_005f0 = (org.apache.taglibs.standard.tag.common.core.ChooseTag) _005fjspx_005ftagPool_005fc_005fchoose.get(org.apache.taglibs.standard.tag.common.core.ChooseTag.class);
      try {
        _jspx_th_c_005fchoose_005f0.setPageContext(_jspx_page_context);
        _jspx_th_c_005fchoose_005f0.setParent(null);
        int _jspx_eval_c_005fchoose_005f0 = _jspx_th_c_005fchoose_005f0.doStartTag();
        if (_jspx_eval_c_005fchoose_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\n");
            out.write("            ");
            if (_jspx_meth_c_005fwhen_005f0(_jspx_th_c_005fchoose_005f0, _jspx_page_context))
              return;
            out.write("\n");
            out.write("            ");
            //  c:otherwise
            org.apache.taglibs.standard.tag.common.core.OtherwiseTag _jspx_th_c_005fotherwise_005f0 = (org.apache.taglibs.standard.tag.common.core.OtherwiseTag) _005fjspx_005ftagPool_005fc_005fotherwise.get(org.apache.taglibs.standard.tag.common.core.OtherwiseTag.class);
            try {
              _jspx_th_c_005fotherwise_005f0.setPageContext(_jspx_page_context);
              _jspx_th_c_005fotherwise_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
              int _jspx_eval_c_005fotherwise_005f0 = _jspx_th_c_005fotherwise_005f0.doStartTag();
              if (_jspx_eval_c_005fotherwise_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
                do {
                  out.write("\n");
                  out.write("                <a href=\"");
                  out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
                  out.write("/member/mypage.jsp?tab=inquiries\" style=\"position:relative\">마이페이지");

                    if (_unreadInquiryCount > 0) { 
                  out.write("<span class=\"cart-count\">");
                  out.print( _unreadInquiryCount );
                  out.write("</span>");
 } 
                  out.write("</a>\n");
                  out.write("                ");
                  if (_jspx_meth_c_005fif_005f0(_jspx_th_c_005fotherwise_005f0, _jspx_page_context))
                    return;
                  out.write("\n");
                  out.write("                <a href=\"");
                  out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
                  out.write("/member/logout.jsp\">로그아웃</a>\n");
                  out.write("            ");
                  int evalDoAfterBody = _jspx_th_c_005fotherwise_005f0.doAfterBody();
                  if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
                    break;
                } while (true);
              }
              if (_jspx_th_c_005fotherwise_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
                return;
              }
            } finally {
              _005fjspx_005ftagPool_005fc_005fotherwise.reuse(_jspx_th_c_005fotherwise_005f0);
            }
            out.write("\n");
            out.write("        ");
            int evalDoAfterBody = _jspx_th_c_005fchoose_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fchoose_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return;
        }
      } finally {
        _005fjspx_005ftagPool_005fc_005fchoose.reuse(_jspx_th_c_005fchoose_005f0);
      }
      out.write("\n");
      out.write("        <a href=\"");
      out.print( _ctx );
      out.write("/cart/list\" style=\"position:relative\">\n");
      out.write("            장바구니<span class=\"cart-count\" id=\"cartBadge\"");
      out.print( _cartCount > 0 ? "" : " style=\"display:none\"" );
      out.write('>');
      out.print( _cartCount > 0 ? _cartCount : 0 );
      out.write("</span>\n");
      out.write("        </a>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("</header>\n");
      out.write("\n");
      out.write("<script>\n");
      out.write("(function(){\n");
      out.write("    var h   = document.getElementById('siteHeader');\n");
      out.write("    var isHome = h && h.getAttribute('data-home') === 'true';\n");
      out.write("    function upd(){ h.classList.toggle('scrolled', !isHome || window.scrollY > 50); }\n");
      out.write("    window.addEventListener('scroll', upd, {passive:true});\n");
      out.write("    upd();\n");
      out.write("})();\n");
      out.write("function incrementCartBadge() {\n");
      out.write("    var b = document.getElementById('cartBadge');\n");
      out.write("    if (!b) return;\n");
      out.write("    var n = (parseInt(b.textContent) || 0) + 1;\n");
      out.write("    b.textContent = n;\n");
      out.write("    b.style.display = '';\n");
      out.write("}\n");
      out.write("</script>\n");
      out.write("\n");
      out.write("\n");
      out.write("<style>\n");
      out.write(".admin-section { max-width: 760px; margin: 0 auto; padding: calc(var(--header-h) + 40px) 16px 60px; }\n");
      out.write(".admin-breadcrumb { display: flex; align-items: center; gap: 6px; font-size: .82rem; color: var(--ink-soft); margin-bottom: 16px; }\n");
      out.write(".admin-breadcrumb a:hover { color: var(--accent); }\n");
      out.write(".page-title { font-size: 1.25rem; font-weight: 700; margin-bottom: 20px; }\n");
      out.write(".info-card  { background: var(--bg); border: 1px solid var(--line); border-radius: 4px; padding: 22px 26px; margin-bottom: 18px; }\n");
      out.write(".card-title { font-size: .95rem; font-weight: 700; margin-bottom: 14px; padding-bottom: 10px; border-bottom: 1px solid var(--line); display: flex; justify-content: space-between; align-items: center; }\n");
      out.write(".info-grid  { display: grid; grid-template-columns: 90px 1fr; gap: 9px 16px; font-size: .88rem; margin-bottom: 16px; }\n");
      out.write(".info-key   { color: var(--ink-soft); }\n");
      out.write(".inq-body   { white-space: pre-wrap; word-break: break-word; line-height: 1.6; font-size: .9rem; padding-top: 10px; border-top: 1px solid var(--line); }\n");
      out.write(".ibadge { display: inline-block; padding: 3px 10px; border-radius: 20px; font-size: .75rem; font-weight: 700; border: 1px solid; }\n");
      out.write(".ibadge-open     { background: #fffbef; color: #8a6200; border-color: #e8c84a; }\n");
      out.write(".ibadge-answered { background: #f0faf4; color: var(--green); border-color: #7dcf9e; }\n");
      out.write(".ibadge-closed   { background: var(--ph-a); color: var(--ink-soft); border-color: var(--line); }\n");
      out.write(".answer-box { background: #f9f8f6; border: 1px solid var(--line); border-radius: 4px; padding: 16px 20px; white-space: pre-wrap; word-break: break-word; font-size: .89rem; line-height: 1.6; }\n");
      out.write("textarea#answerContent { width: 100%; background: var(--bg); border: 1px solid var(--line); color: var(--ink); border-radius: 2px; padding: 12px 14px; font-size: .9rem; font-family: inherit; outline: none; resize: vertical; min-height: 140px; box-sizing: border-box; }\n");
      out.write("textarea#answerContent:focus { border-color: var(--ink); }\n");
      out.write(".btn-submit-answer { margin-top: 12px; padding: 11px 24px; background: var(--ink); color: #fff; border: none; border-radius: 2px; font-size: .88rem; font-weight: 700; cursor: pointer; font-family: inherit; }\n");
      out.write(".btn-submit-answer:hover { opacity: .8; }\n");
      out.write(".back-link { color: var(--ink-soft); text-decoration: none; font-size: .85rem; }\n");
      out.write(".back-link:hover { color: var(--ink); }\n");
      out.write(".flash-error { background: #fff5f5; border: 1px solid var(--red); color: var(--red); padding: 11px 16px; border-radius: 4px; margin-bottom: 18px; font-size: .9rem; }\n");
      out.write("</style>\n");
      out.write("\n");
      out.write("<main class=\"admin-section\">\n");
      out.write("  <nav class=\"admin-breadcrumb\">\n");
      out.write("    <a href=\"");
      out.print( ctx );
      out.write("/admin/\">대시보드</a>\n");
      out.write("    <span>›</span>\n");
      out.write("    <a href=\"");
      out.print( ctx );
      out.write("/admin/inquiryList.jsp\">고객센터 문의</a>\n");
      out.write("    <span>›</span>\n");
      out.write("    <span>#");
      out.print( inquiryNo );
      out.write("</span>\n");
      out.write("  </nav>\n");
      out.write("\n");
      out.write("  <h1 class=\"page-title\">문의 상세 #");
      out.print( inquiryNo );
      out.write("</h1>\n");
      out.write("\n");
      out.write("  ");
 if (flashError != null) { 
      out.write("<div class=\"flash-error\">");
      out.print( HtmlUtils.escape(flashError) );
      out.write("</div>");
 } 
      out.write("\n");
      out.write("\n");
      out.write("  <div class=\"info-card\">\n");
      out.write("    <div class=\"card-title\">\n");
      out.write("      <span>문의 내용</span>\n");
      out.write("      ");

        String badgeClass, badgeLabel;
        switch (status) {
            case "ANSWERED": badgeClass = "ibadge-answered"; badgeLabel = "답변완료"; break;
            case "CLOSED":   badgeClass = "ibadge-closed";   badgeLabel = "종료"; break;
            default:         badgeClass = "ibadge-open";     badgeLabel = "대기"; break;
        }
      
      out.write("\n");
      out.write("      <span class=\"ibadge ");
      out.print( badgeClass );
      out.write('"');
      out.write('>');
      out.print( badgeLabel );
      out.write("</span>\n");
      out.write("    </div>\n");
      out.write("    <div class=\"info-grid\">\n");
      out.write("      <span class=\"info-key\">이름</span><span>");
      out.print( HtmlUtils.escape(name) );
      out.write("</span>\n");
      out.write("      <span class=\"info-key\">이메일</span><span>");
      out.print( HtmlUtils.escape(email) );
      out.write("</span>\n");
      out.write("      <span class=\"info-key\">회원ID</span><span>");
      out.print( memberId != null ? HtmlUtils.escape(memberId) : "비회원" );
      out.write("</span>\n");
      out.write("      <span class=\"info-key\">제목</span><span>");
      out.print( HtmlUtils.escape(title) );
      out.write("</span>\n");
      out.write("      <span class=\"info-key\">접수일</span><span>");
      out.print( regDate != null ? regDate.toString().substring(0,16) : "" );
      out.write("</span>\n");
      out.write("    </div>\n");
      out.write("    <div class=\"inq-body\">");
      out.print( HtmlUtils.escape(content) );
      out.write("</div>\n");
      out.write("  </div>\n");
      out.write("\n");
      out.write("  ");
 if (answer != null) { 
      out.write("\n");
      out.write("  <div class=\"info-card\">\n");
      out.write("    <div class=\"card-title\">\n");
      out.write("      <span>관리자 답변</span>\n");
      out.write("      <span style=\"font-size:.78rem;color:var(--ink-soft);font-weight:400\">");
      out.print( answerDate != null ? answerDate.toString().substring(0,16) : "" );
      out.write("</span>\n");
      out.write("    </div>\n");
      out.write("    <div class=\"answer-box\">");
      out.print( HtmlUtils.escape(answer) );
      out.write("</div>\n");
      out.write("  </div>\n");
      out.write("  ");
 } 
      out.write("\n");
      out.write("\n");
      out.write("  <div class=\"info-card\">\n");
      out.write("    <div class=\"card-title\"><span>");
      out.print( answer != null ? "답변 수정" : "답변 작성" );
      out.write("</span></div>\n");
      out.write("    <form method=\"POST\" action=\"");
      out.print( ctx );
      out.write("/admin/inquiryAnswerProc.jsp\">\n");
      out.write("      <input type=\"hidden\" name=\"inquiryNo\" value=\"");
      out.print( inquiryNo );
      out.write("\">\n");
      out.write("      <textarea id=\"answerContent\" name=\"answerContent\" maxlength=\"3000\" placeholder=\"답변 내용을 입력하세요.\">");
      out.print( answer != null ? HtmlUtils.escape(answer) : "" );
      out.write("</textarea>\n");
      out.write("      <div style=\"display:flex;gap:8px;flex-wrap:wrap\">\n");
      out.write("        <button type=\"submit\" class=\"btn-submit-answer\" onclick=\"return confirm('답변을 등록하시겠습니까?')\">");
      out.print( answer != null ? "답변 수정" : "답변 등록" );
      out.write("</button>\n");
      out.write("        ");
 if (!"CLOSED".equals(status)) { 
      out.write("\n");
      out.write("        <button type=\"submit\" name=\"closeTicket\" value=\"1\" class=\"btn-submit-answer\" style=\"background:var(--ink-soft)\" onclick=\"return confirm('이 문의를 종료 처리하시겠습니까?')\">답변 후 종료 처리</button>\n");
      out.write("        ");
 } 
      out.write("\n");
      out.write("      </div>\n");
      out.write("    </form>\n");
      out.write("  </div>\n");
      out.write("\n");
      out.write("  <a href=\"");
      out.print( ctx );
      out.write("/admin/inquiryList.jsp\" class=\"back-link\">← 목록으로</a>\n");
      out.write("</main>\n");
      out.write("\n");
      out.write("\n");
      out.write("<footer class=\"site-footer\">\n");
      out.write("\n");
      out.write("    <div class=\"footer__top\">\n");
      out.write("        <div class=\"footer__brand\">\n");
      out.write("            <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/\" class=\"logo\">HATSHOP</a>\n");
      out.write("            <p>모자 그 이상의 태도. 절제된 디자인으로<br>매일의 룩을 완성하는 헤드웨어.</p>\n");
      out.write("            <form class=\"footer__news\" onsubmit=\"return false;\">\n");
      out.write("                <input type=\"email\" placeholder=\"이메일로 신상품 소식 받기\" aria-label=\"이메일\">\n");
      out.write("                <button type=\"submit\">→</button>\n");
      out.write("            </form>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        <div class=\"footer__col\">\n");
      out.write("            <h4>쇼핑</h4>\n");
      out.write("            <ul>\n");
      out.write("                <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/hat/list?category=%EB%B3%BC%EC%BA%A1\">볼캡</a></li>\n");
      out.write("                <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/hat/list?category=%EB%B2%84%ED%82%B7%ED%96%87\">버킷햇</a></li>\n");
      out.write("                <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/hat/list?category=%EB%B2%A0%EB%A0%88%EB%AA%A8\">베레모</a></li>\n");
      out.write("                <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/hat/list?category=%ED%8E%98%EB%8F%84%EB%9D%BC\">페도라</a></li>\n");
      out.write("                <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/hat/list?category=%EC%8A%A4%EB%83%85%EB%B0%B1\">스냅백</a></li>\n");
      out.write("                <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/hat/list\">전체 목록</a></li>\n");
      out.write("            </ul>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        <div class=\"footer__col\">\n");
      out.write("            <h4>회원</h4>\n");
      out.write("            <ul>\n");
      out.write("                <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/member/login.jsp\">로그인</a></li>\n");
      out.write("                <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/member/join.jsp\">회원가입</a></li>\n");
      out.write("                <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/member/mypage.jsp\">마이페이지</a></li>\n");
      out.write("                <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/cart/cartList.jsp\">장바구니</a></li>\n");
      out.write("                <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/order/orderList.jsp\">주문내역</a></li>\n");
      out.write("            </ul>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        <div class=\"footer__col\">\n");
      out.write("            <h4>고객센터</h4>\n");
      out.write("            <ul>\n");
      out.write("                <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/info/delivery.jsp\">배송 안내</a></li>\n");
      out.write("                <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/info/returns.jsp\">교환 / 반품</a></li>\n");
      out.write("                <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/info/size-guide.jsp\">사이즈 가이드</a></li>\n");
      out.write("                <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/board/boardList.jsp\">커뮤니티</a></li>\n");
      out.write("            </ul>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <div class=\"footer__bottom\">\n");
      out.write("        <small>© 2026 HATSHOP. All rights reserved.</small>\n");
      out.write("        <div class=\"legal\">\n");
      out.write("            <a href=\"#\">이용약관</a>\n");
      out.write("            <a href=\"#\">개인정보처리방침</a>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("</footer>\n");
      out.write("\n");
      out.write("<!-- ── AI 고객 상담 챗봇 위젯 ── -->\n");
      out.write("<div id=\"hsChatbot\" class=\"hs-chatbot\">\n");
      out.write("  <button id=\"hsChatToggle\" type=\"button\" class=\"hs-chat-toggle\" aria-label=\"고객 상담 챗봇 열기\">💬</button>\n");
      out.write("  <div id=\"hsChatPanel\" class=\"hs-chat-panel\" hidden>\n");
      out.write("    <div class=\"hs-chat-header\">\n");
      out.write("      <span>HATSHOP 고객 상담</span>\n");
      out.write("      <button id=\"hsChatClose\" type=\"button\" class=\"hs-chat-close\" aria-label=\"닫기\">✕</button>\n");
      out.write("    </div>\n");
      out.write("    <div id=\"hsChatBody\" class=\"hs-chat-body\"></div>\n");
      out.write("    <div id=\"hsChatQuick\" class=\"hs-chat-quick\"></div>\n");
      out.write("    <div class=\"ac-wrap\" style=\"margin:0 12px\">\n");
      out.write("      <div id=\"hsAcDropdown\" class=\"ac-dropdown\"></div>\n");
      out.write("    </div>\n");
      out.write("    <form id=\"hsChatForm\" class=\"hs-chat-form\">\n");
      out.write("      <input type=\"text\" id=\"hsChatInput\" placeholder=\"질문을 입력하세요...\" autocomplete=\"off\">\n");
      out.write("      <button type=\"submit\">전송</button>\n");
      out.write("    </form>\n");
      out.write("  </div>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/js/validation.js\"></script>\n");
      out.write("<script>window.HS_CTX = '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("';</script>\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/js/chatbot.js\"></script>\n");
      out.write("</body>\n");
      out.write("</html>\n");
      out.write('\n');
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fwhen_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:when
    org.apache.taglibs.standard.tag.rt.core.WhenTag _jspx_th_c_005fwhen_005f0 = (org.apache.taglibs.standard.tag.rt.core.WhenTag) _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.WhenTag.class);
    try {
      _jspx_th_c_005fwhen_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fwhen_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
      // /WEB-INF/inc/header.jsp(65,12) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fwhen_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${empty sessionScope.loginUser}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fwhen_005f0 = _jspx_th_c_005fwhen_005f0.doStartTag();
      if (_jspx_eval_c_005fwhen_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("                <a href=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/member/login.jsp\">로그인</a>\n");
          out.write("                <a href=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/member/join.jsp\">회원가입</a>\n");
          out.write("            ");
          int evalDoAfterBody = _jspx_th_c_005fwhen_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fwhen_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } finally {
      _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f0);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fotherwise_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fotherwise_005f0);
      // /WEB-INF/inc/header.jsp(72,16) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.loginUser.grade eq 'ADMIN'}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("                    <a href=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/admin/\">관리자</a>\n");
          out.write("                ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } finally {
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
    }
    return false;
  }
}
