/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.118
 * Generated at: 2026-06-19 01:23:33 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.admin;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.hatshop.member.MemberDTO;
import com.hatshop.util.HtmlUtils;
import com.hatshop.util.Logger;
import com.hatshop.db.DBConn;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.List;
import java.util.ArrayList;
import com.hatshop.cart.CartDAO;
import com.hatshop.member.MemberDTO;

public final class refundList_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.LinkedHashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("/WEB-INF/inc/header.jsp", Long.valueOf(1781831986439L));
    _jspx_dependants.put("/WEB-INF/inc/footer.jsp", Long.valueOf(1781756931479L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1781088682000L));
    _jspx_dependants.put("jar:file:/C:/Users/gram14/OneDrive/바탕%20화면/Projact/jsp/hatshop-server/tomcat/webapps/hatshop/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(14);
    _jspx_imports_classes.add("com.hatshop.member.MemberDTO");
    _jspx_imports_classes.add("com.hatshop.util.HtmlUtils");
    _jspx_imports_classes.add("com.hatshop.util.Logger");
    _jspx_imports_classes.add("com.hatshop.db.DBConn");
    _jspx_imports_classes.add("java.sql.Connection");
    _jspx_imports_classes.add("java.sql.PreparedStatement");
    _jspx_imports_classes.add("java.sql.ResultSet");
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("java.util.ArrayList");
    _jspx_imports_classes.add("com.hatshop.cart.CartDAO");
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fchoose;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fotherwise;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fchoose = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fotherwise = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fchoose.release();
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fotherwise.release();
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');
      out.write('\n');

    MemberDTO loginUser = (MemberDTO) session.getAttribute("loginUser");
    if (loginUser == null || !loginUser.isAdmin()) {
        response.sendRedirect(request.getContextPath() + "/error/403.jsp"); return;
    }
    String ctx = request.getContextPath();

    String flashSuccess = (String) session.getAttribute("flashSuccess");
    String flashError   = (String) session.getAttribute("flashError");
    session.removeAttribute("flashSuccess");
    session.removeAttribute("flashError");

    String filter = request.getParameter("status");
    if (filter == null) filter = "";

    java.util.Map<String,String> reasonLabels = new java.util.HashMap<>();
    reasonLabels.put("CHANGE_MIND", "단순 변심");
    reasonLabels.put("DEFECTIVE", "상품 불량/하자");
    reasonLabels.put("WRONG_ITEM", "오배송");
    reasonLabels.put("SIZE_COLOR", "사이즈/색상 불일치");
    reasonLabels.put("LATE_DELIVERY", "배송 지연");
    reasonLabels.put("OTHER", "기타");

    List<Object[]> refunds = new ArrayList<>();
    try {
        Connection conn = DBConn.getConnection();
        StringBuilder sql = new StringBuilder(
            "SELECT r.refund_no, r.order_no, r.member_id, r.reason_code, r.reason_detail, r.refund_status, " +
            "r.request_date, r.processed_date, o.order_total, o.order_status " +
            "FROM refund r JOIN orders o ON r.order_no = o.order_no ");
        if (!filter.isEmpty()) sql.append("WHERE r.refund_status = ? ");
        sql.append("ORDER BY r.refund_no DESC");

        try (PreparedStatement ps = conn.prepareStatement(sql.toString())) {
            if (!filter.isEmpty()) ps.setString(1, filter);
            try (ResultSet rs = ps.executeQuery()) {
                while (rs.next()) {
                    refunds.add(new Object[]{
                        rs.getInt("refund_no"), rs.getInt("order_no"), rs.getString("member_id"),
                        rs.getString("reason_code"), rs.getString("reason_detail"), rs.getString("refund_status"),
                        rs.getTimestamp("request_date"), rs.getTimestamp("processed_date"),
                        rs.getInt("order_total"), rs.getString("order_status")
                    });
                }
            }
        }
    } catch (Exception e) {
        Logger.error(this.getClass(), "admin/refundList.jsp 조회 오류", e);
    }

      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write('\n');

    String _ctx = request.getContextPath();
    String _uri = request.getRequestURI();
    String _cat = request.getParameter("category");
    if (_cat == null) _cat = "";
    boolean _onHome  = _uri.endsWith("/") || _uri.endsWith("index.jsp") || _uri.equals(_ctx + "/");
    boolean _onBoard = _uri.contains("/board/");
    boolean _onHat   = _uri.contains("/hat/");

    MemberDTO _hdrUser = (MemberDTO) session.getAttribute("loginUser");
    int _cartCount = 0;
    int _unreadInquiryCount = 0;
    if (_hdrUser != null) {
        try { _cartCount = new CartDAO().getCartCount(_hdrUser.getMemberId()); }
        catch (Exception _e) { /* 배지 카운트 실패 시 0으로 유지 */ }
        try {
            java.sql.Connection _conn = com.hatshop.db.DBConn.getConnection();
            try (java.sql.PreparedStatement _ps = _conn.prepareStatement(
                    "SELECT COUNT(*) FROM inquiry WHERE member_id = ? AND inquiry_status IN ('ANSWERED','CLOSED') AND is_read = 0")) {
                _ps.setString(1, _hdrUser.getMemberId());
                try (java.sql.ResultSet _rs = _ps.executeQuery()) {
                    if (_rs.next()) _unreadInquiryCount = _rs.getInt(1);
                }
            }
        } catch (Exception _e) { /* 알림 카운트 실패 시 0으로 유지 */ }
    }

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"ko\">\n");
      out.write("<head>\n");
      out.write("    <meta charset=\"UTF-8\">\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("    <title>HATSHOP — Wear Your Statement</title>\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.print( _ctx );
      out.write("/css/style.css?v=5\">\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.print( _ctx );
      out.write("/css/chatbot.css?v=5\">\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("<header class=\"site-header ");
      out.print( _onHome ? "" : "scrolled" );
      out.write("\" id=\"siteHeader\" data-home=\"");
      out.print( _onHome );
      out.write("\">\n");
      out.write("\n");
      out.write("    <a href=\"");
      out.print( _ctx );
      out.write("/\" class=\"brand\">HATSHOP</a>\n");
      out.write("\n");
      out.write("    <nav class=\"site-nav-primary\" id=\"primaryNav\">\n");
      out.write("        <a href=\"");
      out.print( _ctx );
      out.write("/\"\n");
      out.write("           class=\"");
      out.print( _onHome ? "active" : "" );
      out.write("\">Home</a>\n");
      out.write("        <a href=\"");
      out.print( _ctx );
      out.write("/hat/list?category=%EB%B3%BC%EC%BA%A1\"\n");
      out.write("           class=\"");
      out.print( "볼캡".equals(_cat) ? "active" : "" );
      out.write("\">볼캡</a>\n");
      out.write("        <a href=\"");
      out.print( _ctx );
      out.write("/hat/list?category=%EB%B2%84%ED%82%B7%ED%96%87\"\n");
      out.write("           class=\"");
      out.print( "버킷햇".equals(_cat) ? "active" : "" );
      out.write("\">버킷햇</a>\n");
      out.write("        <a href=\"");
      out.print( _ctx );
      out.write("/hat/list?category=%EB%B2%A0%EB%A0%88%EB%AA%A8\"\n");
      out.write("           class=\"");
      out.print( "베레모".equals(_cat) ? "active" : "" );
      out.write("\">베레모</a>\n");
      out.write("        <a href=\"");
      out.print( _ctx );
      out.write("/hat/list?category=%ED%8E%98%EB%8F%84%EB%9D%BC\"\n");
      out.write("           class=\"");
      out.print( "페도라".equals(_cat) ? "active" : "" );
      out.write("\">페도라</a>\n");
      out.write("        <a href=\"");
      out.print( _ctx );
      out.write("/hat/list?category=%EC%8A%A4%EB%83%85%EB%B0%B1\"\n");
      out.write("           class=\"");
      out.print( "스냅백".equals(_cat) ? "active" : "" );
      out.write("\">스냅백</a>\n");
      out.write("        <a href=\"");
      out.print( _ctx );
      out.write("/board/boardList.jsp\"\n");
      out.write("           class=\"");
      out.print( _onBoard ? "active" : "" );
      out.write("\">커뮤니티</a>\n");
      out.write("    </nav>\n");
      out.write("\n");
      out.write("    <div class=\"header-icons\">\n");
      out.write("        ");
      //  c:choose
      org.apache.taglibs.standard.tag.common.core.ChooseTag _jspx_th_c_005fchoose_005f0 = (org.apache.taglibs.standard.tag.common.core.ChooseTag) _005fjspx_005ftagPool_005fc_005fchoose.get(org.apache.taglibs.standard.tag.common.core.ChooseTag.class);
      try {
        _jspx_th_c_005fchoose_005f0.setPageContext(_jspx_page_context);
        _jspx_th_c_005fchoose_005f0.setParent(null);
        int _jspx_eval_c_005fchoose_005f0 = _jspx_th_c_005fchoose_005f0.doStartTag();
        if (_jspx_eval_c_005fchoose_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\n");
            out.write("            ");
            if (_jspx_meth_c_005fwhen_005f0(_jspx_th_c_005fchoose_005f0, _jspx_page_context))
              return;
            out.write("\n");
            out.write("            ");
            //  c:otherwise
            org.apache.taglibs.standard.tag.common.core.OtherwiseTag _jspx_th_c_005fotherwise_005f0 = (org.apache.taglibs.standard.tag.common.core.OtherwiseTag) _005fjspx_005ftagPool_005fc_005fotherwise.get(org.apache.taglibs.standard.tag.common.core.OtherwiseTag.class);
            try {
              _jspx_th_c_005fotherwise_005f0.setPageContext(_jspx_page_context);
              _jspx_th_c_005fotherwise_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
              int _jspx_eval_c_005fotherwise_005f0 = _jspx_th_c_005fotherwise_005f0.doStartTag();
              if (_jspx_eval_c_005fotherwise_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
                do {
                  out.write("\n");
                  out.write("                <a href=\"");
                  out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
                  out.write("/member/mypage.jsp?tab=inquiries\" style=\"position:relative\">마이페이지");

                    if (_unreadInquiryCount > 0) { 
                  out.write("<span class=\"cart-count\">");
                  out.print( _unreadInquiryCount );
                  out.write("</span>");
 } 
                  out.write("</a>\n");
                  out.write("                ");
                  if (_jspx_meth_c_005fif_005f0(_jspx_th_c_005fotherwise_005f0, _jspx_page_context))
                    return;
                  out.write("\n");
                  out.write("                <a href=\"");
                  out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
                  out.write("/member/logout.jsp\">로그아웃</a>\n");
                  out.write("            ");
                  int evalDoAfterBody = _jspx_th_c_005fotherwise_005f0.doAfterBody();
                  if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
                    break;
                } while (true);
              }
              if (_jspx_th_c_005fotherwise_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
                return;
              }
            } finally {
              _005fjspx_005ftagPool_005fc_005fotherwise.reuse(_jspx_th_c_005fotherwise_005f0);
            }
            out.write("\n");
            out.write("        ");
            int evalDoAfterBody = _jspx_th_c_005fchoose_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fchoose_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return;
        }
      } finally {
        _005fjspx_005ftagPool_005fc_005fchoose.reuse(_jspx_th_c_005fchoose_005f0);
      }
      out.write("\n");
      out.write("        <a href=\"");
      out.print( _ctx );
      out.write("/cart/list\" style=\"position:relative\">\n");
      out.write("            장바구니<span class=\"cart-count\" id=\"cartBadge\"");
      out.print( _cartCount > 0 ? "" : " style=\"display:none\"" );
      out.write('>');
      out.print( _cartCount > 0 ? _cartCount : 0 );
      out.write("</span>\n");
      out.write("        </a>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("</header>\n");
      out.write("\n");
      out.write("<script>\n");
      out.write("(function(){\n");
      out.write("    var h   = document.getElementById('siteHeader');\n");
      out.write("    var isHome = h && h.getAttribute('data-home') === 'true';\n");
      out.write("    function upd(){ h.classList.toggle('scrolled', !isHome || window.scrollY > 50); }\n");
      out.write("    window.addEventListener('scroll', upd, {passive:true});\n");
      out.write("    upd();\n");
      out.write("})();\n");
      out.write("function incrementCartBadge() {\n");
      out.write("    var b = document.getElementById('cartBadge');\n");
      out.write("    if (!b) return;\n");
      out.write("    var n = (parseInt(b.textContent) || 0) + 1;\n");
      out.write("    b.textContent = n;\n");
      out.write("    b.style.display = '';\n");
      out.write("}\n");
      out.write("</script>\n");
      out.write("\n");
      out.write("\n");
      out.write("<style>\n");
      out.write(".admin-section { max-width: 1200px; margin: 0 auto; padding: calc(var(--header-h) + 40px) 16px 60px; }\n");
      out.write(".admin-page-head { display: flex; align-items: center; justify-content: space-between; margin-bottom: 20px; flex-wrap: wrap; gap: 12px; }\n");
      out.write(".admin-page-head h1 { font-size: 1.25rem; font-weight: 700; display: flex; align-items: center; gap: 8px; }\n");
      out.write(".admin-breadcrumb { display: flex; align-items: center; gap: 6px; font-size: .82rem; color: var(--ink-soft); margin-bottom: 16px; }\n");
      out.write(".admin-breadcrumb a:hover { color: var(--accent); }\n");
      out.write(".filter-tabs { display: flex; gap: 6px; margin-bottom: 18px; flex-wrap: wrap; }\n");
      out.write(".filter-tab { padding: 7px 16px; border: 1px solid var(--line); border-radius: 20px; font-size: .82rem; text-decoration: none; color: var(--ink-soft); transition: all .15s; }\n");
      out.write(".filter-tab:hover { border-color: var(--ink); color: var(--ink); }\n");
      out.write(".filter-tab.active { background: var(--ink); border-color: var(--ink); color: #fff; font-weight: 700; }\n");
      out.write("\n");
      out.write(".data-table { width: 100%; border-collapse: collapse; font-size: .87rem; }\n");
      out.write(".data-table th { text-align: left; padding: 11px 14px; background: var(--ph-a); color: var(--ink-soft); font-weight: 600; border-bottom: 1px solid var(--line); font-size: .8rem; white-space: nowrap; }\n");
      out.write(".data-table td { padding: 11px 14px; border-bottom: 1px solid var(--line); vertical-align: top; }\n");
      out.write(".data-table tr:last-child td { border-bottom: none; }\n");
      out.write(".data-table tbody tr:hover td { background: var(--bg-sub); }\n");
      out.write(".table-card { border: 1px solid var(--line); border-radius: 4px; overflow: hidden; }\n");
      out.write(".table-summary { padding: 10px 16px; background: var(--bg-sub); border-top: 1px solid var(--line); font-size: .82rem; color: var(--ink-soft); }\n");
      out.write(".reason-detail-txt { max-width: 240px; white-space: pre-wrap; word-break: break-word; color: var(--ink-soft); font-size: .82rem; }\n");
      out.write("\n");
      out.write(".rbadge { display: inline-block; padding: 3px 10px; border-radius: 20px; font-size: .75rem; font-weight: 700; border: 1px solid; white-space: nowrap; }\n");
      out.write(".rbadge-requested { background: #fffbef; color: #8a6200; border-color: #e8c84a; }\n");
      out.write(".rbadge-approved  { background: #eff8ff; color: #1a6fb3; border-color: #96cff5; }\n");
      out.write(".rbadge-rejected  { background: #fff5f5; color: var(--red); border-color: #f5a0a0; }\n");
      out.write(".rbadge-completed { background: #f0faf4; color: var(--green); border-color: #7dcf9e; }\n");
      out.write("\n");
      out.write(".refund-actions { display: flex; gap: 6px; flex-wrap: wrap; }\n");
      out.write(".refund-actions form { display: inline; }\n");
      out.write(".btn-approve { padding: 6px 12px; background: var(--ink); color: #fff; border: none; border-radius: 2px; font-size: .78rem; cursor: pointer; font-family: inherit; }\n");
      out.write(".btn-approve:hover { opacity: .8; }\n");
      out.write(".btn-reject { padding: 6px 12px; background: transparent; color: var(--red); border: 1px solid var(--red); border-radius: 2px; font-size: .78rem; cursor: pointer; font-family: inherit; }\n");
      out.write(".btn-reject:hover { background: #fff5f5; }\n");
      out.write(".btn-complete { padding: 6px 12px; background: var(--green); color: #fff; border: none; border-radius: 2px; font-size: .78rem; cursor: pointer; font-family: inherit; }\n");
      out.write(".btn-complete:hover { opacity: .8; }\n");
      out.write("</style>\n");
      out.write("\n");
      out.write("<main class=\"admin-section\">\n");
      out.write("\n");
      out.write("  <nav class=\"admin-breadcrumb\">\n");
      out.write("    <a href=\"");
      out.print( ctx );
      out.write("/admin/\">대시보드</a>\n");
      out.write("    <span>›</span>\n");
      out.write("    <span>환불 관리</span>\n");
      out.write("  </nav>\n");
      out.write("\n");
      out.write("  <div class=\"admin-page-head\">\n");
      out.write("    <h1>\n");
      out.write("      <svg class=\"icon-svg\" viewBox=\"0 0 24 24\"><polyline points=\"9 14 4 9 9 4\"/><path d=\"M20 20v-7a4 4 0 0 0-4-4H4\"/></svg>\n");
      out.write("      환불 관리\n");
      out.write("      <span style=\"font-size:.85rem;color:var(--ink-soft);font-weight:400\"> (총 ");
      out.print( refunds.size() );
      out.write("건)</span>\n");
      out.write("    </h1>\n");
      out.write("  </div>\n");
      out.write("\n");
      out.write("  ");
 if (flashSuccess != null) { 
      out.write("<div class=\"alert alert-success\" style=\"margin-bottom:16px\">");
      out.print( HtmlUtils.escape(flashSuccess) );
      out.write("</div>");
 } 
      out.write('\n');
      out.write(' ');
      out.write(' ');
 if (flashError   != null) { 
      out.write("<div class=\"alert alert-error\"   style=\"margin-bottom:16px\">");
      out.print( HtmlUtils.escape(flashError)   );
      out.write("</div>");
 } 
      out.write("\n");
      out.write("\n");
      out.write("  <nav class=\"filter-tabs\">\n");
      out.write("    <a href=\"");
      out.print( ctx );
      out.write("/admin/refundList.jsp\" class=\"filter-tab ");
      out.print( filter.isEmpty() ? "active" : "" );
      out.write("\">전체</a>\n");
      out.write("    <a href=\"");
      out.print( ctx );
      out.write("/admin/refundList.jsp?status=REQUESTED\" class=\"filter-tab ");
      out.print( "REQUESTED".equals(filter) ? "active" : "" );
      out.write("\">신청됨</a>\n");
      out.write("    <a href=\"");
      out.print( ctx );
      out.write("/admin/refundList.jsp?status=APPROVED\"  class=\"filter-tab ");
      out.print( "APPROVED".equals(filter)  ? "active" : "" );
      out.write("\">승인됨</a>\n");
      out.write("    <a href=\"");
      out.print( ctx );
      out.write("/admin/refundList.jsp?status=COMPLETED\" class=\"filter-tab ");
      out.print( "COMPLETED".equals(filter) ? "active" : "" );
      out.write("\">완료됨</a>\n");
      out.write("    <a href=\"");
      out.print( ctx );
      out.write("/admin/refundList.jsp?status=REJECTED\"  class=\"filter-tab ");
      out.print( "REJECTED".equals(filter)  ? "active" : "" );
      out.write("\">거부됨</a>\n");
      out.write("  </nav>\n");
      out.write("\n");
      out.write("  <div class=\"table-card\">\n");
      out.write("    ");
 if (refunds.isEmpty()) { 
      out.write("\n");
      out.write("    <div style=\"text-align:center;padding:60px 20px;color:var(--ink-soft)\">환불 신청 내역이 없습니다.</div>\n");
      out.write("    ");
 } else { 
      out.write("\n");
      out.write("    <table class=\"data-table\">\n");
      out.write("      <thead>\n");
      out.write("        <tr>\n");
      out.write("          <th style=\"width:50px\">No.</th>\n");
      out.write("          <th style=\"width:70px\">주문번호</th>\n");
      out.write("          <th style=\"width:90px\">회원ID</th>\n");
      out.write("          <th style=\"width:110px\">사유</th>\n");
      out.write("          <th>상세 설명</th>\n");
      out.write("          <th style=\"width:100px;text-align:right\">결제금액</th>\n");
      out.write("          <th style=\"width:130px\">신청일</th>\n");
      out.write("          <th style=\"width:90px;text-align:center\">상태</th>\n");
      out.write("          <th style=\"width:160px\">처리</th>\n");
      out.write("        </tr>\n");
      out.write("      </thead>\n");
      out.write("      <tbody>\n");
      out.write("        ");
 for (Object[] r : refunds) {
             int refundNo = (Integer) r[0];
             int orderNo  = (Integer) r[1];
             String memberId = (String) r[2];
             String reasonCode = (String) r[3];
             String reasonDetail = (String) r[4];
             String status = (String) r[5];
             java.sql.Timestamp reqDate = (java.sql.Timestamp) r[6];
             int orderTotal = (Integer) r[8];

             String statusLabel, statusClass;
             switch (status) {
                 case "APPROVED":  statusLabel = "승인됨"; statusClass = "rbadge-approved"; break;
                 case "REJECTED":  statusLabel = "거부됨"; statusClass = "rbadge-rejected"; break;
                 case "COMPLETED": statusLabel = "완료됨"; statusClass = "rbadge-completed"; break;
                 default:          statusLabel = "신청됨"; statusClass = "rbadge-requested"; break;
             }
        
      out.write("\n");
      out.write("        <tr>\n");
      out.write("          <td style=\"color:var(--ink-soft)\">");
      out.print( refundNo );
      out.write("</td>\n");
      out.write("          <td style=\"font-weight:600\">\n");
      out.write("            <a href=\"");
      out.print( ctx );
      out.write("/order/detail?orderNo=");
      out.print( orderNo );
      out.write("\" target=\"_blank\" style=\"color:inherit\">#");
      out.print( orderNo );
      out.write("</a>\n");
      out.write("          </td>\n");
      out.write("          <td>");
      out.print( HtmlUtils.escape(memberId) );
      out.write("</td>\n");
      out.write("          <td>");
      out.print( HtmlUtils.escape(reasonLabels.getOrDefault(reasonCode, reasonCode)) );
      out.write("</td>\n");
      out.write("          <td class=\"reason-detail-txt\">");
      out.print( reasonDetail != null ? HtmlUtils.escape(reasonDetail) : "-" );
      out.write("</td>\n");
      out.write("          <td style=\"text-align:right\">");
      out.print( String.format("%,d", orderTotal) );
      out.write("원</td>\n");
      out.write("          <td style=\"font-size:.8rem;color:var(--ink-soft)\">");
      out.print( reqDate != null ? reqDate.toString().substring(0,16) : "" );
      out.write("</td>\n");
      out.write("          <td style=\"text-align:center\"><span class=\"rbadge ");
      out.print( statusClass );
      out.write('"');
      out.write('>');
      out.print( statusLabel );
      out.write("</span></td>\n");
      out.write("          <td>\n");
      out.write("            <div class=\"refund-actions\">\n");
      out.write("              ");
 if ("REQUESTED".equals(status)) { 
      out.write("\n");
      out.write("              <form method=\"POST\" action=\"");
      out.print( ctx );
      out.write("/admin/refundProcess.jsp\" onsubmit=\"return confirm('이 환불 신청을 승인하시겠습니까?')\">\n");
      out.write("                <input type=\"hidden\" name=\"refundNo\" value=\"");
      out.print( refundNo );
      out.write("\">\n");
      out.write("                <input type=\"hidden\" name=\"action\" value=\"approve\">\n");
      out.write("                <button type=\"submit\" class=\"btn-approve\">승인</button>\n");
      out.write("              </form>\n");
      out.write("              <form method=\"POST\" action=\"");
      out.print( ctx );
      out.write("/admin/refundProcess.jsp\" onsubmit=\"return confirm('이 환불 신청을 거부하시겠습니까?')\">\n");
      out.write("                <input type=\"hidden\" name=\"refundNo\" value=\"");
      out.print( refundNo );
      out.write("\">\n");
      out.write("                <input type=\"hidden\" name=\"action\" value=\"reject\">\n");
      out.write("                <button type=\"submit\" class=\"btn-reject\">거부</button>\n");
      out.write("              </form>\n");
      out.write("              ");
 } else if ("APPROVED".equals(status)) { 
      out.write("\n");
      out.write("              <form method=\"POST\" action=\"");
      out.print( ctx );
      out.write("/admin/refundProcess.jsp\" onsubmit=\"return confirm('환불금 지급을 완료 처리하시겠습니까?\\n재고가 복구되고 주문이 취소 처리됩니다.')\">\n");
      out.write("                <input type=\"hidden\" name=\"refundNo\" value=\"");
      out.print( refundNo );
      out.write("\">\n");
      out.write("                <input type=\"hidden\" name=\"action\" value=\"complete\">\n");
      out.write("                <button type=\"submit\" class=\"btn-complete\">완료 처리</button>\n");
      out.write("              </form>\n");
      out.write("              ");
 } else { 
      out.write("\n");
      out.write("              <span style=\"color:var(--ink-soft);font-size:.8rem\">-</span>\n");
      out.write("              ");
 } 
      out.write("\n");
      out.write("            </div>\n");
      out.write("          </td>\n");
      out.write("        </tr>\n");
      out.write("        ");
 } 
      out.write("\n");
      out.write("      </tbody>\n");
      out.write("    </table>\n");
      out.write("    <div class=\"table-summary\">전체 ");
      out.print( refunds.size() );
      out.write("건</div>\n");
      out.write("    ");
 } 
      out.write("\n");
      out.write("  </div>\n");
      out.write("\n");
      out.write("</main>\n");
      out.write("\n");
      out.write("\n");
      out.write("<footer class=\"site-footer\">\n");
      out.write("\n");
      out.write("    <div class=\"footer__top\">\n");
      out.write("        <div class=\"footer__brand\">\n");
      out.write("            <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/\" class=\"logo\">HATSHOP</a>\n");
      out.write("            <p>모자 그 이상의 태도. 절제된 디자인으로<br>매일의 룩을 완성하는 헤드웨어.</p>\n");
      out.write("            <form class=\"footer__news\" onsubmit=\"return false;\">\n");
      out.write("                <input type=\"email\" placeholder=\"이메일로 신상품 소식 받기\" aria-label=\"이메일\">\n");
      out.write("                <button type=\"submit\">→</button>\n");
      out.write("            </form>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        <div class=\"footer__col\">\n");
      out.write("            <h4>쇼핑</h4>\n");
      out.write("            <ul>\n");
      out.write("                <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/hat/list?category=%EB%B3%BC%EC%BA%A1\">볼캡</a></li>\n");
      out.write("                <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/hat/list?category=%EB%B2%84%ED%82%B7%ED%96%87\">버킷햇</a></li>\n");
      out.write("                <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/hat/list?category=%EB%B2%A0%EB%A0%88%EB%AA%A8\">베레모</a></li>\n");
      out.write("                <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/hat/list?category=%ED%8E%98%EB%8F%84%EB%9D%BC\">페도라</a></li>\n");
      out.write("                <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/hat/list?category=%EC%8A%A4%EB%83%85%EB%B0%B1\">스냅백</a></li>\n");
      out.write("                <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/hat/list\">전체 목록</a></li>\n");
      out.write("            </ul>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        <div class=\"footer__col\">\n");
      out.write("            <h4>회원</h4>\n");
      out.write("            <ul>\n");
      out.write("                <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/member/login.jsp\">로그인</a></li>\n");
      out.write("                <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/member/join.jsp\">회원가입</a></li>\n");
      out.write("                <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/member/mypage.jsp\">마이페이지</a></li>\n");
      out.write("                <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/cart/cartList.jsp\">장바구니</a></li>\n");
      out.write("                <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/order/orderList.jsp\">주문내역</a></li>\n");
      out.write("            </ul>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        <div class=\"footer__col\">\n");
      out.write("            <h4>고객센터</h4>\n");
      out.write("            <ul>\n");
      out.write("                <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/info/delivery.jsp\">배송 안내</a></li>\n");
      out.write("                <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/info/returns.jsp\">교환 / 반품</a></li>\n");
      out.write("                <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/info/size-guide.jsp\">사이즈 가이드</a></li>\n");
      out.write("                <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/board/boardList.jsp\">커뮤니티</a></li>\n");
      out.write("            </ul>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <div class=\"footer__bottom\">\n");
      out.write("        <small>© 2026 HATSHOP. All rights reserved.</small>\n");
      out.write("        <div class=\"legal\">\n");
      out.write("            <a href=\"#\">이용약관</a>\n");
      out.write("            <a href=\"#\">개인정보처리방침</a>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("</footer>\n");
      out.write("\n");
      out.write("<!-- ── AI 고객 상담 챗봇 위젯 ── -->\n");
      out.write("<div id=\"hsChatbot\" class=\"hs-chatbot\">\n");
      out.write("  <button id=\"hsChatToggle\" type=\"button\" class=\"hs-chat-toggle\" aria-label=\"고객 상담 챗봇 열기\">💬</button>\n");
      out.write("  <div id=\"hsChatPanel\" class=\"hs-chat-panel\" hidden>\n");
      out.write("    <div class=\"hs-chat-header\">\n");
      out.write("      <span>HATSHOP 고객 상담</span>\n");
      out.write("      <button id=\"hsChatClose\" type=\"button\" class=\"hs-chat-close\" aria-label=\"닫기\">✕</button>\n");
      out.write("    </div>\n");
      out.write("    <div id=\"hsChatBody\" class=\"hs-chat-body\"></div>\n");
      out.write("    <div id=\"hsChatQuick\" class=\"hs-chat-quick\"></div>\n");
      out.write("    <div class=\"ac-wrap\" style=\"margin:0 12px\">\n");
      out.write("      <div id=\"hsAcDropdown\" class=\"ac-dropdown\"></div>\n");
      out.write("    </div>\n");
      out.write("    <form id=\"hsChatForm\" class=\"hs-chat-form\">\n");
      out.write("      <input type=\"text\" id=\"hsChatInput\" placeholder=\"질문을 입력하세요...\" autocomplete=\"off\">\n");
      out.write("      <button type=\"submit\">전송</button>\n");
      out.write("    </form>\n");
      out.write("  </div>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/js/validation.js\"></script>\n");
      out.write("<script>window.HS_CTX = '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("';</script>\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/js/chatbot.js\"></script>\n");
      out.write("</body>\n");
      out.write("</html>\n");
      out.write('\n');
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fwhen_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:when
    org.apache.taglibs.standard.tag.rt.core.WhenTag _jspx_th_c_005fwhen_005f0 = (org.apache.taglibs.standard.tag.rt.core.WhenTag) _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.WhenTag.class);
    try {
      _jspx_th_c_005fwhen_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fwhen_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
      // /WEB-INF/inc/header.jsp(65,12) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fwhen_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${empty sessionScope.loginUser}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fwhen_005f0 = _jspx_th_c_005fwhen_005f0.doStartTag();
      if (_jspx_eval_c_005fwhen_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("                <a href=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/member/login.jsp\">로그인</a>\n");
          out.write("                <a href=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/member/join.jsp\">회원가입</a>\n");
          out.write("            ");
          int evalDoAfterBody = _jspx_th_c_005fwhen_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fwhen_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } finally {
      _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f0);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fotherwise_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fotherwise_005f0);
      // /WEB-INF/inc/header.jsp(72,16) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.loginUser.grade eq 'ADMIN'}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("                    <a href=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/admin/\">관리자</a>\n");
          out.write("                ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } finally {
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
    }
    return false;
  }
}
